<?php

class Stpd_hotelController extends Controller
{
	var $KODE_GOL = 3;
	var $PAJAK_AYAT = 1;
	var $PAJAK_REK = '4.1.1.1.0';

	public function actionIndex()
	{
		$data['theme_baseurl'] = Yii::app()->theme->baseUrl;
		$data['sub_rek'] = TRekening::model()->getRekeningSubAktif('4110100');

		$data['rek'] = Yii::app()->db->createCommand("
		SELECT * 
		FROM TBLREKENING
		WHERE TBLREKENING_KODE LIKE '4.1.1.1.%'
		ORDER BY TBLREKENING_KODE
		")
		->queryAll();

		$this->renderPartial('index', array('data'=>$data));
	}

	public function actionautocompletewphotel()
	{
		header('Content-type: text/json');
		header('Content-type: application/json');
		
		$query = trim($_REQUEST['query']);

		$select = 'TBLDAFTHOTEL.TBLDAFTAR_NOPOK, TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA, TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT';
		$from = 'TBLDAFTHOTEL';
		$filter = array(
			'LK__TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA' => $query
			,'LK__TBLDAFTAR.TBLDAFTAR_NOPOK' => $query
		);

		$filter_AND = array(
			//'EQ__TREKENING_KODE' => '4110100'
			// ,'EQ__tblsubyek_jenisusaha' => $jenisusaha
			// ,'EQ__tblsubyek_isaktif' => "T"
		);

		$otherquery = array(
			'limit'=> 30
			,'join'=> array('TBLDAFTAR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTHOTEL.TBLDAFTAR_NOPOK')
			,'order'=> 'TBLDAFTHOTEL.TBLDAFTAR_NOPOK ASC'
			,'group'=> 'TBLDAFTHOTEL.TBLDAFTAR_NOPOK, TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA, TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT'
		);

		$arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'filter_AND'=>$filter_AND,'filterOR'=>true,'otherquery'=>$otherquery,'mode'=>'LIST');
		$results = DBFetch::query($arrayConfig);

		$suggestions = array();
		 
		foreach($results as $result)
		{
			$suggestions[] = array(
			"value" => $result['TBLDAFTAR_NOPOK']. ' | ' . $result['TBLDAFTAR_BADANUSAHANAMA']
			,"data" => $result['TBLDAFTAR_NOPOK']
			,"TBLDAFTAR_BADANUSAHANAMA" => $result['TBLDAFTAR_BADANUSAHANAMA']
			,"TBLDAFTAR_BADANUSAHAALAMAT" => $result['TBLDAFTAR_BADANUSAHAALAMAT']
			,"TBLDAFTAR_NOPOK" => $result['TBLDAFTAR_NOPOK']
			);
		}
 
		echo CJSON::encode(array('suggestions' => $suggestions));
	}

	public function actiongetdata()
	{
		$TBLDAFTAR_NOPOK = trim($_POST['TBLDAFTAR_NOPOK']);
		$bulan = trim($_POST['bulan']);
		$tahun = trim($_POST['tahun']);
		$tahun_substr = substr($tahun, -2);
		$proses = $this->cekProses($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);
		$cek = $this->cekPernahDaftar($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);
		$bayar =$this->cekBayar($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);

		if ($bayar > 0) {
			$data['data'] = 'sudah dibayar';	
		} else if ($cek == 0){
			$data['data'] = 'belum terdaftar';
		}else if ($proses > 0){
			$data['data'] = 'sudah entri';
			
			$select = "
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			TBLDAFTAR.TBLDAFTAR_ISAKTIF,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKALAMAT,
			REFBADANUSAHA.REKENING_KODE,
			REFBADANUSAHA.REFBADANUSAHA_REKPENDAPATAN,
			REFBADANUSAHA.REFBADANUSAHA_REKPAD,
			REFBADANUSAHA.REFBADANUSAHA_REKPJK,
			REFBADANUSAHA.REFBADANUSAHA_REKAYAT,
			REFBADANUSAHA.REFBADANUSAHA_REKJENIS,
			REFBADANUSAHA.REFBADANUSAHA_PERSEN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_NOMORPERIKSA, 0) AS TBLDAFTHOTEL_NOMORPERIKSA,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKPERIKSA,0) AS TBLDAFTHOTEL_PAJAKPERIKSA,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_NOSURATTAGIHAN, 0) AS TBLDAFTHOTEL_NOSURATTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BUNGATAGIHAN,0) AS TBLDAFTHOTEL_BUNGATAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_DENDAKRGBAYAR,0) AS TBLDAFTHOTEL_KENAIKANKRGBAYAR,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_KENAIKANKRGBAYAR,0) AS TBLDAFTHOTEL_DENDAKRGBAYAR,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHTAGIHAN,0) AS TBLDAFTHOTEL_RUPIAHTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNKBAWAL,0) AS TBLDAFTHOTEL_BLNKBAWAL,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNKBAKHIR,0) AS TBLDAFTHOTEL_BLNKBAKHIR,

			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLSKPD,0) AS TBLDAFTHOTEL_TGLSKPD,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNSKPD,0) AS TBLDAFTHOTEL_BLNSKPD,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNSKPD,0) AS TBLDAFTHOTEL_THNSKPD,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAK, 0) AS TBLDAFTHOTEL_PAJAK,

			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLENTRISETOR,0) AS TBLDAFTHOTEL_TGLENTRISETOR,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNENTRISETOR,0) AS TBLDAFTHOTEL_BLNENTRISETOR,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNENTRISETOR,0) AS TBLDAFTHOTEL_THNENTRISETOR,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_REGSETOR,0) AS TBLDAFTHOTEL_REGSETOR,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR,0) AS TBLDAFTHOTEL_RUPIAHSETOR,

			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLPERIKSA,0) AS TBLDAFTHOTEL_TGLPERIKSA,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNPERIKSA,0) AS TBLDAFTHOTEL_BLNPERIKSA,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNPERIKSA,0) AS TBLDAFTHOTEL_THNPERIKSA,

			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLSURATTAGIHAN,0) AS TBLDAFTHOTEL_TGLSURATTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNSURATTAGIHAN,0) AS TBLDAFTHOTEL_BLNSURATTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNSURATTAGIHAN,0) AS TBLDAFTHOTEL_THNSURATTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLBTSTAGIHAN,0) AS TBLDAFTHOTEL_TGLBTSTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNBTSTAGIHAN,0) AS TBLDAFTHOTEL_BLNBTSTAGIHAN,
			NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNBTSTAGIHAN,0) AS TBLDAFTHOTEL_THNBTSTAGIHAN 
			";
			$from = 'TBLDAFTAR';
			$filter = array(
				'EQ__TBLDAFTAR.TBLDAFTAR_NOPOK' => $TBLDAFTAR_NOPOK
			);

			$filter_AND = array(
				'EQ__TBLDAFTAR.TBLDAFTAR_GOLONGAN' => $this->KODE_GOL
				,'EQ__REFBADANUSAHA.REFBADANUSAHA_REKAYAT' => $this->PAJAK_AYAT
				,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK' => $tahun_substr
				,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_BLNPAJAK' => $bulan
				// ,'EQ__tblsubyek_isaktif' => "T"
			);

			$otherquery = array(
				'limit'=> 30
				,'join'=> array('REFBADANUSAHA', 'REFBADANUSAHA.REFBADANUSAHA_ID= TBLDAFTAR.REFBADANUSAHA_IDBADANUSAHA')
				,'join_2'=> array('TBLDAFTHOTEL', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTHOTEL.TBLDAFTAR_NOPOK')
				,'andwhere'=> 'NVL(TBLDAFTHOTEL.TBLPENDATAAN_TGLPAJAK, 0) = 0'
				,'order'=> 'TBLDAFTAR.TBLDAFTAR_NOPOK ASC'
			);
			$model = DBFetch::query( array('select'=>$select,'from'=>$from,'filter'=>$filter,'filter_AND'=>$filter_AND,'filterOR'=>true,'otherquery'=>$otherquery,'mode'=>'DETAIL') );

			$data['TBLDAFTAR_BADANUSAHANAMA'] =$model['TBLDAFTAR_BADANUSAHANAMA'];
			$data['TBLDAFTAR_BADANUSAHAALAMAT'] =$model['TBLDAFTAR_BADANUSAHAALAMAT'];
			$data['REKENING_KODE'] =$model['REKENING_KODE'];
			$data['TREKENING_TARIF'] =$model['REFBADANUSAHA_PERSEN'];
			
			$data['REFBADANUSAHA_REKPENDAPATAN'] =$model['REFBADANUSAHA_REKPENDAPATAN'];
			$data['REFBADANUSAHA_REKPAD'] =$model['REFBADANUSAHA_REKPAD'];
			$data['REFBADANUSAHA_REKPJK'] =$model['REFBADANUSAHA_REKPJK'];
			$data['REFBADANUSAHA_REKAYAT'] =$model['REFBADANUSAHA_REKAYAT'];
			$data['REFBADANUSAHA_REKJENIS'] =$model['REFBADANUSAHA_REKJENIS'];

			$data['TBLDAFTHOTEL_NOSURATTAGIHAN'] = $model['TBLDAFTHOTEL_NOSURATTAGIHAN'];
			$data['TBLDAFTHOTEL_NOMORPERIKSA'] = $model['TBLDAFTHOTEL_NOMORPERIKSA'];
			$data['TBLDAFTHOTEL_PAJAKPERIKSA'] = $model['TBLDAFTHOTEL_PAJAKPERIKSA']; 
			$data['TBLDAFTHOTEL_BUNGATAGIHAN'] = $model['TBLDAFTHOTEL_BUNGATAGIHAN']; 
			$data['TBLDAFTHOTEL_KENAIKANKRGBAYAR'] = $model['TBLDAFTHOTEL_KENAIKANKRGBAYAR']; 
			$data['TBLDAFTHOTEL_DENDAKRGBAYAR'] = $model['TBLDAFTHOTEL_DENDAKRGBAYAR']; 
			$data['TBLDAFTHOTEL_RUPIAHTAGIHAN'] = $model['TBLDAFTHOTEL_RUPIAHTAGIHAN']; 
			$data['TBLDAFTHOTEL_BLNKBAWAL'] = $model['TBLDAFTHOTEL_BLNKBAWAL']; 
			$data['TBLDAFTHOTEL_BLNKBAKHIR'] = $model['TBLDAFTHOTEL_BLNKBAKHIR']; 
			$data['TBLDAFTHOTEL_TGLSURATTAGIHAN'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLSURATTAGIHAN']); 
			$data['TBLDAFTHOTEL_BLNSURATTAGIHAN'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNSURATTAGIHAN']); 
			$data['TBLDAFTHOTEL_THNSURATTAGIHAN'] = $model['TBLDAFTHOTEL_THNSURATTAGIHAN'];
			$data['TBLDAFTHOTEL_TGLSKPD'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLSKPD']); 
			$data['TBLDAFTHOTEL_BLNSKPD'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNSKPD']); 
			$data['TBLDAFTHOTEL_THNSKPD'] = $model['TBLDAFTHOTEL_THNSKPD'];
			$data['TBLDAFTHOTEL_PAJAK'] = $model['TBLDAFTHOTEL_PAJAK'];
			$data['TBLDAFTHOTEL_TGLENTRISETOR'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLENTRISETOR']); 
			$data['TBLDAFTHOTEL_BLNENTRISETOR'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNENTRISETOR']); 
			$data['TBLDAFTHOTEL_THNENTRISETOR'] = $model['TBLDAFTHOTEL_THNENTRISETOR'];
			$data['TBLDAFTHOTEL_REGSETOR'] = $model['TBLDAFTHOTEL_REGSETOR'];
			$data['TBLDAFTHOTEL_RUPIAHSETOR'] = $model['TBLDAFTHOTEL_RUPIAHSETOR'];
			$data['TBLDAFTHOTEL_TGLPERIKSA'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLPERIKSA']); 
			$data['TBLDAFTHOTEL_BLNPERIKSA'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNPERIKSA']); 
			$data['TBLDAFTHOTEL_THNPERIKSA'] = $model['TBLDAFTHOTEL_THNPERIKSA'];
			$data['TBLDAFTHOTEL_TGLBTSTAGIHAN'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLBTSTAGIHAN']); 
			$data['TBLDAFTHOTEL_BLNBTSTAGIHAN'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNBTSTAGIHAN']); 
			$data['TBLDAFTHOTEL_THNBTSTAGIHAN'] = $model['TBLDAFTHOTEL_THNBTSTAGIHAN']; 
			
			// }
		
		
		} else {

		$data['data'] = 'sudah terdaftar';
		
		$select = "
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_ISAKTIF,
		TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
		TBLDAFTAR.TBLDAFTAR_PEMILIKALAMAT,
		REFBADANUSAHA.REKENING_KODE,
		REFBADANUSAHA.REFBADANUSAHA_REKPENDAPATAN,
		REFBADANUSAHA.REFBADANUSAHA_REKPAD,
		REFBADANUSAHA.REFBADANUSAHA_REKPJK,
		REFBADANUSAHA.REFBADANUSAHA_REKAYAT,
		REFBADANUSAHA.REFBADANUSAHA_REKJENIS,
		REFBADANUSAHA.REFBADANUSAHA_PERSEN,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLSKPD,0) AS TBLDAFTHOTEL_TGLSKPD,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNSKPD,0) AS TBLDAFTHOTEL_BLNSKPD,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNSKPD,0) AS TBLDAFTHOTEL_THNSKPD,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAK,0) AS TBLDAFTHOTEL_PAJAK,

		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLENTRISETOR,0) AS TBLDAFTHOTEL_TGLENTRISETOR,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNENTRISETOR,0) AS TBLDAFTHOTEL_BLNENTRISETOR,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNENTRISETOR,0) AS TBLDAFTHOTEL_THNENTRISETOR,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_REGSETOR,0) AS TBLDAFTHOTEL_REGSETOR,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR,0) AS TBLDAFTHOTEL_RUPIAHSETOR,

		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_TGLPERIKSA,0) AS TBLDAFTHOTEL_TGLPERIKSA,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNPERIKSA,0) AS TBLDAFTHOTEL_BLNPERIKSA,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_THNPERIKSA,0) AS TBLDAFTHOTEL_THNPERIKSA,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_NOMORPERIKSA, 0) AS TBLDAFTHOTEL_NOMORPERIKSA,
		NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKPERIKSA,0) AS TBLDAFTHOTEL_PAJAKPERIKSA
		";
		$from = 'TBLDAFTAR';
		$filter = array(
			'EQ__TBLDAFTAR.TBLDAFTAR_NOPOK' => $TBLDAFTAR_NOPOK
		);

		$filter_AND = array(
			'EQ__TBLDAFTAR.TBLDAFTAR_GOLONGAN' => $this->KODE_GOL
			,'EQ__REFBADANUSAHA.REFBADANUSAHA_REKAYAT' => $this->PAJAK_AYAT
			,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK' => $tahun_substr
			,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_BLNPAJAK' => $bulan
			// ,'EQ__tblsubyek_isaktif' => "T"
		);

		$otherquery = array(
			'limit'=> 30
			,'join'=> array('REFBADANUSAHA', 'REFBADANUSAHA.REFBADANUSAHA_ID= TBLDAFTAR.REFBADANUSAHA_IDBADANUSAHA')
			,'join_2'=> array('TBLDAFTHOTEL', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTHOTEL.TBLDAFTAR_NOPOK')
			,'andwhere'=> 'NVL(TBLDAFTHOTEL.TBLPENDATAAN_TGLPAJAK, 0) = 0'
			,'order'=> 'TBLDAFTAR_NOPOK ASC'
		);
		$model = DBFetch::query( array('select'=>$select,'from'=>$from,'filter'=>$filter,'filter_AND'=>$filter_AND,'filterOR'=>true,'otherquery'=>$otherquery,'mode'=>'DETAIL') );

		$data['TBLDAFTAR_BADANUSAHANAMA'] =$model['TBLDAFTAR_BADANUSAHANAMA'];
		$data['TBLDAFTAR_BADANUSAHAALAMAT'] =$model['TBLDAFTAR_BADANUSAHAALAMAT'];
		$data['REKENING_KODE'] =$model['REKENING_KODE'];
		$data['TREKENING_TARIF'] =$model['REFBADANUSAHA_PERSEN'];
		
		$data['REFBADANUSAHA_REKPENDAPATAN'] =$model['REFBADANUSAHA_REKPENDAPATAN'];
		$data['REFBADANUSAHA_REKPAD'] =$model['REFBADANUSAHA_REKPAD'];
		$data['REFBADANUSAHA_REKPJK'] =$model['REFBADANUSAHA_REKPJK'];
		$data['REFBADANUSAHA_REKAYAT'] =$model['REFBADANUSAHA_REKAYAT'];
		$data['REFBADANUSAHA_REKJENIS'] =$model['REFBADANUSAHA_REKJENIS'];
		$data['TBLDAFTHOTEL_TGLSKPD'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLSKPD']); 
		$data['TBLDAFTHOTEL_BLNSKPD'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNSKPD']); 
		$data['TBLDAFTHOTEL_THNSKPD'] = $model['TBLDAFTHOTEL_THNSKPD'];
		$data['TBLDAFTHOTEL_PAJAK'] =$model['TBLDAFTHOTEL_PAJAK'];
		$data['TBLDAFTHOTEL_TGLENTRISETOR'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLENTRISETOR']); 
		$data['TBLDAFTHOTEL_BLNENTRISETOR'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNENTRISETOR']); 
		$data['TBLDAFTHOTEL_THNENTRISETOR'] = $model['TBLDAFTHOTEL_THNENTRISETOR'];
		$data['TBLDAFTHOTEL_REGSETOR'] = $model['TBLDAFTHOTEL_REGSETOR'];
		$data['TBLDAFTHOTEL_RUPIAHSETOR'] = $model['TBLDAFTHOTEL_RUPIAHSETOR'];
		$data['TBLDAFTHOTEL_TGLPERIKSA'] = sprintf("%02d",$model['TBLDAFTHOTEL_TGLPERIKSA']); 
		$data['TBLDAFTHOTEL_BLNPERIKSA'] = sprintf("%02d",$model['TBLDAFTHOTEL_BLNPERIKSA']); 
		$data['TBLDAFTHOTEL_THNPERIKSA'] = $model['TBLDAFTHOTEL_THNPERIKSA'];
		$data['TBLDAFTHOTEL_NOMORPERIKSA'] = $model['TBLDAFTHOTEL_NOMORPERIKSA'];
		$data['TBLDAFTHOTEL_PAJAKPERIKSA'] = $model['TBLDAFTHOTEL_PAJAKPERIKSA'];

		}

		echo CJSON::encode($data);
	}

		public function actioncekSudahBayar()
	{
		$NOPOKOK = $_REQUEST['NOPOKOK'];
		$THNPAJAK = substr($_REQUEST['TAHUN'], -2);
		$BLNPAJAK = $_REQUEST['BULAN'];
		$jns = 'K';

		$sql = "SELECT COUNT(TBLPENDATAAN_THNPAJAK) AS JML FROM TBLSETOR WHERE TBLPENDATAAN_THNPAJAK =".$THNPAJAK." AND TBLPENDATAAN_BLNPAJAK=".$BLNPAJAK." AND TBLDAFTAR_NOPOK=".$NOPOKOK." AND TBLSETOR_JNSBAYAR = 'STPD'";
		$cek = Yii::app()->db->createCommand($sql)->queryScalar();
		if ($cek) {
			echo CJSON::encode(array('status'=>'sudah'));
		}
		else{
			echo CJSON::encode(array('status'=>'belum'));
		}
	}

	public function cekProses($tahun, $bulan, $TBLDAFTAR_NOPOK)
	{
		$model = Yii::app()->db->createCommand('SELECT NVL(TBLDAFTHOTEL_NOSURATTAGIHAN,0) FROM TBLDAFTHOTEL WHERE TBLPENDATAAN_THNPAJAK ='.$tahun.' AND TBLPENDATAAN_BLNPAJAK='.$bulan.' AND TBLDAFTAR_NOPOK='.$TBLDAFTAR_NOPOK.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function cekBayar($THNPAJAK, $BLNPAJAK, $NOPOKOK)
	{
		$model = Yii::app()->db->createCommand("SELECT COUNT(TBLPENDATAAN_THNPAJAK) AS JML FROM TBLSETORANBPD WHERE TBLPENDATAAN_THNPAJAK =".$THNPAJAK." AND TBLPENDATAAN_BLNPAJAK=".$BLNPAJAK." AND TBLDAFTAR_NOPOK=".$NOPOKOK." AND TBLSETORANBPD_JNSBAYAR = 'STPD'")->queryScalar();
		return $model;
	}

	public function cekPernahDaftar($thn, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT COUNT(TBLPENDATAAN_THNPAJAK) AS JML FROM TBLDAFTHOTEL WHERE TBLPENDATAAN_THNPAJAK ='.$thn.' AND TBLPENDATAAN_BLNPAJAK='.$bulan.' AND TBLDAFTAR_NOPOK='.$nopok.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function CekNoRegisterKB($tahun, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT NVL(TBLDAFTHOTEL_NOSURATTAGIHAN,0) AS NOKB FROM TBLDAFTHOTEL WHERE TBLPENDATAAN_THNPAJAK = '.$tahun.' AND TBLPENDATAAN_BLNPAJAK = '.$bulan.' AND TBLDAFTAR_NOPOK = '.$nopok.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function GetLastNoKB($tahun, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT MAX(NVL(TBLKRGBAYAR_REGKURANGBAYAR,0)) AS LAST_KB FROM TBLKRGBAYAR WHERE TBLPENDATAAN_THNPAJAK = '.$tahun.' AND TBLPENDATAAN_BLNPAJAK = '.$bulan.' AND TBLDAFTAR_NOPOK = '.$nopok.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function actionSimpanSKPDKBHotel()
	{
		Yii::import('ext.LokalIndonesia');

		$PARAM = $_REQUEST;
		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];

		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);

		$TBLPENDATAAN_BLNPAJAK = !empty($_REQUEST['TBLPENDATAAN_BLNPAJAK']) ? $_REQUEST['TBLPENDATAAN_BLNPAJAK'] : '';

		$TBLDAFTHOTEL_TGLSURATTAGIHAN = !empty($_REQUEST['TBLDAFTHOTEL_TGLSURATTAGIHAN']) ? $_REQUEST['TBLDAFTHOTEL_TGLSURATTAGIHAN'] : '';

		$TBLDAFTHOTEL_TGLBTSTAGIHAN = !empty($_REQUEST['TBLDAFTHOTEL_TGLBTSTAGIHAN']) ? $_REQUEST['TBLDAFTHOTEL_TGLBTSTAGIHAN'] : '';

		$TBLDAFTHOTEL_TGLPERIKSA = !empty($_REQUEST['TBLDAFTHOTEL_TGLPERIKSA']) ? $_REQUEST['TBLDAFTHOTEL_TGLPERIKSA'] : '';

		if ($TBLDAFTHOTEL_TGLSURATTAGIHAN !='') {
			$exp_TGLTERIMADAFTAR = explode('-', $TBLDAFTHOTEL_TGLSURATTAGIHAN);
			$pecahtgldaftar = $exp_TGLTERIMADAFTAR[0];
			$pecahbulandaftar = $exp_TGLTERIMADAFTAR[1];
			$pecahthndaftar = substr($exp_TGLTERIMADAFTAR[2], -2);	
		} else {
			$pecahtgldaftar = '';
			$pecahbulandaftar = '';
			$pecahthndaftar = '';
		}

		if ($TBLDAFTHOTEL_TGLBTSTAGIHAN !='') {	
			$exp_TGLENTRYDAFTAR = explode('-', $TBLDAFTHOTEL_TGLBTSTAGIHAN);
			$pecahtglentry = $exp_TGLENTRYDAFTAR[0];
			$pecahbulanentry = $exp_TGLENTRYDAFTAR[1];
			$pecahthnentry = substr($exp_TGLENTRYDAFTAR[2], -2);
		} else {
			$pecahtglentry = '';
			$pecahbulanentry = '';
			$pecahthnentry = '';
		}

		if ($TBLDAFTHOTEL_TGLPERIKSA !='') {
			$exp_TGLPERIKSA = explode('-', $TBLDAFTHOTEL_TGLPERIKSA);
			$pecahtglperiksa = $exp_TGLPERIKSA[0];
			$pecahbulanperiksa = $exp_TGLPERIKSA[1];
			$pecahthnperiksa = substr($exp_TGLPERIKSA[2], -2);
		} else {
			$pecahtglperiksa = '';
			$pecahbulanperiksa = '';
			$pecahthnperiksa = '';
		}

		$command = Yii::app()->db->createCommand();
		$column = array(

			'TBLDAFTHOTEL_NOSURATTAGIHAN' => LokalIndonesia::toAngka($PARAM['TBLDAFTHOTEL_NOSURATTAGIHAN']),
			'TBLDAFTHOTEL_BUNGATAGIHAN' => LokalIndonesia::toAngka($PARAM['TBLDAFTHOTEL_BUNGATAGIHAN']),
			'TBLDAFTHOTEL_RUPIAHTAGIHAN' => LokalIndonesia::toAngka($PARAM['TBLDAFTHOTEL_RUPIAHTAGIHAN']),
			
			'TBLDAFTHOTEL_TGLSURATTAGIHAN' => $pecahtgldaftar,
			'TBLDAFTHOTEL_BLNSURATTAGIHAN' => $pecahbulandaftar,
			'TBLDAFTHOTEL_THNSURATTAGIHAN' => $pecahthndaftar,

			'TBLDAFTHOTEL_TGLBTSTAGIHAN' => $pecahtglentry,
			'TBLDAFTHOTEL_BLNBTSTAGIHAN' => $pecahbulanentry,
			'TBLDAFTHOTEL_THNBTSTAGIHAN' => $pecahthnentry,

		);

		$simpan = $command->update('TBLDAFTHOTEL', $column ,'TBLDAFTAR_NOPOK =:NOPOK AND TBLPENDATAAN_THNPAJAK =:THNPJK AND TBLPENDATAAN_BLNPAJAK =:TBLPENDATAAN_BLNPAJAK AND (TBLPENDATAAN_TGLPAJAK IS NULL OR TBLPENDATAAN_TGLPAJAK = 0)',array(':NOPOK' => $NOPOK,':THNPJK' => $THNPJK,':TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK));


		
			if ($simpan>=0) {
				echo CJSON::encode(array('status'=>'success'));
			}
			else{
				echo CJSON::encode(array('status'=>'failed'));
			}
	}

	public function actionHapusSKPDKB()
	{
		Yii::import('ext.LokalIndonesia');

		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];

		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);

		$TBLPENDATAAN_BLNPAJAK = !empty($_REQUEST['TBLPENDATAAN_BLNPAJAK']) ? $_REQUEST['TBLPENDATAAN_BLNPAJAK'] : '';

		$command = Yii::app()->db->createCommand();
		$column = array(

			'TBLDAFTHOTEL_NOSURATTAGIHAN' => '',
			'TBLDAFTHOTEL_BUNGATAGIHAN' => '',
			'TBLDAFTHOTEL_RUPIAHTAGIHAN' => '',

			'TBLDAFTHOTEL_TGLSURATTAGIHAN' => '',
			'TBLDAFTHOTEL_BLNSURATTAGIHAN' => '',
			'TBLDAFTHOTEL_THNSURATTAGIHAN' => '',

			'TBLDAFTHOTEL_TGLBTSTAGIHAN' => '',
			'TBLDAFTHOTEL_BLNBTSTAGIHAN' => '',
			'TBLDAFTHOTEL_THNBTSTAGIHAN' => '',

		);

		$simpan = $command->update('TBLDAFTHOTEL', $column ,'TBLDAFTAR_NOPOK =:NOPOK AND TBLPENDATAAN_THNPAJAK =:THNPJK AND TBLPENDATAAN_BLNPAJAK =:TBLPENDATAAN_BLNPAJAK AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0',array(':NOPOK' => $NOPOK,':THNPJK' => $THNPJK,':TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK));

		if ($simpan>=0) {
			echo CJSON::encode(array('status'=>'success'));
		}
		else{
			echo CJSON::encode(array('status'=>'failed'));
		}
	}

	public function actionGetNoSKPDKB()
	{
		$tahun = $_REQUEST['tahun'];
		$splthn = substr($tahun, -2);

		$data = Yii::app()->db->createCommand("SELECT
			MAX(TO_NUMBER (TO_CHAR(NVL(TBLDAFTHOTEL_NOSURATTAGIHAN, 0))))+1 AS nokb
		FROM
			TBLDAFTHOTEL
		WHERE
			TBLPENDATAAN_THNPAJAK = ".$splthn."
		AND NVL (TBLDAFTHOTEL_NOSURATTAGIHAN, 0) <> 0
		ORDER BY
			TO_NUMBER (TO_CHAR(NVL(nokb, 0))) DESC")->queryRow();

		echo CJSON::encode($data);
	}

	public function actionCetak()
	{
		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];
		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);
		$TBLPENDATAAN_BLNPAJAK = $_REQUEST['TBLPENDATAAN_BLNPAJAK'];

        $select = "
        TBLDAFTHOTEL.*,
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BUNGATAGIHAN, 0) AS TBLDAFTHOTEL_BUNGATAGIHAN, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_KENAIKANKRGBAYAR, 0) AS TBLDAFTHOTEL_DENDAKRGBAYAR, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) AS TBLDAFTHOTEL_RUPIAHSETOR, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNKBAWAL, 0) AS TBLDAFTHOTEL_BLNKBAWAL, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNKBAKHIR, 0) AS TBLDAFTHOTEL_BLNKBAKHIR, 
        TBLDAFTAR.*, (
		SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
			TBLREKENING
		WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTHOTEL.TBLDAFTHOTEL_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTHOTEL.TBLDAFTHOTEL_REKJENIS
	) AS NMREK,
	(
		SELECT
		TBLREKENING.TBLREKENING_KODEFULL
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTHOTEL.TBLDAFTHOTEL_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTHOTEL.TBLDAFTHOTEL_REKJENIS
		) AS TBLREKENING_KODEFULL,
	(
		SELECT
			REFKECAMATAN.REFKECAMATAN_NAMA
		FROM
			REFKECAMATAN
		WHERE
			REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
	) AS bnmkec,
	(
		SELECT
			REFKELURAHAN.REFKELURAHAN_NAMA
		FROM
			REFKELURAHAN
		WHERE
			REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_KODE
	) AS bnmkel,
	(
		SELECT
			REFKECAMATAN.REFKECAMATAN_NAMA
		FROM
			REFKECAMATAN
		WHERE
			REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
	) AS pnmkec,
	(
		SELECT
			REFKELURAHAN.REFKELURAHAN_NAMA
		FROM
			REFKELURAHAN
		WHERE
			REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDPEMILIK
		AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
	) AS pnmkel";
        $from = 'TBLDAFTHOTEL';

        $otherquery = array(
             'leftjoin_daftar'=>array('TBLDAFTAR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTHOTEL.TBLDAFTAR_NOPOK')
        );

        $filter = array(
            'EQ__TBLDAFTHOTEL.TBLDAFTAR_NOPOK' => $NOPOK
			,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK' => $THNPJK
			,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK
        );

        $arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'otherquery'=>$otherquery,'mode'=>'DETAIL');
        $data['cetak'] = DBFetch::query($arrayConfig);

		$this->renderPartial('cetak',array('data'=>$data));
	}

	public function actionCetakWord()
	{
		// error_reporting(0);

		// baca file template, yg dipakai
		// $gettpl = MasterTemplate::model()->find('tblmastertemplate_jenis="WORD" AND tblmastertemplate_kelompok="tpl_bakecamatan" AND tblmastertemplate_isaktif="T"');
		
		// echo "$query";
		
		// $data['list_kartudata'] = Yii::app()->db->createCommand($query)->queryAll();

		$path_tpl =  dirname(Yii::app()->basePath) . DIRECTORY_SEPARATOR . 'file' . DIRECTORY_SEPARATOR . 'tpl_penagihan' . DIRECTORY_SEPARATOR;
		$namatpl = $path_tpl . 'STPD.docx';

		Yii::import('ext.DMOpenTBS',true);
		Yii::import('ext.LokalIndonesia');
		DMOpenTBS::init();
		$otbs = new clsTinyButStrong;

		// Useful for debugging purposes. Displays the errors
		$otbs->NoErr = 0;
		$otbs->Plugin(TBS_INSTALL, OPENTBS_PLUGIN); // load the OpenTBS plugin

		$template = $namatpl;
		$otbs->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // load the template

		// Delete a sheet 
		// $otbs->PlugIn(OPENTBS_DELETE_SHEETS, 'Delete me'); 


		// Display a sheet (make it visible) 
		// $otbs->PlugIn(OPENTBS_DISPLAY_SHEETS, 'Display me'); 

		// Change the current sheet 
		// $otbs->PlugIn(OPENTBS_SELECT_SHEET, 2); 

		// A recordset for merging tables

		//INI CODING QUERY CETAK WORD

		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];
		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);
		$TBLPENDATAAN_BLNPAJAK = $_REQUEST['TBLPENDATAAN_BLNPAJAK'];

        $select = "
        TBLDAFTHOTEL.*,
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BUNGATAGIHAN, 0) AS TBLDAFTHOTEL_BUNGATAGIHAN, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) AS TBLDAFTHOTEL_RUPIAHSETOR, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNKBAWAL, 0) AS TBLDAFTHOTEL_BLNKBAWAL, 
        NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_BLNKBAKHIR, 0) AS TBLDAFTHOTEL_BLNKBAKHIR, 
        TBLDAFTAR.*, (
		SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
			TBLREKENING
		WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTHOTEL.TBLDAFTHOTEL_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTHOTEL.TBLDAFTHOTEL_REKJENIS
		) AS NMREK,
		(
			SELECT
			TBLREKENING.TBLREKENING_KODEFULL
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTHOTEL.TBLDAFTHOTEL_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTHOTEL.TBLDAFTHOTEL_REKJENIS
			) AS TBLREKENING_KODEFULL,
		(
			SELECT
				REFKECAMATAN.REFKECAMATAN_NAMA
			FROM
				REFKECAMATAN
			WHERE
				REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		) AS bnmkec,
		(
			SELECT
				REFKELURAHAN.REFKELURAHAN_NAMA
			FROM
				REFKELURAHAN
			WHERE
				REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
			AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_KODE
		) AS bnmkel,
		(
			SELECT
				REFKECAMATAN.REFKECAMATAN_NAMA
			FROM
				REFKECAMATAN
			WHERE
				REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
		) AS pnmkec,
		(
			SELECT
				REFKELURAHAN.REFKELURAHAN_NAMA
			FROM
				REFKELURAHAN
			WHERE
				REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDPEMILIK
			AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
		) AS pnmkel";
        $from = 'TBLDAFTHOTEL';

        $otherquery = array(
             'leftjoin_daftar'=>array('TBLDAFTAR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTHOTEL.TBLDAFTAR_NOPOK')
             ,'andwhere'=> 'NVL(TBLDAFTHOTEL.TBLPENDATAAN_TGLPAJAK, 0) = 0'
        );

        $filter = array(
            'EQ__TBLDAFTHOTEL.TBLDAFTAR_NOPOK' => $NOPOK
			,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK' => $THNPJK
			,'EQ__TBLDAFTHOTEL.TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK
        );

        $arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'otherquery'=>$otherquery,'mode'=>'DETAIL');
        $data['cetak'] = DBFetch::query($arrayConfig);

        $sql1="SELECT * FROM TBLPEJABAT WHERE REFJABATAN_ID = 8";
        $data['jab1'] = Yii::app()->db->createCommand($sql1)->queryRow();

		$dt = array();

		$GLOBALS['jabatan1'] = $data['jab1']['TBLPEJABAT_URAIAN'];
		$GLOBALS['petugas1'] = $data['jab1']['TBLPEJABAT_NAMA'];
		$GLOBALS['nip1'] = $data['jab1']['TBLPEJABAT_NIP'];

		$dt['nopok'] = $data['cetak']['TBLDAFTAR_NOPOK'];

		$dt['thnkb'] = '20'.$data['cetak']['TBLDAFTHOTEL_THNSURATTAGIHAN'];
		$dt['regkb'] = $data['cetak']['TBLDAFTHOTEL_NOSURATTAGIHAN'];

		$dt['namabadan'] = $data['cetak']['TBLDAFTAR_BADANUSAHANAMA'];
		$dt['alamatbadan'] = $data['cetak']['TBLDAFTAR_BADANUSAHAALAMAT'];

		$dt['kodefull'] = $data['cetak']['TBLREKENING_KODEFULL'];

		$dt['namarek'] = $data['cetak']['NMREK'];

		$dt['namarek'] = $data['cetak']['NMREK'];

		$dt['ketetapan'] = $data['cetak']['TBLDAFTHOTEL_TGLSURATTAGIHAN'] .'/'. $data['cetak']['TBLDAFTHOTEL_BLNSURATTAGIHAN'] .'/20'.$data['cetak']['TBLDAFTHOTEL_THNSURATTAGIHAN'];

		$dt['jatuhtempo'] = $data['cetak']['TBLDAFTHOTEL_TGLBTSTAGIHAN'] .'/'. $data['cetak']['TBLDAFTHOTEL_BLNBTSTAGIHAN'] .'/20'.$data['cetak']['TBLDAFTHOTEL_THNBTSTAGIHAN'];

		$dt['tglsetor'] = $data['cetak']['TBLDAFTHOTEL_TANGGALSETOR'] .'/'. $data['cetak']['TBLDAFTHOTEL_BULANSETOR'] .'/20'.$data['cetak']['TBLDAFTHOTEL_TAHUNSETOR'];

		// $dt['pajakperiksa'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTHOTEL_PAJAKPERIKSA']);
		$dt['bunga'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTHOTEL_BUNGATAGIHAN']);
		// $dt['denda'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTHOTEL_DENDAKRGBAYAR']);
		$dt['denda'] = '';
		$dt['setoran'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTHOTEL_RUPIAHSETOR']);
		$dt['pajak'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTHOTEL_PAJAK']);
		$dt['total'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTHOTEL_BUNGATAGIHAN']);
		$dt['terbilang'] = LokalIndonesia::terbilangangka($data['cetak']['TBLDAFTHOTEL_BUNGATAGIHAN']);

		$dt['thnpajak'] = '20'.$data['cetak']['TBLPENDATAAN_THNPAJAK'];

		$dt['blnpajak'] = LokalIndonesia::getbulan($data['cetak']['TBLPENDATAAN_BLNPAJAK']);

		$dt['npwpd'] = $data['cetak']['TBLDAFTAR_JENISPENDAPATAN'] .'.'. $data['cetak']['TBLDAFTAR_GOLONGAN'] .'.'. $data['cetak']['TBLDAFTAR_NOPOK'] .'.'. sprintf("%02d",$data['cetak']['TBLKECAMATAN_IDBADANUSAHA']) .'.'. sprintf("%02d",$data['cetak']['TBLKELURAHAN_IDBADANUSAHA']);

		// $dt['totalpajak'] = LokalIndonesia::ribuan($totalpajak['totalpajak']);
		$dt['datenow'] = date('d') .' '. LokalIndonesia::getbulan(date('m')) .' '. date('Y');
		
		//SAMPAI SINI QUERYNYA

		// var_dump($data);
		// echo json_encode($data['cetak']);Yii::app()->end();
		// echo json_encode($row);

		// Merge data in the first sheet 
		$npwpd = $data['cetak']['TBLDAFTAR_NOPOK'];
		$namafileDL = "STPD-HOTEL-".$npwpd.".docx";
		$otbs->MergeField('dt', $dt); 
		// $otbs->MergeField('setoran', $setoran); 
		// $otbs->PlugIn(OPENTBS_DEBUG_XML_CURRENT); // debug the template

		$otbs->Show(OPENTBS_DOWNLOAD, $namafileDL);
		Yii::app()->end();
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}