<?php

class Presentase_penerimaanController extends Controller
{
	public function init()
	{
		Yii::import('ext.DBFetch');
	}

	public function actionIndex()
	{
		$data['rek'] = Yii::app()->db->createCommand('
			SELECT
			*
			FROM
			TBLREKENING
			WHERE
			TBLREKENING_REKPAJAK = 1
			AND TBLREKENING_REKPAD = 1
			AND TBLREKENING_REKJENIS = 0
			ORDER BY
			TBLREKENING_REKPENDAPATAN,
			TBLREKENING_REKPAD,
			TBLREKENING_REKPAJAK,
			TBLREKENING_REKAYAT,
			TBLREKENING_REKJENIS
			')->queryAll();
		$this->renderPartial('index', array('data'=>$data));
	}

	public function actionCari()
	{
		$ayat = $_REQUEST['ayat'] ? $_REQUEST['ayat'] : '0';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '0';
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '0';

		$cari = "SELECT
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR = '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS BULAN_INI,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR < '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANLALU,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANINI,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK,
		NVL (
		(
		SELECT
		SUM (
		TBLREKTARGET.TBLREKENING_TARGETANGGARAN
		) AS TARGETANGGARAN
		FROM
		TBLREKTARGET
		WHERE
		TBLREKTARGET.REFBADANUSAHA_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKTARGET.PAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKTARGET.PJK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKTARGET.AYT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKTARGET.REFBADANUSAHA_JENIS = TBLSETOR.TBLSETOR_REKJENIS
		GROUP BY
		TBLSETOR_REKPENDAPATAN,
		TBLSETOR_REKPAD,
		TBLSETOR_REKPAJAK,
		TBLSETOR_REKAYAT,
		TBLSETOR_REKJENIS
		),
		0
		) AS TARGETANGGARAN
		FROM
		TBLSETOR
		WHERE
		TBLSETOR.TBLSETOR_THNSETOR = '$tahun'
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
		AND TBLSETOR.TBLSETOR_REKPAD = 1
		AND TBLSETOR.TBLSETOR_REKPAJAK = 1
		AND TBLSETOR.TBLSETOR_REKAYAT = '$ayat'
		AND TBLSETOR_STATUSBAYAR <> 20
		GROUP BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS
		HAVING
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) > 0
		ORDER BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS";

		$data['cari'] = $cari = Yii::app()->db->createCommand($cari)->queryAll();
		$this->renderPartial('tabel_laporan',array('data'=>$data));

	}

	public function actionCetak()
	{
		$ayat = $_REQUEST['ayat'] ? $_REQUEST['ayat'] : '0';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '0';
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '0';

		$cetak = "SELECT
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR = '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS BULAN_INI,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR < '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANLALU,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANINI,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK,
		NVL (
		(
		SELECT
		SUM (
		TBLREKTARGET.TBLREKENING_TARGETANGGARAN
		) AS TARGETANGGARAN
		FROM
		TBLREKTARGET
		WHERE
		TBLREKTARGET.REFBADANUSAHA_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKTARGET.PAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKTARGET.PJK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKTARGET.AYT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKTARGET.REFBADANUSAHA_JENIS = TBLSETOR.TBLSETOR_REKJENIS
		GROUP BY
		TBLSETOR_REKPENDAPATAN,
		TBLSETOR_REKPAD,
		TBLSETOR_REKPAJAK,
		TBLSETOR_REKAYAT,
		TBLSETOR_REKJENIS
		),
		0
		) AS TARGETANGGARAN
		FROM
		TBLSETOR
		WHERE
		TBLSETOR.TBLSETOR_THNSETOR = '$tahun'
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
		AND TBLSETOR.TBLSETOR_REKPAD = 1
		AND TBLSETOR.TBLSETOR_REKPAJAK = 1
		AND TBLSETOR.TBLSETOR_REKAYAT = '$ayat'
		AND TBLSETOR_STATUSBAYAR <> 20
		GROUP BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS
		HAVING
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= '$bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) > 0
		ORDER BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS";

		$header = "
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS TBLREKENING_NAMAREKENING,
		TBLSETOR.*
		FROM
		TBLSETOR
		INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR.TBLSETOR_THNSETOR = 15
		AND TBLSETOR.TBLSETOR_BLNSETOR = 3
		AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
		AND TBLSETOR.TBLSETOR_REKPAD = 1
		AND TBLSETOR.TBLSETOR_REKPAJAK = 1
		AND TBLSETOR.TBLSETOR_REKAYAT = '$ayat'
		ORDER BY
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_REKPENDAPATAN";
		$data['header'] = $header = Yii::app()->db->createCommand($header)->queryrow();

		$data['cetak'] = $cetak = Yii::app()->db->createCommand($cetak)->queryAll();
		if (isset($_REQUEST['jenis']) AND ($_REQUEST['jenis'])=='excel') {
			header('Content-Type: application/excel');
			header("Content-Disposition: attachment;Filename=Cetak-Jenis.xls");
		}	
		$this->renderPartial('cetak',array('data'=>$data));
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}