<?php

class Kasumum_harianController extends Controller
{
	public function actionIndex()
	{
		$this->renderPartial('index');
	}
	public function actionCetak()
	{
		//$cmd = $_REQUEST['cmd'];
		$tahun  =substr($_REQUEST['tahun'], -2) ;
		$bulan = $_REQUEST['bulan'];
		$tanggal = $_REQUEST['tanggal'];
		$data=array();


		$wheretahun = '';
		if (!empty($tahun)) {
			$wheretahun = ' AND "TBLDAFTREKLAME".TBLPENDATAAN_THNPAJAK = ' . substr($tahun, -2);
		}

		$wherebulan = '';
		if (!empty($bulan)) {
			$wherebulan = ' AND "TBLDAFTREKLAME".TBLPENDATAAN_BLNPAJAK = ' . $bulan;
		}

		$wheretanggal = '';
		if (!empty($tanggal)) {
			$wheretanggal = ' AND "TBLDAFTREKLAME".TBLPENDATAAN_TGLPAJAK = ' . $tanggal;
		}

		$sql = "SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (
			TBLDAFTAR_BADANUSAHANAMA,
			'PBB'
			) AS TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		WHERE
		TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
		AND TBLSETOR.TBLSETOR_TGLSETOR = ".$tanggal."
		ORDER BY
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS
		";
		$data['hasil'] = $hasil = Yii::app()->db->createCommand($sql)->queryAll();

		$this->renderPartial('cetak', array('data'=>$data));
	
}
}