<?php

class Lap_ayatbulanController extends Controller
{
	public function actionIndex()
	{
		$this->renderPartial('index');
	}

	public function actionCetak()
	{
		$tahun =substr($_REQUEST['tahun'], -2);
		$bulan = $_REQUEST['bulan'];
		$rekening = $_REQUEST['rekening'];
		$data=array();

		$sql = "
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS TBLREKENING_NAMAREKENING,
		TBLSETOR.*
		FROM
		TBLSETOR
		INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
		AND TBLSETOR_STATUSBAYAR = 20
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
		AND TBLSETOR.TBLSETOR_REKPAD = 1
		AND TBLSETOR.TBLSETOR_REKPAJAK = 1
		AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."
		ORDER BY
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_REKPENDAPATAN";

		$data['ayatbulan'] = $ayatbulan = Yii::app()->db->createCommand($sql)->queryAll();
		
		$sqltotal="SELECT
		SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR = 8 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS bulanini,
		SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR < 8 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanlalu,
		SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR <= 8 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanini
		FROM
		TBLSETOR
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR.TBLSETOR_THNSETOR = 14
		AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
		AND TBLSETOR.TBLSETOR_REKPAD = 1
		AND TBLSETOR.TBLSETOR_REKPAJAK = 1
		AND TBLSETOR.TBLSETOR_REKAYAT = 1";
		// UNTUK PAJAK YANG LAIN GANTI KONDISI WHERE MENJADI
		// TBLSETOR.TBLSETOR_REKAYAT = 1 => HOTEL
		// TBLSETOR.TBLSETOR_REKAYAT = 2 => RMAKAN
		// TBLSETOR.TBLSETOR_REKAYAT = 3 => HIBURAN
		// TBLSETOR.TBLSETOR_REKAYAT = 4 => REKLAME
		// TBLSETOR.TBLSETOR_REKAYAT = 5 => PPJ
		// TBLSETOR.TBLSETOR_REKAYAT = 7 => PAKKIR
		// TBLSETOR.TBLSETOR_REKAYAT = 8 => AIR TANAH
		// TBLSETOR.TBLSETOR_REKAYAT = 9 => BURUNG WALET
		// TBLSETOR.TBLSETOR_REKAYAT = 10 => BPHTB
		// TBLSETOR.TBLSETOR_REKAYAT = 11 => ???

		
		$data['total'] = $total = Yii::app()->db->createCommand($sqltotal)->queryrow();
		
		$sqlheader = "
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS TBLREKENING_NAMAREKENING,
		TBLSETOR.*
		FROM
		TBLSETOR
		INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
		AND TBLSETOR_STATUSBAYAR = 20
		AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
		AND TBLSETOR.TBLSETOR_REKPAD = 1
		AND TBLSETOR.TBLSETOR_REKPAJAK = 1
		AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."
		ORDER BY
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_REKPENDAPATAN";

		$data['header'] = $header = Yii::app()->db->createCommand($sqlheader)->queryrow();
		$this->renderPartial('cetak',array('data'=>$data));
	}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}