<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 12">
<link rel=File-List href="tpl_files/filelist.xml">
<style id="Book1_5234_Styles">
<!--table
	{mso-displayed-decimal-separator:"\,";
	mso-displayed-thousand-separator:"\.";}
.xl155234
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl635234
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:"Short Date";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl645234
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl655234
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl665234
	{color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:General;
	text-align:left;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;
	padding-left:9px;
	mso-char-indent-count:1;}
.xl675234
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl685234
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:1;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->


<div id="Book1_5234" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=662 style='border-collapse:
 collapse;table-layout:fixed;width:497pt'>
 <col width=136 style='mso-width-source:userset;mso-width-alt:4973;width:102pt'>
 <col width=95 style='mso-width-source:userset;mso-width-alt:3474;width:71pt'>
 <col width=202 style='mso-width-source:userset;mso-width-alt:7387;width:152pt'>
 <col width=106 style='mso-width-source:userset;mso-width-alt:3876;width:80pt'>
 <col width=123 style='mso-width-source:userset;mso-width-alt:4498;width:92pt'>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 width=136 style='height:15.0pt;width:102pt'></td>
  <td class=xl155234 width=95 style='width:71pt'></td>
  <td class=xl155234 width=202 style='width:152pt'></td>
  <td class=xl155234 width=106 style='width:80pt'></td>
  <td class=xl155234 width=123 style='width:92pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan="5" height=20 class=xl155234 style='height:15.0pt'>
  	------------------------------------------------------------------------------------------------------------------------------------------
  </td>
 
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td colspan="2" class=xl155234>Rp. <?php echo $data['jumlah_stok']; ?></td>
  <!-- <td class=xl155234></td> -->
  <td class=xl635234 align=right><?php echo $data['tanggal_bg']; ?></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'><?php echo $data['text_rekening']; ?></td>
  <td colspan=2 class=xl655234>Setoran Pajak <?php echo $data['nama_wp']; ?></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234><?php echo $data['no_bukti']; ?>.</td>
  <td class=xl665234>tgl.<?php echo $data['tanggal_bg']; ?></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td colspan=2 class=xl655234>Bank <?php echo $data['nama_bank']; ?>. Kliringan Melalui</td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234 colspan=2>Bank BPD Senopati</td>
  <td class=xl155234></td>
  <td class=xl155234>Rp. <?php echo $data['jumlah_stok']; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234>Rp. <?php echo $data['jumlah_stok']; ?></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td colspan=2 class=xl645234>WARNINGSIH</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td colspan=2 class=xl675234>196303091987032000</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl685234></td>
  <td class=xl685234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan="5" height=20 class=xl155234 style='height:15.0pt'>
  	------------------------------------------------------------------------------------------------------------------------------------------
  </td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl155234 style='height:15.0pt'></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
  <td class=xl155234></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=136 style='width:102pt'></td>
  <td width=95 style='width:71pt'></td>
  <td width=202 style='width:152pt'></td>
  <td width=106 style='width:80pt'></td>
  <td width=123 style='width:92pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
