<?php

class Lap_obyekjabongController extends Controller
{
	public function actionIndex()
	{
		$this->renderPartial('index');
	}

	public function actionCetak()
	{
		$tahun =substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		
		// if($tahun==''){
		// 	$wherethn = "";
		// }	
		// else{
		// 	$wherethn = "";
		// };

		// if($bulan==''){
		// 	$wherebln = "";
		// }
		// else{
		// 	$wherebln = "";
		// }

		$sql = "
		SELECT
		TBLSETJABONG.TBLSETJABONG_THNSETOR,
		TBLSETJABONG.TBLSETJABONG_BLNSETOR,
		TBLSETJABONG.TBLSETJABONG_TGLSETOR,
		TBLSETJABONG.TBLPENDATAAN_THNPAJAK,
		TBLSETJABONG.TBLPENDATAAN_BLNPAJAK,
		TBLSETJABONG.TBLPENDATAAN_TGLPAJAK,
		TBLSETJABONG.TBLSETJABONG_NOMORSSPD,
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN,
		TBLSETJABONG.TBLSETJABONG_REKPAD,
		TBLSETJABONG.TBLSETJABONG_REKPAJAK,
		TBLSETJABONG.TBLSETJABONG_REKAYAT,
		TBLSETJABONG.TBLSETJABONG_REKJENIS,
		TBLSETJABONG.TBLSETJABONG_REKSUBJENIS,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETJABONG.TBLSETJABONG_RUPIAHSETOR,
		TBLSETJABONG.TBLSETJABONG_JNSBAYAR,
		'Jabong' AS VARNAMAREKENING,
		TBLSETJABONG.*
		FROM
		TBLSETJABONG
		INNER JOIN TBLDAFTAR ON TBLSETJABONG.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		WHERE
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN <> 0
		AND TBLSETJABONG.TBLPENDATAAN_THNPAJAK = ".$tahun."
		AND TBLSETJABONG.TBLPENDATAAN_BLNPAJAK = ".$bulan."
		AND TBLSETJABONG.TBLSETJABONG_THNSETOR = ".$tahun."
		AND TBLSETJABONG.TBLSETJABONG_BLNSETOR = ".$bulan."
		ORDER BY
		TBLSETJABONG.TBLSETJABONG_THNSETOR,
		TBLSETJABONG.TBLSETJABONG_BLNSETOR,
		TBLSETJABONG.TBLSETJABONG_TGLSETOR,
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN";

		$data['rincijabong'] = $rincijabong = Yii::app()->db->createCommand($sql)->queryAll();

		$sqltotal = "SELECT
		SUM (
		CASE
		WHEN TBLSETJABONG.TBLSETJABONG_BLNSETOR = '$bulan' THEN
		TBLSETJABONG.TBLSETJABONG_RUPIAHSETOR
		ELSE
		0
		END
		) AS bulanini,
		SUM (
		CASE
		WHEN TBLSETJABONG.TBLSETJABONG_BLNSETOR < '$bulan' THEN
		TBLSETJABONG.TBLSETJABONG_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanlalu,
		SUM (
		CASE
		WHEN TBLSETJABONG.TBLSETJABONG_BLNSETOR <= '$bulan' THEN
		TBLSETJABONG.TBLSETJABONG_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanini
		FROM
		TBLSETJABONG
		WHERE
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN <> 0
		AND TBLSETJABONG.TBLSETJABONG_THNSETOR = ".$tahun."";

		$data['total'] = $total = Yii::app()->db->createCommand($sqltotal)->queryrow();
		
		$sqlheader = "
		SELECT
		TBLSETJABONG.TBLSETJABONG_THNSETOR,
		TBLSETJABONG.TBLSETJABONG_BLNSETOR,
		TBLSETJABONG.TBLSETJABONG_TGLSETOR,
		TBLSETJABONG.TBLPENDATAAN_THNPAJAK,
		TBLSETJABONG.TBLPENDATAAN_BLNPAJAK,
		TBLSETJABONG.TBLPENDATAAN_TGLPAJAK,
		TBLSETJABONG.TBLSETJABONG_NOMORSSPD,
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN,
		TBLSETJABONG.TBLSETJABONG_REKPAD,
		TBLSETJABONG.TBLSETJABONG_REKPAJAK,
		TBLSETJABONG.TBLSETJABONG_REKAYAT,
		TBLSETJABONG.TBLSETJABONG_REKJENIS,
		TBLSETJABONG.TBLSETJABONG_REKSUBJENIS,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETJABONG.TBLSETJABONG_RUPIAHSETOR,
		TBLSETJABONG.TBLSETJABONG_JNSBAYAR,
		'Jabong' AS VARNAMAREKENING,
		TBLSETJABONG.*
		FROM
		TBLSETJABONG
		INNER JOIN TBLDAFTAR ON TBLSETJABONG.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		WHERE
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN <> 0
		AND TBLSETJABONG.TBLPENDATAAN_THNPAJAK = 14
		AND TBLSETJABONG.TBLPENDATAAN_BLNPAJAK = 1
		AND TBLSETJABONG.TBLSETJABONG_THNSETOR = ".$tahun."
		AND TBLSETJABONG.TBLSETJABONG_BLNSETOR = ".$bulan."
		ORDER BY
		TBLSETJABONG.TBLSETJABONG_THNSETOR,
		TBLSETJABONG.TBLSETJABONG_BLNSETOR,
		TBLSETJABONG.TBLSETJABONG_TGLSETOR,
		TBLSETJABONG.TBLSETJABONG_REKPENDAPATAN";

		$data['header'] = $header = Yii::app()->db->createCommand($sqlheader)->queryrow();

		$this->renderPartial('cetak',array('data'=>$data));
	}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}