<?php

class Setoran_harianController extends Controller
{
	public function actionIndex()
	{
		$data['rek'] = Yii::app()->db->createCommand('
			SELECT
			*
			FROM
			TBLREKENING
			WHERE
			TBLREKENING_REKPAJAK = 1
			AND TBLREKENING_REKPAD = 1
			AND TBLREKENING_REKJENIS = 0
			AND TBLREKENING_REKAYAT <>23
			ORDER BY
			TBLREKENING_REKPENDAPATAN,
			TBLREKENING_REKPAD,
			TBLREKENING_REKPAJAK,
			TBLREKENING_REKAYAT,
			TBLREKENING_REKJENIS
			')->queryAll();
		$data['sub_rek'] = Yii::app()->db->createCommand()
		->select('*')
		->from('TREKENING')
		->where('TREKENING_LEVEL=1')
		->queryAll();
		
		$this->renderPartial('index', array('data'=>$data));
	
	}

	public function actionCetakatashtml()
	{

		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '';
		$rekening = $_REQUEST['rekening'] ? $_REQUEST['rekening'] : '';
		
		$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='4'){
			$data['judul'] = 'PAJAK REKLAME';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

		// if($rekening==''){
		// 	$rekening = "";
		// }
		// else{
		// 	$rekening = "AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."";
		// }

		
		if($tanggal==''){
			$wheretanggal = "";
		}
		else{
			$wheretanggal = "AND TBLSETOR_TGLSETOR = ".$tanggal."";
		}


		$sqlatas = "SELECT * FROM
		(
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."
		AND TBLSETOR.TBLSETOR_REKPAJAK = '1'

		UNION

		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT IN ('6','7')
		AND TBLSETOR.TBLSETOR_REKPAJAK = '4'
		AND TBLSETOR.TBLSETOR_REKJENIS = ".$rekening."
		) TBLSETOR
		ORDER BY
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLSETOR_BLNSETOR ASC";

		// echo "$sqlatas";
		$data['atas'] = $atas =Yii::app()->db->createCommand($sqlatas)->queryAll();

		header('Content-Type: application/excel');
		header("Content-Disposition: attachment;Filename=Cetak-Setoran-Harian.xls");

		$this->renderPartial('cetakatas_bak',array('data'=>$data));

	}

	public function actionCetakatas()
	{

		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '';
		$rekening = $_REQUEST['rekening'] ? $_REQUEST['rekening'] : '';
		
		$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='4'){
			$data['judul'] = 'PAJAK REKLAME';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

		// if($rekening==''){
		// 	$rekening = "";
		// }
		// else{
		// 	$rekening = "AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."";
		// }

		
		if($tanggal==''){
			$wheretanggal = "";
		}
		else{
			$wheretanggal = "AND TBLSETOR_TGLSETOR = ".$tanggal."";
		}


		$sqlatas = "SELECT * FROM
		(
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."
		AND TBLSETOR.TBLSETOR_REKPAJAK = '1'

		UNION

		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT IN ('6','7')
		AND TBLSETOR.TBLSETOR_REKPAJAK = '4'
		AND TBLSETOR.TBLSETOR_REKJENIS = ".$rekening."
		) TBLSETOR
		ORDER BY
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLSETOR_BLNSETOR ASC";

		// echo "$sqlatas";
		$data['atas'] = $atas =Yii::app()->db->createCommand($sqlatas)->queryAll();

		$this->actionCetakWord($data);
        Yii::app()->end();

		$this->renderPartial('cetakatas',array('data'=>$data));

	}

	public function actionCetakWord()
	{
		// error_reporting(0);

		// baca file template, yg dipakai
		// $gettpl = MasterTemplate::model()->find('tblmastertemplate_jenis="WORD" AND tblmastertemplate_kelompok="tpl_bakecamatan" AND tblmastertemplate_isaktif="T"');
		
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '';
		$rekening = $_REQUEST['rekening'] ? $_REQUEST['rekening'] : '';
		
		$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

		// if($rekening==''){
		// 	$rekening = "";
		// }
		// else{
		// 	$rekening = "AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."";
		// }

		
		if($tanggal==''){
			$wheretanggal = "";
		}
		else{
			$wheretanggal = "AND TBLSETOR_TGLSETOR = ".$tanggal."";
		}


		$sqlatas = "SELECT * FROM
		(
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."
		AND TBLSETOR.TBLSETOR_REKPAJAK = '1'

		UNION

		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT IN ('6','7')
		AND TBLSETOR.TBLSETOR_REKPAJAK = '4'
		AND TBLSETOR.TBLSETOR_REKJENIS = ".$rekening."
		) TBLSETOR
		ORDER BY
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLSETOR_BLNSETOR ASC";

		$data['atas'] = $atas =Yii::app()->db->createCommand($sqlatas)->queryAll();

		// echo "$query";
		// $data['list_kartudata'] = Yii::app()->db->createCommand($query)->queryAll();

		$path_tpl =  dirname(Yii::app()->basePath) . DIRECTORY_SEPARATOR . 'file' . DIRECTORY_SEPARATOR . 'tpl_penagihan' . DIRECTORY_SEPARATOR;
		$namatpl = $path_tpl . 'SETORAN_HARIAN.docx';

		Yii::import('ext.DMOpenTBS',true);
		Yii::import('ext.LokalIndonesia');
		DMOpenTBS::init();
		$otbs = new clsTinyButStrong;

		// Useful for debugging purposes. Displays the errors
		$otbs->NoErr = 0;
		$otbs->Plugin(TBS_INSTALL, OPENTBS_PLUGIN); // load the OpenTBS plugin

		$template = $namatpl;
		$otbs->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // load the template

		// Delete a sheet 
		// $otbs->PlugIn(OPENTBS_DELETE_SHEETS, 'Delete me'); 


		// Display a sheet (make it visible) 
		// $otbs->PlugIn(OPENTBS_DISPLAY_SHEETS, 'Display me'); 

		// Change the current sheet 
		// $otbs->PlugIn(OPENTBS_SELECT_SHEET, 2); 

		// A recordset for merging tables

		//INI CODING QUERY CETAK WORD

		$dt = array();
		$rows = array();
		
		$totalpajak = array('totalpajak'=>0); $no=1; foreach ($data['atas'] as $kolom) :

			$dt['no'] = $no++;
			$dt['tglsetor'] = $kolom['TBLSETOR_TGLSETOR'].'-'.$kolom['TBLSETOR_BLNSETOR'].'-20'.$kolom['TBLSETOR_THNSETOR'];
			$dt['namabu'] = $kolom['BNAMA'];
			$dt['npwpd'] = sprintf("%01d",$kolom['TBLDAFTAR_GOLONGAN']).'.'.sprintf("%07d",$kolom['TBLDAFTAR_NOPOK']).'.'.sprintf("%02d",$kolom['TBLKECAMATAN_IDBADANUSAHA']).'.'.sprintf("%02d",$kolom['TBLKELURAHAN_IDBADANUSAHA']);
			$dt['norek'] = sprintf("%01d",$kolom['TBLSETOR_REKPENDAPATAN']).'.'.sprintf("%02d",$kolom['TBLSETOR_REKPAD']).'.'.sprintf("%02d",$kolom['TBLSETOR_REKPAJAK']).'.'.sprintf("%02d",$kolom['TBLSETOR_REKAYAT']).'.'.sprintf("%02d",$kolom['TBLSETOR_REKJENIS']);
			$dt['nmarek'] = $kolom['NMREK'];
			$dt['rpset'] =  LokalIndonesia::ribuan($kolom['TBLSETOR_RUPIAHSETOR']);
			$dt['ke'] = '000';
			$dt['nmsu'] = $kolom['TBLSETOR_JNSBAYAR'];
			$dt['thp'] =  sprintf("%02d",$kolom['TBLPENDATAAN_THNPAJAK']);
			$dt['blp'] =  sprintf("%02d",$kolom['TBLPENDATAAN_BLNPAJAK']);
			$dt['nossp'] = substr($kolom['TBLSETOR_NOMORSSPD'],0,7);

			$totalpajak['totalpajak'] += $kolom['TBLSETOR_RUPIAHSETOR'];

		array_push($rows, $dt);

		endforeach;

		$header = array();


		// $header['totrek'] = $totaljumrek['totaljumrek'];
		// $header['totalpajak'] = LokalIndonesia::ribuan($totalpajak['totalpajak']);
		// $header['datenow'] = date('d') .' '. LokalIndonesia::getbulan(date('m')) .' '. date('Y');

		// $GLOBALS['thnpajak'] = !empty($thnpajak) ? '20'. $thnpajak : '';
		// $GLOBALS['blnpajak'] = !empty($blnpajak) ? $blnpajak : '';
		// $GLOBALS['tglpajak'] = !empty($tglpajak) ? $tglpajak : '';

		// // var_dump($header['hasil']);die;
		$GLOBALS['jnspajak'] = $data['judul'];
		$GLOBALS['tglsetor'] = $tanggal.' '.LokalIndonesia::getBulan($bulan).' '.$tahun;
		$GLOBALS['totalrpset'] = LokalIndonesia::ribuan($totalpajak['totalpajak']);
		$GLOBALS['tglcetak'] =  date('d') .' '. LokalIndonesia::getbulan(date('m')) .' '. date('Y');

		// var_dump($data);
		// echo json_encode($rows);Yii::app()->end();
		// echo json_encode($rows);

		// Merge data in the first sheet 
		// $npwpd = $data['TBLDAFTAR_NOPOK'];
		$namafileDL = "SETORAN-HARIAN-".$data['judul'].".docx";
		$otbs->MergeBlock('row', $rows); 
		$otbs->MergeField('header', $header); 
		// $otbs->MergeField('setoran', $setoran); 
		// $otbs->PlugIn(OPENTBS_DEBUG_XML_CURRENT); // debug the template

		$otbs->Show(OPENTBS_DOWNLOAD, $namafileDL);
		Yii::app()->end();
	}

	public function actionCetakkecilatas()
	{
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '';
		$rekening = $_REQUEST['rekening'] ? $_REQUEST['rekening'] : '';
		
		$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

		if($rekening==''){
			$rekening = "";
		}
		else{
			$rekening = "AND TBLSETOR.TBLSETOR_REKAYAT = ".$rekening."";
		}

		
		if($tanggal==''){
			$wheretanggal = "";
		}
		else{
			$wheretanggal = "AND TBLSETOR_TGLSETOR = ".$tanggal."";
		}

		$sqlkecilatas = "SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		".$rekening."
		AND TBLSETOR.TBLSETOR_REKPAJAK = '1'
		UNION
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
		AND TBLSETOR_THNSETOR = ".$tahun."
		AND TBLSETOR_BLNSETOR = ".$bulan."
		".$wheretanggal."
		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKJENIS = '1'
		AND TBLSETOR.TBLSETOR_REKPAJAK = '4'
		ORDER BY
		TBLSETOR_NOMORSSPD,
		TBLDAFTAR_NOPOK,
		TBLSETOR_REKPENDAPATAN,
		TBLSETOR_REKPAD,
		TBLSETOR_REKPAJAK,
		TBLSETOR_REKAYAT,
		TBLSETOR_REKJENIS,
		TBLKECAMATAN_IDBADANUSAHA,
		TBLKELURAHAN_IDBADANUSAHA";

		$data['kecilatas'] = $kecilats = Yii::app()->db->createCommand($sqlkecilatas)->queryAll();
			// Cetak Kecil Atas
		$this->renderPartial('cetakkecilatas',array('data'=>$data));
	}

	public function actionCetakbawah()
	{
		$rekening = $_REQUEST['rekening'];
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '';

		// Untuk Tanggal Awal
	$tglawl = trim($_REQUEST['tglawl'])!='' ? date('Y-m-d', strtotime($_REQUEST['tglawl']) ) : "";
		$explode = explode('-',$tglawl);
		$tgla =$explode[2];
		$blna =$explode[1];
		$tahuna = substr($explode[0], -2);

		// Untuk Tanggal Akhir
	$tglakhir = trim($_REQUEST['tglakhir'])!='' ? date('Y-m-d', strtotime($_REQUEST['tglakhir']) ) : "";
		$explode = explode('-',$tglakhir);
		$tglk =$explode[2];
		$blnk =$explode[1];
		$tahunk = substr($explode[0], -2);
		// echo $tglakhir;

		$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='4'){
			$data['judul'] = 'PAJAK REKLAME';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

		$sqlbawah = "SELECT * FROM 
		(
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKAYAT
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0

		AND TBLSETOR_BLNSETOR BETWEEN $blna AND $blnk
		AND TBLSETOR_TGLSETOR BETWEEN $tgla AND $tglk 
		AND TBLSETOR_THNSETOR BETWEEN $tahuna AND $tahunk

		/*(
		TO_DATE (
		CONCAT (
		TBLSETOR_BLNSETOR,
		CONCAT (
		'/',
		CONCAT (TBLSETOR_TGLSETOR, CONCAT('/', TBLSETOR_THNSETOR))
		)
		),
		'mm/dd/yy'
		) BETWEEN TO_DATE ('$blna/$tgla/$tahuna', 'mm/dd/yy')
		AND TO_DATE ('$blnk/$tglk/$tahunk', 'mm/dd/yy')
		)*/

		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT = '$rekening'
		AND TBLSETOR.TBLSETOR_REKPAJAK = '1'
		UNION
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKAYAT
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0

		AND TBLSETOR_BLNSETOR BETWEEN $blna AND $blnk
		AND TBLSETOR_TGLSETOR BETWEEN $tgla AND $tglk 
		AND TBLSETOR_THNSETOR BETWEEN $tahuna AND $tahunk

		/*(
		TO_DATE (
		CONCAT (
		TBLSETOR_BLNSETOR,
		CONCAT (
		'/',
		CONCAT (TBLSETOR_TGLSETOR, CONCAT('/', TBLSETOR_THNSETOR))
		)
		),
		'mm/dd/yy'
		) BETWEEN TO_DATE ('$blna/$tgla/$tahuna', 'mm/dd/yy')
		AND TO_DATE ('$blnk/$tglk/$tahunk', 'mm/dd/yy')
		)*/

		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT IN ('6','7')
		AND TBLSETOR.TBLSETOR_REKPAJAK = '4'
		AND TBLSETOR.TBLSETOR_REKJENIS = '$rekening'
		) TBLSETOR
		ORDER BY TBLSETOR.TBLSETOR_TGLSETOR, TBLSETOR.TBLSETOR_NOMORSSPD, TBLSETOR.TBLDAFTAR_NOPOK, TBLSETOR_BLNSETOR ASC";
		// echo $sqlbawah;
		$data['bawah'] = $bawah = Yii::app()->db->createCommand($sqlbawah)->queryAll();

		$this->actionCetakWord($data);
        Yii::app()->end();
	}

	public function actionCetakbawahhtml()
	{
		$rekening = $_REQUEST['rekening'];
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '';
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '';

		// Untuk Tanggal Awal
	$tglawl = trim($_REQUEST['tglawl'])!='' ? date('Y-m-d', strtotime($_REQUEST['tglawl']) ) : "";
		$explode = explode('-',$tglawl);
		$tgla =$explode[2];
		$blna =$explode[1];
		$tahuna = substr($explode[0], -2);

		// Untuk Tanggal Akhir
	$tglakhir = trim($_REQUEST['tglakhir'])!='' ? date('Y-m-d', strtotime($_REQUEST['tglakhir']) ) : "";
		$explode = explode('-',$tglakhir);
		$tglk =$explode[2];
		$blnk =$explode[1];
		$tahunk = substr($explode[0], -2);
		// echo $tglakhir;

		$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='4'){
			$data['judul'] = 'PAJAK REKLAME';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

		$sqlbawah = "SELECT * FROM 
		(
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKAYAT
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0

		AND TBLSETOR_BLNSETOR BETWEEN $blna AND $blnk
		AND TBLSETOR_TGLSETOR BETWEEN $tgla AND $tglk 
		AND TBLSETOR_THNSETOR BETWEEN $tahuna AND $tahunk

		/*(
		TO_DATE (
		CONCAT (
		TBLSETOR_BLNSETOR,
		CONCAT (
		'/',
		CONCAT (TBLSETOR_TGLSETOR, CONCAT('/', TBLSETOR_THNSETOR))
		)
		),
		'mm/dd/yy'
		) BETWEEN TO_DATE ('$blna/$tgla/$tahuna', 'mm/dd/yy')
		AND TO_DATE ('$blnk/$tglk/$tahunk', 'mm/dd/yy')
		)*/

		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT = '$rekening'
		AND TBLSETOR.TBLSETOR_REKPAJAK = '1'
		UNION
		SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLSETOR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLSETOR.TBLSETOR_RUPIAHSETOR,
		TBLSETOR.TBLSETOR_JNSBAYAR,
		(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKAYAT
		) AS NMREK
		FROM
		TBLSETOR
		LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
		AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
		WHERE
		TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0

		AND TBLSETOR_BLNSETOR BETWEEN $blna AND $blnk
		AND TBLSETOR_TGLSETOR BETWEEN $tgla AND $tglk 
		AND TBLSETOR_THNSETOR BETWEEN $tahuna AND $tahunk

		/*(
		TO_DATE (
		CONCAT (
		TBLSETOR_BLNSETOR,
		CONCAT (
		'/',
		CONCAT (TBLSETOR_TGLSETOR, CONCAT('/', TBLSETOR_THNSETOR))
		)
		),
		'mm/dd/yy'
		) BETWEEN TO_DATE ('$blna/$tgla/$tahuna', 'mm/dd/yy')
		AND TO_DATE ('$blnk/$tglk/$tahunk', 'mm/dd/yy')
		)*/

		AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
		AND TBLSETOR.TBLSETOR_REKAYAT IN ('6','7')
		AND TBLSETOR.TBLSETOR_REKPAJAK = '4'
		AND TBLSETOR.TBLSETOR_REKJENIS = '$rekening'
		) TBLSETOR
		ORDER BY TBLSETOR.TBLSETOR_TGLSETOR, TBLSETOR.TBLSETOR_NOMORSSPD, TBLSETOR.TBLDAFTAR_NOPOK, TBLSETOR_BLNSETOR ASC";
		// echo $sqlbawah;
		$data['bawah'] = $bawah = Yii::app()->db->createCommand($sqlbawah)->queryAll();

		header('Content-Type: application/excel');
		header("Content-Disposition: attachment;Filename=Cetak-Setoran-Harian.xls");
		$this->renderPartial('cetakbawah_bak',array('data'=>$data));
}

public function actionCetakkecilbawah()
{
	$rekening = $_REQUEST['rekening'];

		// Untuk Tanggal Awal
	$tglawl = trim($_REQUEST['tglawl'])!='' ? date('Y-m-d', strtotime($_REQUEST['tglawl']) ) : "";
		$explode = explode('-',$tglawl);
		$tgla =$explode[2];
		$blna =$explode[1];
		$tahuna = substr($explode[0], -2);

		// Untuk Tanggal Akhir
	$tglakhir = trim($_REQUEST['tglakhir'])!='' ? date('Y-m-d', strtotime($_REQUEST['tglakhir']) ) : "";
		$explode = explode('-',$tglakhir);
		$tglk =$explode[2];
		$blnk =$explode[1];
		$tahunk = substr($explode[0], -2);

	$AYAT = $_REQUEST['rekening'];

		if ($AYAT=='1'){
			$data['judul'] = 'PAJAK HOTEL';
		}
		elseif($AYAT=='2'){
			$data['judul'] = 'PAJAK RESTORAN';
		}
		elseif($AYAT=='3'){
			$data['judul'] = 'PAJAK HIBURAN';
		}
		elseif($AYAT=='5'){
			$data['judul'] = 'PAJAK PENERANGAN JALAN';
		}
		elseif($AYAT=='7'){
			$data['judul'] = 'PAJAK PARKIR';
		}
		elseif($AYAT=='8'){
			$data['judul'] = 'PAJAK AIR TANAH';
		}
		elseif($AYAT=='9'){
			$data['judul'] = 'PAJAK SARANG BURUNG WALET';
		}
		elseif($AYAT=='11'){
			$data['judul'] = 'PAJAK BPHTB';
		}
		elseif($AYAT=='10'){
			$data['judul'] = 'PAJAK BUMI DAN BANGUNAN (PBB';
		}
		elseif($AYAT=='23'){
			$data['judul'] = 'PAJAK SEWA ASET';
		}

	$sqlkecilbawah = "SELECT
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLPENDATAAN_THNPAJAK,
	TBLSETOR.TBLPENDATAAN_BLNPAJAK,
	TBLSETOR.TBLPENDATAAN_TGLPAJAK,
	TBLSETOR.TBLSETOR_NOMORSSPD,
	TBLSETOR.TBLSETOR_REKPENDAPATAN,
	TBLSETOR.TBLSETOR_REKPAD,
	TBLSETOR.TBLSETOR_REKPAJAK,
	TBLSETOR.TBLSETOR_REKAYAT,
	TBLSETOR.TBLSETOR_REKJENIS,
	TBLSETOR.TBLSETOR_REKSUBJENIS,
	NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
	TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
	TBLDAFTAR.TBLDAFTAR_GOLONGAN,
	TBLSETOR.TBLDAFTAR_NOPOK,
	TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
	TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	TBLSETOR.TBLSETOR_JNSBAYAR,
	(
	SELECT
	TBLREKENING.TBLREKENING_NAMAREKENING
	FROM
	TBLREKENING
	WHERE
	TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
	AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
	AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
	AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
	AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
	) AS NMREK
	FROM
	TBLSETOR
	LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
	AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
	AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
	WHERE
	TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
	AND (
	TO_DATE (
	CONCAT (
	TBLSETOR_BLNSETOR,
	CONCAT (
	'/',
	CONCAT (TBLSETOR_TGLSETOR, CONCAT('/', TBLSETOR_THNSETOR))
	)
	),
	'MM/DD/YY'
	) BETWEEN TO_DATE ('$blna/$tgla/$tahuna', 'MM/DD/YY')
	AND TO_DATE ('$blnk/$tglk/$tahunk', 'MM/DD/YY')
	)
	AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
	AND TBLSETOR.TBLSETOR_REKAYAT = '$rekening'
	AND TBLSETOR.TBLSETOR_REKPAJAK = '1'
	UNION
	SELECT
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLPENDATAAN_THNPAJAK,
	TBLSETOR.TBLPENDATAAN_BLNPAJAK,
	TBLSETOR.TBLPENDATAAN_TGLPAJAK,
	TBLSETOR.TBLSETOR_NOMORSSPD,
	TBLSETOR.TBLSETOR_REKPENDAPATAN,
	TBLSETOR.TBLSETOR_REKPAD,
	TBLSETOR.TBLSETOR_REKPAJAK,
	TBLSETOR.TBLSETOR_REKAYAT,
	TBLSETOR.TBLSETOR_REKJENIS,
	TBLSETOR.TBLSETOR_REKSUBJENIS,
	NVL (TBLDAFTAR_BADANUSAHANAMA, KET) AS BNAMA,
	TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
	TBLDAFTAR.TBLDAFTAR_GOLONGAN,
	TBLSETOR.TBLDAFTAR_NOPOK,
	TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
	TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	TBLSETOR.TBLSETOR_JNSBAYAR,
	(
	SELECT
	TBLREKENING.TBLREKENING_NAMAREKENING
	FROM
	TBLREKENING
	WHERE
	TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
	AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
	AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
	AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
	AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
	) AS NMREK
	FROM
	TBLSETOR
	LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
	AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
	AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
	WHERE
	TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
	AND (
	TO_DATE (
	CONCAT (
	TBLSETOR_BLNSETOR,
	CONCAT (
	'/',
	CONCAT (TBLSETOR_TGLSETOR, CONCAT('/', TBLSETOR_THNSETOR))
	)
	),
	'MM/DD/YY'
	) BETWEEN TO_DATE ('$blna/$tgla/$tahuna', 'MM/DD/YY')
	AND TO_DATE ('$blnk/$tgla/$tahuna', 'MM/DD/YY')
	)
	AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
	AND TBLSETOR.TBLSETOR_REKJENIS = '$rekening'
	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	ORDER BY
	TBLSETOR_NOMORSSPD,
	TBLDAFTAR_NOPOK,
	TBLSETOR_REKPENDAPATAN,
	TBLSETOR_REKPAD,
	TBLSETOR_REKPAJAK,
	TBLSETOR_REKAYAT,
	TBLSETOR_REKJENIS,
	TBLKECAMATAN_IDBADANUSAHA,
	TBLKELURAHAN_IDBADANUSAHA";

	$data['kecilbawah'] = $kecilbawah = Yii::app()->db->createCommand($sqlkecilbawah)->queryAll();

	$this->renderPartial('cetakkecilbawah',array('data'=>$data));
}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
		'inlineFilterName',
		array(
		'class'=>'path.to.FilterClass',
		'propertyName'=>'propertyValue',
		),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
		'action1'=>'path.to.ActionClass',
		'action2'=>array(
		'class'=>'path.to.AnotherActionClass',
		'propertyName'=>'propertyValue',
		),
		);
	}
	*/
}