<?php

class TeguranreklameController extends Controller
{
	public function actionIndex()
	{
		$data['URL_APP'] = Yii::app()->getBaseUrl(true);
		$this->renderPartial('index', array('data'=>$data));
	}

	public function actionCari()
	{
		$id_eksepsi = trim(isset($_REQUEST['id_eksepsi']) ? $_REQUEST['id_eksepsi'] : '', ',');
		$TBLPENDATAAN_THNPAJAK = (int)DMOrcl::getRequest('param', 'TBLPENDATAAN_THNPAJAK');
        $TBLDAFTREKLAME_JNSREKLAME = DMOrcl::getRequest('param', 'TBLDAFTREKLAME_JNSREKLAME');
        $TBLDAFTAR_NOPOK = DMOrcl::getRequest('param', 'TBLDAFTAR_NOPOK');
		$TBLDAFTAR_NOPOK = !empty(DMOrcl::getRequest('TBLDAFTAR_NOPOK')) ? DMOrcl::getRequest('TBLDAFTAR_NOPOK') : '';
		$TBLDAFTAR_JENISPENDAPATAN = !empty(DMOrcl::getRequest('TBLDAFTAR_JENISPENDAPATAN')) ? DMOrcl::getRequest('TBLDAFTAR_JENISPENDAPATAN') : '';
		$TBLDAFTAR_GOLONGAN = !empty(DMOrcl::getRequest('TBLDAFTAR_GOLONGAN')) ? DMOrcl::getRequest('TBLDAFTAR_GOLONGAN') : '';
		$REFBADANUSAHA_ID = !empty(DMOrcl::getRequest('REFBADANUSAHA_ID')) ? DMOrcl::getRequest('REFBADANUSAHA_ID') : '';
		$TBLDAFTAR_ISAKTIF = !empty(DMOrcl::getRequest('TBLDAFTAR_ISAKTIF')) ? DMOrcl::getRequest('TBLDAFTAR_ISAKTIF') : '';
		$TBLDAFTAR_PEMILIKNAMA = !empty(DMOrcl::getRequest('TBLDAFTAR_PEMILIKNAMA')) ? DMOrcl::getRequest('TBLDAFTAR_PEMILIKNAMA') : '';
		$TBLKECAMATAN_IDPEMILIK = !empty(DMOrcl::getRequest('TBLKECAMATAN_IDPEMILIK')) ? DMOrcl::getRequest('TBLKECAMATAN_IDPEMILIK') : '';
		$TBLKELURAHAN_IDPEMILIK = !empty(DMOrcl::getRequest('TBLKELURAHAN_IDPEMILIK')) ? DMOrcl::getRequest('TBLKELURAHAN_IDPEMILIK') : '';
		$TBLDAFTAR_PEMILIKALAMAT = !empty(DMOrcl::getRequest('TBLDAFTAR_PEMILIKALAMAT')) ? DMOrcl::getRequest('TBLDAFTAR_PEMILIKALAMAT') : '';
		$TBLDAFTAR_BADANUSAHANAMA = !empty(DMOrcl::getRequest('TBLDAFTAR_BADANUSAHANAMA')) ? DMOrcl::getRequest('TBLDAFTAR_BADANUSAHANAMA') : '';
		$TBLKECAMATAN_IDBADANUSAHA = !empty(DMOrcl::getRequest('TBLKECAMATAN_IDBADANUSAHA')) ? DMOrcl::getRequest('TBLKECAMATAN_IDBADANUSAHA') : '';
		$TBLKELURAHAN_IDBADANUSAHA = !empty(DMOrcl::getRequest('TBLKELURAHAN_IDBADANUSAHA')) ? DMOrcl::getRequest('TBLKELURAHAN_IDBADANUSAHA') : '';
		$TBLDAFTAR_BADANUSAHAALAMAT = !empty(DMOrcl::getRequest('TBLDAFTAR_BADANUSAHAALAMAT')) ? DMOrcl::getRequest('TBLDAFTAR_BADANUSAHAALAMAT') : '';
	// $JENIS = $data['JENIS'] = !empty(DMOrcl::getRequest('jenis')) ? DMOrcl::getRequest('jenis') : '';

		$select = "
		SELECT
		ROWNUM AS unik_id,
		(
			SELECT
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
			FROM
			TBLDAFTAR
			WHERE
			TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTREKLAME.TBLDAFTAR_NOPOK
			) AS TBLDAFTAR_BADANUSAHANAMA,
(
	SELECT
	TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
	FROM
	TBLDAFTAR
	WHERE
	TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTREKLAME.TBLDAFTAR_NOPOK
	) AS TBLDAFTAR_BADANUSAHAALAMAT,
TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK,
TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK,
TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK,
TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE,
TBLDAFTREKLAME.TBLDAFTAR_GOLONGAN,
TBLDAFTREKLAME.TBLDAFTAR_NOPOK,
TBLDAFTREKLAME.TBLKECAMATAN_ID,
TBLDAFTREKLAME.TBLKELURAHAN_ID,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRI,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRI,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRI,
TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAK,
TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN2,
TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN1,
TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNBATASSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNBATASSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLBATASSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_NOMORSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_URUTSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRISETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRISETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRISETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_REGSETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR,
(
	CASE
	WHEN NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) = 0 THEN
	'Menunggu SKPD Dicetak'
	WHEN NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) = 0 THEN
	'SKPD Belum Dibayar'
	END
	) AS status
ORDER BY
TBLDAFTAR_NOPOK,
TBLDAFTREKLAME_THNSPTPD,
TBLDAFTREKLAME_BLNSPTPD,
TBLDAFTREKLAME_TGLSPTPD,
TBLPENDATAAN_THNPAJAK,
TBLPENDATAAN_BLNPAJAK,
TBLPENDATAAN_TGLPAJAK";

$from = 'TBLDAFTREKLAME';

$otherquery = array(
	'leftjoin_REFBADANUSAHA'=>array('REFBADANUSAHA','TBLDAFTAR.REFBADANUSAHA_IDBADANUSAHA=REFBADANUSAHA.REFBADANUSAHA_ID')
	,'leftjoin_REFBADANUSAHA'=>array('TBLDAFTAR','TBLDAFTAR.REFBADANUSAHA_IDPEMILIK=REFBADANUSAHA.REFBADANUSAHA_ID')
	,'andwhere'=> '
	NVL (TBLDAFTREKLAME_PAJAK, 0) > 0
AND NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) > 0
AND NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) = 0'
	);

$filter = array(
	'EQ__TBLDAFTREKLAME.TBLDAFTAR_NOPOK' => $TBLDAFTAR_NOPOK
	,'EQ__TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME' => $TBLDAFTREKLAME_JNSREKLAME
	,'EQ__TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK' => substr($TBLPENDATAAN_THNPAJAK, -2)
	);

if (!empty($id_eksepsi)) {
	$list_nopok = explode(',', $id_eksepsi);
	$where_nopok = '' ;
	foreach ($list_nopok as $kodene) {
		$pch   = explode('-', $kodene);
		$nopok = (int) (isset($pch[0]) ? $pch[0] : 0);
		$thn   = isset($pch[1]) ? $pch[1] : 0;

		$where_nopok .= " AND NOT (TBLDAFTAR.TBLDAFTAR_NOPOK = $nopok AND TBLPENDATAAN_THNPAJAK = $thn ) ";
	}
        $otherquery['andwhere'] .= $where_nopok;
}

$arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'otherquery'=>$otherquery,'mode'=>'LIST');
$data['cari'] = DBFetch::query($arrayConfig);

$this->renderPartial('cari', array('data'=>$data));

}

public function cetakword()
{

	$data['URL_APP']=Yii::app()->getBaseUrl(true);

	$TBLDAFTAR_NOPOK = !empty(DMOrcl::getRequest('TBLDAFTAR_NOPOK')) ? DMOrcl::getRequest('TBLDAFTAR_NOPOK') : '';
	$TBLDAFTAR_JENISPENDAPATAN = !empty(DMOrcl::getRequest('TBLDAFTAR_JENISPENDAPATAN')) ? DMOrcl::getRequest('TBLDAFTAR_JENISPENDAPATAN') : '';
	$TBLDAFTAR_GOLONGAN = !empty(DMOrcl::getRequest('TBLDAFTAR_GOLONGAN')) ? DMOrcl::getRequest('TBLDAFTAR_GOLONGAN') : '';
	$REFBADANUSAHA_ID = !empty(DMOrcl::getRequest('REFBADANUSAHA_ID')) ? DMOrcl::getRequest('REFBADANUSAHA_ID') : '';
	$TBLDAFTAR_ISAKTIF = !empty(DMOrcl::getRequest('TBLDAFTAR_ISAKTIF')) ? DMOrcl::getRequest('TBLDAFTAR_ISAKTIF') : '';
	$TBLDAFTAR_PEMILIKNAMA = !empty(DMOrcl::getRequest('TBLDAFTAR_PEMILIKNAMA')) ? DMOrcl::getRequest('TBLDAFTAR_PEMILIKNAMA') : '';
	$TBLKECAMATAN_IDPEMILIK = !empty(DMOrcl::getRequest('TBLKECAMATAN_IDPEMILIK')) ? DMOrcl::getRequest('TBLKECAMATAN_IDPEMILIK') : '';
	$TBLKELURAHAN_IDPEMILIK = !empty(DMOrcl::getRequest('TBLKELURAHAN_IDPEMILIK')) ? DMOrcl::getRequest('TBLKELURAHAN_IDPEMILIK') : '';
	$TBLDAFTAR_PEMILIKALAMAT = !empty(DMOrcl::getRequest('TBLDAFTAR_PEMILIKALAMAT')) ? DMOrcl::getRequest('TBLDAFTAR_PEMILIKALAMAT') : '';
	$TBLDAFTAR_BADANUSAHANAMA = !empty(DMOrcl::getRequest('TBLDAFTAR_BADANUSAHANAMA')) ? DMOrcl::getRequest('TBLDAFTAR_BADANUSAHANAMA') : '';
	$TBLKECAMATAN_IDBADANUSAHA = !empty(DMOrcl::getRequest('TBLKECAMATAN_IDBADANUSAHA')) ? DMOrcl::getRequest('TBLKECAMATAN_IDBADANUSAHA') : '';
	$TBLKELURAHAN_IDBADANUSAHA = !empty(DMOrcl::getRequest('TBLKELURAHAN_IDBADANUSAHA')) ? DMOrcl::getRequest('TBLKELURAHAN_IDBADANUSAHA') : '';
	$TBLDAFTAR_BADANUSAHAALAMAT = !empty(DMOrcl::getRequest('TBLDAFTAR_BADANUSAHAALAMAT')) ? DMOrcl::getRequest('TBLDAFTAR_BADANUSAHAALAMAT') : '';
	// $JENIS = $data['JENIS'] = !empty(DMOrcl::getRequest('jenis')) ? DMOrcl::getRequest('jenis') : '';

	$select = "
	SELECT
	ROWNUM AS unik_id,
	(
		SELECT
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
		FROM
		TBLDAFTAR
		WHERE
		TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTREKLAME.TBLDAFTAR_NOPOK
		) AS TBLDAFTAR_BADANUSAHANAMA,
(
	SELECT
	TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
	FROM
	TBLDAFTAR
	WHERE
	TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTREKLAME.TBLDAFTAR_NOPOK
	) AS TBLDAFTAR_BADANUSAHAALAMAT,
TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK,
TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK,
TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK,
TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE,
TBLDAFTREKLAME.TBLDAFTAR_GOLONGAN,
TBLDAFTREKLAME.TBLDAFTAR_NOPOK,
TBLDAFTREKLAME.TBLKECAMATAN_ID,
TBLDAFTREKLAME.TBLKELURAHAN_ID,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRI,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRI,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRI,
TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAK,
TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN2,
TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN1,
TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNBATASSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNBATASSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLBATASSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_NOMORSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_URUTSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLSKPD,
TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRISETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRISETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRISETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_REGSETOR,
TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR,
(
	CASE
	WHEN NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) = 0 THEN
	'Menunggu SKPD Dicetak'
	WHEN NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) = 0 THEN
	'SKPD Belum Dibayar'
	END
	) AS status
ORDER BY
TBLDAFTAR_NOPOK,
TBLDAFTREKLAME_THNSPTPD,
TBLDAFTREKLAME_BLNSPTPD,
TBLDAFTREKLAME_TGLSPTPD,
TBLPENDATAAN_THNPAJAK,
TBLPENDATAAN_BLNPAJAK,
TBLPENDATAAN_TGLPAJAK";

$from = 'TBLDAFTREKLAME';

$otherquery = array(
	'leftjoin_REFBADANUSAHA'=>array('REFBADANUSAHA','TBLDAFTAR.REFBADANUSAHA_IDBADANUSAHA=REFBADANUSAHA.REFBADANUSAHA_ID')
	,'leftjoin_REFBADANUSAHA'=>array('TBLDAFTAR','TBLDAFTAR.REFBADANUSAHA_IDPEMILIK=REFBADANUSAHA.REFBADANUSAHA_ID')
	,'andwhere'=> '
	NVL (TBLDAFTREKLAME_PAJAK, 0) > 0
AND NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) > 0
AND NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) = 0'
	);

$filter = array(
	'EQ__TBLDAFTREKLAME.TBLDAFTAR_NOPOK' => $TBLDAFTAR_NOPOK
	,'EQ__TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME' => $TBLDAFTREKLAME_JNSREKLAME
	,'EQ__TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK' => substr($TBLPENDATAAN_THNPAJAK, -2)
	);

if (!empty($id_eksepsi)) {
	$list_nopok = explode(',', $id_eksepsi);
	$where_nopok = '' ;
	foreach ($list_nopok as $kodene) {
		$pch   = explode('-', $kodene);
		$nopok = (int) (isset($pch[0]) ? $pch[0] : 0);
		$thn   = isset($pch[1]) ? $pch[1] : 0;

		$where_nopok .= " AND NOT (TBLDAFTAR.TBLDAFTAR_NOPOK = $nopok AND TBLPENDATAAN_THNPAJAK = $thn ) ";
	}
           // $otherquery['andwhere'] .= $where_nopok;
}

$arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'otherquery'=>$otherquery,'mode'=>'LIST');
$data['cetak'] = DBFetch::query($arrayConfig);

$this->cetakWordSKNPWPD($data);
Yii::app()->end();

}

// public function actionCetak()
// {
// 	$nomor_surat = $_REQUEST['nomor_surat'];
// 	$pajak_tahun = $_REQUEST['pajak_tahun'];
// 	$jenis_reklame = $_REQUEST['jenis_reklame'];

// 	$sql="
// 	SELECT
// 	ROWNUM AS unik_id,
// 	(
// 		SELECT
// 		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
// 		FROM
// 		TBLDAFTAR
// 		WHERE
// 		TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTREKLAME.TBLDAFTAR_NOPOK
// 		) AS TBLDAFTAR_BADANUSAHANAMA,
// (
// 	SELECT
// 	TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
// 	FROM
// 	TBLDAFTAR
// 	WHERE
// 	TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTREKLAME.TBLDAFTAR_NOPOK
// 	) AS TBLDAFTAR_BADANUSAHAALAMAT,
// TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK,
// TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK,
// TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK,
// TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE,
// TBLDAFTREKLAME.TBLDAFTAR_GOLONGAN,
// TBLDAFTREKLAME.TBLDAFTAR_NOPOK,
// TBLDAFTREKLAME.TBLKECAMATAN_ID,
// TBLDAFTREKLAME.TBLKELURAHAN_ID,
// TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRI,
// TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRI,
// TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRI,
// TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAK,
// TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN2,
// TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN1,
// TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME,
// TBLDAFTREKLAME.TBLDAFTREKLAME_THNBATASSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_BLNBATASSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_TGLBATASSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_NOMORSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_URUTSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_THNSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_BLNSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_TGLSKPD,
// TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRISETOR,
// TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRISETOR,
// TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRISETOR,
// TBLDAFTREKLAME.TBLDAFTREKLAME_REGSETOR,
// TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR,
// (
// 	CASE
// 	WHEN NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) = 0 THEN
// 	'Menunggu SKPD Dicetak'
// 	WHEN NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) = 0 THEN
// 	'SKPD Belum Dibayar'
// 	END
// 	) AS status
// FROM
// TBLDAFTREKLAME
// WHERE
// NVL (TBLDAFTREKLAME_PAJAK, 0) > 0
// AND NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) > 0
// AND NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) = 0
// AND TBLDAFTREKLAME.TBLDAFTAR_NOPOK = '$nopok'
// AND TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME = '$jenis_reklame'
// AND TBLPENDATAAN_THNPAJAK = '$pajak_tahun'
// ORDER BY
// TBLDAFTAR_NOPOK,
// TBLDAFTREKLAME_THNSPTPD,
// TBLDAFTREKLAME_BLNSPTPD,
// TBLDAFTREKLAME_TGLSPTPD,
// TBLPENDATAAN_THNPAJAK,
// TBLPENDATAAN_BLNPAJAK,
// TBLPENDATAAN_TGLPAJAK";

// $data['cetak'] = $cetak = Yii::app()->db->createCommand($sql)->queryAll();
// $this->renderPartial('cetak', array('data'=>$data));
// }

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}