<?php

class Cetaksetoran_wpwrController extends Controller
{

	public function actionIndex()
	{
		$this->renderPartial('index');
	}

	public function actionCari()
	{
		$tanggal = $_REQUEST['tanggal'] ? $_REQUEST['tanggal'] : '0';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '0';
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '0';

		$sql = "SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (
			TBLDAFTAR_BADANUSAHANAMA,
			KET
			) AS TBLDAFTAR_BADANUSAHANAMA,
TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
TBLDAFTAR.TBLDAFTAR_GOLONGAN,
TBLSETOR.TBLDAFTAR_NOPOK,
TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
CASE
WHEN (
	(
		TBLSETOR.TBLSETOR_REKAYAT = 2
		)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 1
	)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 7
	)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 11
	)
)
AND (
	TRIM (TBLSETOR.TBLSETOR_JNSBAYAR) LIKE 'SKPD'
	) THEN
'SPTPD'
ELSE
TBLSETOR.TBLSETOR_JNSBAYAR
END AS TBLSETOR_JNSBAYAR,
TBLSETOR_BUNGAKETETAPAN,
CASE
WHEN TRIM (TBLSETOR.TBLSETOR_JNSBAYAR) LIKE '%SKPD-A%' THEN
NVL (
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	0
	) + NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0)
ELSE
TBLSETOR.TBLSETOR_RUPIAHSETOR
END AS TBLSETOR_RUPIAHSETOR,
(
	SELECT
	TBLREKENING.TBLREKENING_NAMAREKENING
	FROM
	TBLREKENING
	WHERE
	TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
	AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
	AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
	AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
	AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
	) AS TBLREKENING_NAMAREKENING
FROM
TBLSETOR
LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
AND TBLSETOR.TBLSETOR_TGLSETOR = ".$tanggal."
AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
AND TRIM (TBLSETOR_JNSBAYAR) <> 'BNG SK-A'
ORDER BY
TBLSETOR.TBLSETOR_REKPENDAPATAN,
TBLSETOR.TBLSETOR_REKPAD,
TBLSETOR.TBLSETOR_REKPAJAK,
TBLSETOR.TBLSETOR_REKAYAT,
TBLSETOR.TBLSETOR_REKJENIS,
TBLSETOR.TBLDAFTAR_NOPOK";

$data['setoran'] = $setoran = Yii::app()->db->createCommand($sql)->queryAll();

$this->renderPartial('tabel_laporan',array('data'=>$data));

}

public function actionCetak()
{
	$tanggal = $_REQUEST['tanggal'];
	$bulan = $_REQUEST['bulan'];
	$tahun = substr($_REQUEST['tahun'], -2);

	$sql = "SELECT
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLPENDATAAN_THNPAJAK,
	TBLSETOR.TBLPENDATAAN_BLNPAJAK,
	TBLSETOR.TBLPENDATAAN_TGLPAJAK,
	TBLSETOR.TBLSETOR_NOMORSSPD,
	TBLSETOR.TBLSETOR_REKPENDAPATAN,
	TBLSETOR.TBLSETOR_REKPAD,
	TBLSETOR.TBLSETOR_REKPAJAK,
	TBLSETOR.TBLSETOR_REKAYAT,
	TBLSETOR.TBLSETOR_REKJENIS,
	TBLSETOR.TBLSETOR_REKSUBJENIS,
	NVL (
		TBLDAFTAR_BADANUSAHANAMA,
		KET
		) AS TBLDAFTAR_BADANUSAHANAMA,
TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
TBLDAFTAR.TBLDAFTAR_GOLONGAN,
TBLSETOR.TBLDAFTAR_NOPOK,
TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
CASE
WHEN (
	(
		TBLSETOR.TBLSETOR_REKAYAT = 2
		)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 1
	)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 7
	)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 11
	)
)
AND (
	TRIM (TBLSETOR.TBLSETOR_JNSBAYAR) LIKE 'SKPD'
	) THEN
'SPTPD'
ELSE
TBLSETOR.TBLSETOR_JNSBAYAR
END AS TBLSETOR_JNSBAYAR,
TBLSETOR_BUNGAKETETAPAN,
CASE
WHEN TRIM (TBLSETOR.TBLSETOR_JNSBAYAR) LIKE '%SKPD-A%' THEN
NVL (
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	0
	) + NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0)
ELSE
TBLSETOR.TBLSETOR_RUPIAHSETOR
END AS TBLSETOR_RUPIAHSETOR,
(
	SELECT
	TBLREKENING.TBLREKENING_NAMAREKENING
	FROM
	TBLREKENING
	WHERE
	TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
	AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
	AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
	AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
	AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
	) AS TBLREKENING_NAMAREKENING
FROM
TBLSETOR
LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
AND TBLSETOR.TBLSETOR_TGLSETOR = ".$tanggal."
AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
AND TRIM (TBLSETOR_JNSBAYAR) <> 'BNG SK-A'
ORDER BY
TBLSETOR.TBLSETOR_REKPENDAPATAN,
TBLSETOR.TBLSETOR_REKPAD,
TBLSETOR.TBLSETOR_REKPAJAK,
TBLSETOR.TBLSETOR_REKAYAT,
TBLSETOR.TBLSETOR_REKJENIS,
TBLSETOR.TBLDAFTAR_NOPOK";

$data['setoran'] = $setoran =  Yii::app()->db->createCommand($sql)->queryAll();

if (isset($_REQUEST['jenis']) AND ($_REQUEST['jenis'])=='excel') {
	header('Content-Type: application/excel');
	header("Content-Disposition: attachment;Filename=Cetak-Jenis.xls");
}
$this->renderPartial('cetak',array('data'=>$data));
}

public function actionCetakword($data=array())
{
	$path_tpl =  dirname(Yii::app()->basePath) . DIRECTORY_SEPARATOR . 'file' . DIRECTORY_SEPARATOR . 'tpl_pembukuan' . DIRECTORY_SEPARATOR;
	$namatpl = $path_tpl . 'CETAK DAFTAR SETORAN WPWR.docx';
	$namafileDL = "CETAK_DAFTAR_SETORAN_WPWR.docx";

	Yii::import('ext.DMOpenTBS',true);
	Yii::import('ext.LokalIndonesia');
	DMOpenTBS::init();
	$otbs = new clsTinyButStrong;

		// Useful for debugging purposes. Displays the errors
	$otbs->NoErr = 0;
		$otbs->Plugin(TBS_INSTALL, OPENTBS_PLUGIN); // load the OpenTBS plugin

		$template = $namatpl;
		$otbs->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // load the template

		// Delete a sheet 
		// $otbs->PlugIn(OPENTBS_DELETE_SHEETS, 'Delete me'); 


		// Display a sheet (make it visible) 
		// $otbs->PlugIn(OPENTBS_DISPLAY_SHEETS, 'Display me'); 

		// Change the current sheet 
		// $otbs->PlugIn(OPENTBS_SELECT_SHEET, 2); 

		// A recordset for merging tables

		//INI CODING CETAK WORD SETORAN WP WR

		$tahun = substr($_REQUEST['tahun'], -2);
		$tanggal = $_REQUEST['tanggal'];
		$bulan = $_REQUEST['bulan'];
		$TBLDAFTAR_GOLONGAN = !empty(DMOrcl::getRequest('TBLDAFTAR_GOLONGAN')) ? DMOrcl::getRequest('TBLDAFTAR_GOLONGAN') : '';
		$TBLDAFTAR_NOPOK = !empty(DMOrcl::getRequest('TBLDAFTAR_NOPOK')) ? DMOrcl::getRequest('TBLDAFTAR_NOPOK') : '';
		$TBLKECAMATAN_IDBADANUSAHA = !empty(DMOrcl::getRequest('TBLKECAMATAN_IDBADANUSAHA')) ? DMOrcl::getRequest('TBLKECAMATAN_IDBADANUSAHA') : '';
		$TBLKELURAHAN_IDBADANUSAHA = !empty(DMOrcl::getRequest('TBLKELURAHAN_IDBADANUSAHA')) ? DMOrcl::getRequest('TBLKELURAHAN_IDBADANUSAHA') : '';
		$TBLDAFTAR_BADANUSAHANAMA = !empty(DMOrcl::getRequest('TBLDAFTAR_BADANUSAHANAMA')) ? DMOrcl::getRequest('TBLDAFTAR_BADANUSAHANAMA') : '';
		$TBLDAFTAR_BADANUSAHAALAMAT = !empty(DMOrcl::getRequest('TBLDAFTAR_BADANUSAHAALAMAT')) ? DMOrcl::getRequest('TBLDAFTAR_BADANUSAHAALAMAT') : '';
		$TBLSETOR_JNSBAYAR = !empty(DMOrcl::getRequest('TBLSETOR_JNSBAYAR')) ? DMOrcl::getRequest('TBLSETOR_JNSBAYAR') : '';
		$TBLPENDATAAN_THNPAJAK = !empty(DMOrcl::getRequest('TBLPENDATAAN_THNPAJAK')) ? DMOrcl::getRequest('TBLPENDATAAN_THNPAJAK') : '';
		$TBLPENDATAAN_BLNPAJAK = !empty(DMOrcl::getRequest('TBLPENDATAAN_BLNPAJAK')) ? DMOrcl::getRequest('TBLPENDATAAN_BLNPAJAK') : '';
		$TBLSETOR_NOMORSSPD = !empty(DMOrcl::getRequest('TBLSETOR_NOMORSSPD')) ? DMOrcl::getRequest('TBLSETOR_NOMORSSPD') : '';
		$TBLSETOR_BLNSETOR = !empty(DMOrcl::getRequest('TBLSETOR_BLNSETOR')) ? DMOrcl::getRequest('TBLSETOR_BLNSETOR') : '';
		$TBLSETOR_THNSETOR = !empty(DMOrcl::getRequest('TBLSETOR_THNSETOR')) ? DMOrcl::getRequest('TBLSETOR_THNSETOR') : '';
		$TBLSETOR_TGLSETOR = !empty(DMOrcl::getRequest('TBLSETOR_TGLSETOR')) ? DMOrcl::getRequest('TBLSETOR_TGLSETOR') : '';
		$TBLSETOR_REKPENDAPATAN = !empty(DMOrcl::getRequest('TBLSETOR_REKPENDAPATAN')) ? DMOrcl::getRequest('TBLSETOR_REKPENDAPATAN') : '';
		$TBLSETOR_REKPAD = !empty(DMOrcl::getRequest('TBLSETOR_REKPAD')) ? DMOrcl::getRequest('TBLSETOR_REKPAD') : '';
		$TBLSETOR_REKPAJAK = !empty(DMOrcl::getRequest('TBLSETOR_REKPAJAK')) ? DMOrcl::getRequest('TBLSETOR_REKPAJAK') : '';
		$TBLSETOR_REKAYAT = !empty(DMOrcl::getRequest('TBLSETOR_REKAYAT')) ? DMOrcl::getRequest('TBLSETOR_REKAYAT') : '';
		$TBLSETOR_RUPIAHSETOR = !empty(DMOrcl::getRequest('TBLSETOR_RUPIAHSETOR')) ? DMOrcl::getRequest('TBLSETOR_RUPIAHSETOR') : '';
		$TBLREKENING_NAMAREKENING = !empty(DMOrcl::getRequest('TBLREKENING_NAMAREKENING')) ? DMOrcl::getRequest('TBLREKENING_NAMAREKENING') : '';

		$sql = "SELECT
		TBLSETOR.TBLSETOR_THNSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLPENDATAAN_THNPAJAK,
		TBLSETOR.TBLPENDATAAN_BLNPAJAK,
		TBLSETOR.TBLPENDATAAN_TGLPAJAK,
		TBLSETOR.TBLSETOR_NOMORSSPD,
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		TBLSETOR.TBLSETOR_REKSUBJENIS,
		NVL (
			TBLDAFTAR_BADANUSAHANAMA,
			KET
			) AS TBLDAFTAR_BADANUSAHANAMA,
TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
TBLDAFTAR.TBLDAFTAR_GOLONGAN,
TBLSETOR.TBLDAFTAR_NOPOK,
TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
CASE
WHEN (
	(
		TBLSETOR.TBLSETOR_REKAYAT = 2
		)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 1
	)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 7
	)
OR (
	TBLSETOR.TBLSETOR_REKAYAT = 11
	)
)
AND (
	TRIM (TBLSETOR.TBLSETOR_JNSBAYAR) LIKE 'SKPD'
	) THEN
'SPTPD'
ELSE
TBLSETOR.TBLSETOR_JNSBAYAR
END AS TBLSETOR_JNSBAYAR,
TBLSETOR_BUNGAKETETAPAN,
CASE
WHEN TRIM (TBLSETOR.TBLSETOR_JNSBAYAR) LIKE '%SKPD-A%' THEN
NVL (
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	0
	) + NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0)
ELSE
TBLSETOR.TBLSETOR_RUPIAHSETOR
END AS TBLSETOR_RUPIAHSETOR,
(
	SELECT
	TBLREKENING.TBLREKENING_NAMAREKENING
	FROM
	TBLREKENING
	WHERE
	TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
	AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
	AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
	AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
	AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
	) AS TBLREKENING_NAMAREKENING
FROM
TBLSETOR
LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = '$tahun'
AND TBLSETOR.TBLSETOR_BLNSETOR = '$bulan'
AND TBLSETOR.TBLSETOR_TGLSETOR = '$tanggal'
AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20
AND TRIM (TBLSETOR_JNSBAYAR) <> 'BNG SK-A'
ORDER BY
TBLSETOR.TBLSETOR_REKPENDAPATAN,
TBLSETOR.TBLSETOR_REKPAD,
TBLSETOR.TBLSETOR_REKPAJAK,
TBLSETOR.TBLSETOR_REKAYAT,
TBLSETOR.TBLSETOR_REKJENIS,
TBLSETOR.TBLDAFTAR_NOPOK";

$data['setoran'] = $setoran =  Yii::app()->db->createCommand($sql)->queryAll();

$alamat = "SELECT
TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
TBLDAFTAR.TBLDAFTAR_GOLONGAN,
TBLSETOR.TBLDAFTAR_NOPOK,
TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
FROM
TBLSETOR
LEFT JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
AND TBLSETOR.TBLSETOR_GOLONGAN = TBLDAFTAR.TBLDAFTAR_GOLONGAN
AND TBLSETOR.TBLDAFTAR_JNSPENDAPATAN = TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = '$tahun'
AND TBLSETOR.TBLSETOR_BLNSETOR = '$bulan'
AND TBLSETOR.TBLSETOR_TGLSETOR = '$tanggal'
AND TBLSETOR.TBLSETOR_STATUSBAYAR <> 20	
AND TRIM (TBLSETOR_JNSBAYAR) <> 'BNG SK-A'
ORDER BY
TBLSETOR.TBLSETOR_REKPENDAPATAN,
TBLSETOR.TBLSETOR_REKPAD,
TBLSETOR.TBLSETOR_REKPAJAK,
TBLSETOR.TBLSETOR_REKAYAT,
TBLSETOR.TBLSETOR_REKJENIS,
TBLSETOR.TBLDAFTAR_NOPOK";

$data['alamat'] = $alamat =  Yii::app()->db->createCommand($alamat)->queryAll();

// 		$jenis="SELECT
// 		TBLREKENING.TBLREKENING_NAMAREKENING AS NMREK
// 		FROM
// 		TBLREKENING
// 		WHERE
// 		TBLREKENING.TBLREKENING_REKPENDAPATAN = 4
// 		AND TBLREKENING.TBLREKENING_REKPAD = 1
// 		AND TBLREKENING.TBLREKENING_REKPAJAK = 1
// 		AND TBLREKENING.TBLREKENING_REKAYAT = 1 OR  TBLREKENING.TBLREKENING_REKAYAT = 2 
// 		AND TBLREKENING.TBLREKENING_REKJENIS = 0";

// $data['jenis'] = $jenis = Yii::app()->db->createCommand($jenis)->queryrow();
		//$this->renderPartial('cetak',array('data'=>$data));

$utama = array();
$rows = array();

$no = 1;
foreach ($data['setoran'] as $rowWP) :
			//$npwpd = $rowWP['TBLDAFTAR_GOLONGAN'] . '.' . (sprintf('%07d',$rowWP['TBLDAFTAR_NOPOK'])) . '.' . (sprintf('%02d',$rowWP['TBLKECAMATAN_IDBADANUSAHA'])) . '.' . (sprintf('%02d',$rowWP['TBLKELURAHAN_IDBADANUSAHA']));
	$utama['ke'] = '';
$utama['no'] = $no++;


$utama['sspd'] = trim($rowWP['TBLSETOR_NOMORSSPD']);
$utama['rpset'] = trim (LokalIndonesia::ribuan($rowWP['TBLSETOR_RUPIAHSETOR']));
$utama['jbayar'] = trim($rowWP['TBLSETOR_JNSBAYAR']);
$utama['bnama'] = trim($rowWP['TBLDAFTAR_BADANUSAHANAMA']);
			// $utama['balamat'] = trim($rowWP['TBLDAFTAR_BADANUSAHAALAMAT']);
			// $utama['nmrek'] = trim($rowWP['TBLREKENING_NAMAREKENING']);
$utama['thpajak'] = trim ($rowWP['TBLPENDATAAN_THNPAJAK'] . ' ' . ($rowWP['TBLPENDATAAN_BLNPAJAK']));
$utama['koderek'] = trim ($rowWP['TBLSETOR_REKPENDAPATAN'] . '.' . ($rowWP['TBLSETOR_REKPAD']) . '.' . ($rowWP['TBLSETOR_REKPAJAK']) . '.' . ($rowWP['TBLSETOR_REKAYAT']));
$utama['npwpd'] =  trim ($rowWP['TBLDAFTAR_GOLONGAN'] . '.' . ($rowWP['TBLDAFTAR_NOPOK']) . '.' . ($rowWP['TBLKECAMATAN_IDBADANUSAHA']) . '.' . ($rowWP['TBLKELURAHAN_IDBADANUSAHA']));
$utama['tglsetor'] = trim ($rowWP['TBLSETOR_TGLSETOR'] . ' ' . ($rowWP['TBLSETOR_BLNSETOR']) . ' ' . ($rowWP['TBLSETOR_THNSETOR']));

array_push($rows, $utama);	

endforeach;
$header=array();
$header['tgltoday'] = date('d-m-Y');
$header['tanggal'] = '';
$header['nmrek'] = '';
$header['balamat'] = '';

// . $_REQUEST['bulan'] . ($_REQUEST['tahun']
$otbs->MergeBlock('utama', $rows); 
$otbs->MergeField('header', $header);


		// $otbs->PlugIn(OPENTBS_DEBUG_XML_CURRENT); // debug the template

$otbs->Show(OPENTBS_DOWNLOAD, $namafileDL);
Yii::app()->end();
}

}

