<?php

class Cetakrekap_jenisController extends Controller
{
	public function actionIndex()
	{
		$this->renderPartial('index');
	}

	public function actionCari()
	{
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '0';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '0';

		$sql = "SELECT
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_THNSETOR,
		SUM (
			CASE
			WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 1 THEN
			NVL (
				TBLSETOR.TBLSETOR_RUPIAHSETOR,
				0
				)
			ELSE
			0
			END
			) AS pajakhotel,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 1 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 1 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndhotel,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 2 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakrestoran,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 2 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 2 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndrestoranl,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 3 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakhiburan,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 3 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 3 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndhiburan,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 4 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakreklame,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 4 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 4
				AND TBLSETOR.JENSET = 'B' THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndreklame,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 5 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakppj,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 5 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndppj,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 7 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakparkir,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 7 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 7 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndparkir,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 8 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakabt,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 8 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 8
				AND TBLSETOR.JENSET = 'B' THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndabt,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 9 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakwalet,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 9 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndwalet,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 10 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakpbb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 10 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndpbb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 11 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakbphtb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 11 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 11
				AND TBLSETOR.JENSET = 'B' THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndbphtb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 23 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajaksewa,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 23 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndsewa
			FROM
			TBLSETOR
			WHERE
			TBLSETOR.TBLDAFTAR_NOPOK <> 0
			AND TBLSETOR_STATUSBAYAR <> 20
			AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
			AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
			GROUP BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR";

		$data['cari'] = $cari = Yii::app()->db->createCommand($sql)->queryAll();

		$this->renderPartial('tabel_laporan',array('data'=>$data));
	}

	public function actionCetak()
	{
		$tahun = substr($_REQUEST['tahun'], -2);
		$bulan = $_REQUEST['bulan'];

		$sql = "SELECT
		TBLSETOR.TBLSETOR_TGLSETOR,
		TBLSETOR.TBLSETOR_BLNSETOR,
		TBLSETOR.TBLSETOR_THNSETOR,
		SUM (
			CASE
			WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 1 THEN
			NVL (
				TBLSETOR.TBLSETOR_RUPIAHSETOR,
				0
				)
			ELSE
			0
			END
			) AS pajakhotel,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 1 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 1 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndhotel,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 2 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakrestoran,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 2 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 2 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndrestoranl,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 3 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakhiburan,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 3 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 3 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndhiburan,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 4 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakreklame,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 4 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 4
				AND TBLSETOR.JENSET = 'B' THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndreklame,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 5 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakppj,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 5 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndppj,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 7 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakparkir,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 7
				AND TBLSETOR.TBLSETOR_REKJENIS = 7 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 7 THEN
				NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
				ELSE
				0
				END
				) AS bngdndparkir,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 8 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakabt,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 8 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 8
				AND TBLSETOR.JENSET = 'B' THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndabt,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 9 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakwalet,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 9 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndwalet,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 10 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakpbb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 10 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndpbb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 11 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajakbphtb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				AND TBLSETOR.TBLSETOR_REKAYAT = 11 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) + SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 6
				AND TBLSETOR.TBLSETOR_REKJENIS = 11
				AND TBLSETOR.JENSET = 'B' THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndbphtb,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 23 THEN
				NVL (
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					0
					)
			ELSE
			0
			END
			) AS pajaksewa,
			SUM (
				CASE
				WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
				AND TBLSETOR.TBLSETOR_REKPAD = 1
				AND TBLSETOR.TBLSETOR_REKPAJAK = 4
				AND TBLSETOR.TBLSETOR_REKAYAT = 23 THEN
				NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
				ELSE
				0
				END
				) AS bngdndsewa
			FROM
			TBLSETOR
			WHERE
			TBLSETOR.TBLDAFTAR_NOPOK <> 0
			AND TBLSETOR_STATUSBAYAR <> 20
			AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
			AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
			GROUP BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR";

		$data['cetak'] = $cetak = Yii::app()->db->createCommand($sql)->queryAll();
		
		if (isset($_REQUEST['jenis']) AND ($_REQUEST['jenis'])=='excel') {
			header('Content-Type: application/excel');
			header("Content-Disposition: attachment;Filename=Cetak-Jenis.xls");
		}		
		$this->renderPartial('cetak',array('data'=>$data));
	}

	// public function actionCetakwrd($data=array())
	// {
	// 	$path_tpl =  dirname(Yii::app()->basePath) . DIRECTORY_SEPARATOR . 'file' . DIRECTORY_SEPARATOR . 'tpl_pembukuan' . DIRECTORY_SEPARATOR;
	// 	$namatpl = $path_tpl . 'CETAK_REKAP_PENERIMAAN PERJENIS.docx.docx';
	// 	$namafileDL = "CETAK_REKAP_PENERIMAAN PERJENIS.docx";
	
	// 		Yii::import('ext.DMOpenTBS',true);
	// 	Yii::import('ext.LokalIndonesia');
	// 	DMOpenTBS::init();
	// 	$otbs = new clsTinyButStrong;

	// 	// Useful for debugging purposes. Displays the errors
	// 	$otbs->NoErr = 0;
	// 	$otbs->Plugin(TBS_INSTALL, OPENTBS_PLUGIN); // load the OpenTBS plugin

	// 	$template = $namatpl;
	// 	$otbs->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // load the template

	// 	// Delete a sheet 
	// 	// $otbs->PlugIn(OPENTBS_DELETE_SHEETS, 'Delete me'); 


	// 	// Display a sheet (make it visible) 
	// 	// $otbs->PlugIn(OPENTBS_DISPLAY_SHEETS, 'Display me'); 

	// 	// Change the current sheet 
	// 	// $otbs->PlugIn(OPENTBS_SELECT_SHEET, 2); 

	// 	// A recordset for merging tables

	// 	//INI CODING CETAK REKAP PENERIMAAN PER JENIS

	// 	$tahun = substr($_REQUEST['tahun'], -2);
	// 	$bulan = $_REQUEST['bulan'];
	// 	$TBLSETOR_BLNSETOR = !empty(DMOrcl::getRequest('TBLSETOR_BLNSETOR')) ? DMOrcl::getRequest('TBLSETOR_BLNSETOR') : '';
	// 	$TBLSETOR_THNSETOR = !empty(DMOrcl::getRequest('TBLSETOR_THNSETOR')) ? DMOrcl::getRequest('TBLSETOR_THNSETOR') : '';
	// 	$TBLSETOR_TGLSETOR = !empty(DMOrcl::getRequest('TBLSETOR_TGLSETOR')) ? DMOrcl::getRequest('TBLSETOR_TGLSETOR') : '';

	// 	$sql = "SELECT
	// 	TBLSETOR.TBLSETOR_TGLSETOR,
	// 	TBLSETOR.TBLSETOR_BLNSETOR,
	// 	TBLSETOR.TBLSETOR_THNSETOR,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 1 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakhotel,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 1 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 1
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndhotel,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 2 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakrestoran,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 2 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 2
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndrestoranl,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 3 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakhiburan,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 3 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 3
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndhiburan,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 4 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakreklame,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 4 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 4
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndreklame,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 5 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakppj,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 5 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndppj,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 7 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakparkir,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 7 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 7
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndparkir,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 8 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakabt,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 8 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 8
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndabt,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 9 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakwalet,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 9 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndwalet,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 10 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakpbb,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 10 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndpbb,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 11 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajakbphtb,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 11 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) + SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 6
	// 	AND TBLSETOR.TBLSETOR_REKJENIS = 11
	// 	AND TBLSETOR.JENSET = 'B' THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndbphtb,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 23 THEN
	// 	NVL (TBLSETOR.TBLSETOR_RUPIAHSETOR, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS pajaksewa,
	// 	SUM (
	// 	CASE
	// 	WHEN TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	// 	AND TBLSETOR.TBLSETOR_REKPAD = 1
	// 	AND TBLSETOR.TBLSETOR_REKPAJAK = 4
	// 	AND TBLSETOR.TBLSETOR_REKAYAT = 23 THEN
	// 	NVL (TBLSETOR.TBLSETOR_BUNGAKETETAPAN, 0) + NVL (TBLSETOR.TBLSETOR_DENDAKETETAPAN, 0)
	// 	ELSE
	// 	0
	// 	END
	// 	) AS bngdndsewa
	// 	FROM
	// 	TBLSETOR
	// 	WHERE
	// 	TBLSETOR.TBLDAFTAR_NOPOK <> 0
	// 	AND TBLSETOR_STATUSBAYAR <> 20
	// 	AND TBLSETOR.TBLSETOR_THNSETOR = ".$tahun."
	// 	AND TBLSETOR.TBLSETOR_BLNSETOR = ".$bulan."
	// 	GROUP BY
	// 	TBLSETOR.TBLSETOR_THNSETOR,
	// 	TBLSETOR.TBLSETOR_BLNSETOR,
	// 	TBLSETOR.TBLSETOR_TGLSETOR
	// 	ORDER BY
	// 	TBLSETOR.TBLSETOR_THNSETOR,
	// 	TBLSETOR.TBLSETOR_BLNSETOR,
	// 	TBLSETOR.TBLSETOR_TGLSETOR";

	// 	$data['cetak'] = $cetak = Yii::app()->db->createCommand($sql)->queryAll();

	// 	$utama = array();
	// 	$rows = array();

	// 	foreach ($data['cetak'] as $rowWP) :
	// 		$tanggalsetor = $rowWP['TBLSETOR_TGLSETOR'] . ' ' . (sprintf('MMMM',$rowWP['TBLSETOR_BLNSETOR'])) . '' . (sprintf('YYY',$rowWP['TBLSETOR_THNSETOR']));

	// 		$utama['tgl_today'] = date('d-m-Y');
	// 		$utama['PAJAKHOTEL'] = trim($rowWP['PAJAKHOTEL']);
	// 		$utama['BNGDNDHOTEL'] = trim($rowWP['BNGDNDHOTEL']);
	// 		$utama['PAJAKRESTORAN'] = trim($rowWP['PAJAKRESTORAN']);
	// 		$utama['BNGDNDRESTORANL'] = trim($rowWP['BNGDNDRESTORANL']);
	// 		$utama['PAJAKHIBURAN'] = trim($rowWP['PAJAKHIBURAN']);
	// 		$utama['BNGDNDHIBURAN'] = trim($rowWP['BNGDNDHIBURAN']);
	// 		$utama['PAJAKREKLAME'] = trim($rowWP['PAJAKREKLAME']);
	// 		$utama['BNGDNDREKLAME'] = trim($rowWP['BNGDNDREKLAME']);
	// 		$utama['PAJAKPPJ'] = trim($rowWP['PAJAKPPJ']);
	// 		$utama['BNGDNDPPJ'] = trim($rowWP['BNGDNDPPJ']);
	// 		$utama['PAJAKPARKIR'] = trim($rowWP['PAJAKPARKIR']);
	// 		$utama['BNGDNDPARKIR'] = trim($rowWP['BNGDNDPARKIR']);
	// 		$utama['PAJAKABT'] = trim($rowWP['PAJAKABT']);
	// 		$utama['BNGDNDABT'] = trim($rowWP['BNGDNDABT']);
	// 		$utama['PAJAKWALET'] = trim($rowWP['PAJAKWALET']);
	// 		$utama['BNGDNDWALET'] = trim($rowWP['BNGDNDWALET']);
	// 		$utama['PAJAKPBB'] = trim($rowWP['PAJAKPBB']);
	// 		$utama['BNGDNDPBB'] = trim($rowWP['BNGDNDPBB']);
	// 		$utama['PAJAKBPHTB'] = trim($rowWP['PAJAKBPHTB']);
	// 		$utama['BNGDNDBPHTB'] = trim($rowWP['BNGDNDBPHTB']);
	// 		$utama['PAJAKSEWA'] = trim($rowWP['PAJAKSEWA']);
	// 		$utama['BNGDNDSEWA'] = trim($rowWP['BNGDNDSEWA']);
			

	// 	array_push($rows, $utama):

	// 	endforeach;

	// 	$otbs->MergeBlock('utama', $rows); 
	// 	// $otbs->PlugIn(OPENTBS_DEBUG_XML_CURRENT); // debug the template

	// 	$otbs->Show(OPENTBS_DOWNLOAD, $namafileDL);
	// 	Yii::app()->end();

	// }
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}