<?php

class Cetakbuku_jenis_90Controller extends Controller
{
	var $MODULE_URL = 'pembukuandanpelaporan/cetakbuku_jenis_90';

	public function actionIndex()
	{
		$data['rek'] = Yii::app()->db->createCommand('
			SELECT
			*
			FROM
			TBLREKENING_90 TBLREKENING
			WHERE
			TBLREKENING_REKPAJAK = 1
			AND TBLREKENING_REKPAD = 1
			AND TBLREKENING_REKJENIS = 0
			AND TBLREKENING_REKPENDAPATAN_90 IS NOT NULL
			ORDER BY
			TBLREKENING_REKPENDAPATAN,
			TBLREKENING_REKPAD,
			TBLREKENING_REKPAJAK,
			TBLREKENING_REKAYAT,
			TBLREKENING_REKJENIS
			')->queryAll();
		$data['sub_rek'] = Yii::app()->db->createCommand()
		->select('*')
		->from('TREKENING')
		->where('TREKENING_LEVEL=1')
		->queryAll();
		$this->renderPartial('index', array('data'=>$data));
	}

	public function actionCari()
	{
		$rek = $_REQUEST['rek'] ? $_REQUEST['rek'] : '0' ;
		$masapajak_tahun = substr($_REQUEST['masapajak_tahun'], -2) ? substr($_REQUEST['masapajak_tahun'], -2) : '0';
		$masapajak_bulan = $_REQUEST['masapajak_bulan'] ? $_REQUEST['masapajak_bulan'] : '0';

			$sql ="SELECT
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLPENDATAAN_THNPAJAK,
	TBLSETOR.TBLPENDATAAN_BLNPAJAK,
	TBLSETOR.TBLPENDATAAN_TGLPAJAK,
	TBLSETOR.TBLSETOR_NOMORSSPD,
	TBLSETOR.TBLSETOR_REKPENDAPATAN,
	TBLSETOR.TBLSETOR_REKPAD,
	TBLSETOR.TBLSETOR_REKPAJAK,
	TBLSETOR.TBLSETOR_REKAYAT,
	TBLSETOR.TBLSETOR_REKJENIS,
	TBLSETOR.TBLSETOR_REKSUBJENIS,
	TBLDAFTAR.TBLDAFTAR_GOLONGAN,
	TBLDAFTAR.TBLDAFTAR_NOPOK,
	TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
	TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	TBLSETOR.TBLSETOR_JNSBAYAR,
	(
		SELECT
		TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK,
TBLSETOR.*
FROM
TBLSETOR 
JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
AND TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan'
AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
AND TBLSETOR.TBLSETOR_REKPAD = 1
AND TBLSETOR.TBLSETOR_REKPAJAK = 1
AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'
ORDER BY
TBLSETOR.TBLSETOR_THNSETOR,
TBLSETOR.TBLSETOR_BLNSETOR,
TBLSETOR.TBLSETOR_TGLSETOR,
TBLSETOR.TBLSETOR_REKPENDAPATAN";

$data['cari'] = $cetak = Yii::app()->db->createCommand($sql)->queryAll();

$sqlheader = "SELECT
TBLSETOR.TBLSETOR_THNSETOR,
TBLSETOR.TBLSETOR_BLNSETOR,
TBLSETOR.TBLSETOR_TGLSETOR,
TBLSETOR.TBLPENDATAAN_THNPAJAK,
TBLSETOR.TBLPENDATAAN_BLNPAJAK,
TBLSETOR.TBLPENDATAAN_TGLPAJAK,
TBLSETOR.TBLSETOR_NOMORSSPD,
TBLSETOR.TBLSETOR_REKPENDAPATAN,
TBLSETOR.TBLSETOR_REKPAD,
TBLSETOR.TBLSETOR_REKPAJAK,
TBLSETOR.TBLSETOR_REKAYAT,
TBLSETOR.TBLSETOR_REKJENIS,
TBLSETOR.TBLSETOR_REKSUBJENIS,
TBLDAFTAR.TBLDAFTAR_GOLONGAN,
TBLDAFTAR.TBLDAFTAR_NOPOK,
TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
TBLSETOR.TBLSETOR_RUPIAHSETOR,
TBLSETOR.TBLSETOR_JNSBAYAR,
(
	SELECT
	TBLREKENING.TBLREKENING_NAMAREKENING
	FROM
	TBLREKENING
	WHERE
	TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
	AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
	AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
	AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
	AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
	) AS NMREK,
TBLSETOR.*
FROM
TBLSETOR 
JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
AND TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan'
AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
AND TBLSETOR.TBLSETOR_REKPAD = 1
AND TBLSETOR.TBLSETOR_REKPAJAK = 1
AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'
ORDER BY
TBLSETOR.TBLSETOR_THNSETOR,
TBLSETOR.TBLSETOR_BLNSETOR,
TBLSETOR.TBLSETOR_TGLSETOR,
TBLSETOR.TBLSETOR_REKPENDAPATAN";

$data['header'] = $header = Yii::app()->db->createCommand($sqlheader)->queryrow();

$sqltotal = "SELECT
SUM (
	CASE
	WHEN TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan' THEN
	TBLSETOR.TBLSETOR_RUPIAHSETOR
	ELSE
	0
	END
	) AS bulanini,
SUM (
	CASE
	WHEN TBLSETOR.TBLSETOR_BLNSETOR < '$masapajak_bulan' THEN
	TBLSETOR.TBLSETOR_RUPIAHSETOR
	ELSE
	0
	END
	) AS sd_bulanlalu,
SUM (
	CASE
	WHEN TBLSETOR.TBLSETOR_BLNSETOR <= '$masapajak_bulan' THEN
	TBLSETOR.TBLSETOR_RUPIAHSETOR
	ELSE
	0
	END
	) AS sd_bulanini
FROM
TBLSETOR
WHERE
TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
AND TBLSETOR.TBLSETOR_REKPAD = 1
AND TBLSETOR.TBLSETOR_REKPAJAK = 1
AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'";

$data['total'] = $total = Yii::app()->db->createCommand($sqltotal)->queryrow();

$this->renderPartial('tabel_laporan',array('data'=>$data));
}

public function actionCetak()
{
	$rek = $_REQUEST['rek'];
	$masapajak_tahun = substr($_REQUEST['masapajak_tahun'], -2);
	$masapajak_bulan = $_REQUEST['masapajak_bulan'];

	$sql ="SELECT
	TBLSETOR.*,
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLPENDATAAN_THNPAJAK,
	TBLSETOR.TBLPENDATAAN_BLNPAJAK,
	TBLSETOR.TBLPENDATAAN_TGLPAJAK,
	TBLSETOR.TBLSETOR_NOMORSSPD,

	TBLREKENING.TBLREKENING_REKPENDAPATAN_90 AS TBLSETOR_REKPENDAPATAN,
	TBLREKENING.TBLREKENING_REKPAD_90 AS TBLSETOR_REKPAD,
	TBLREKENING.TBLREKENING_REKPAJAK_90 AS TBLSETOR_REKPAJAK,
	TBLREKENING.TBLREKENING_REKAYAT_90 TBLSETOR_REKAYAT,
	TBLREKENING.TBLREKENING_REKJENIS_90 AS TBLSETOR_REKJENIS,
	TBLREKENING.TBLREKENING_REKSUBJENIS_90 AS TBLSETOR_REKSUBJENIS,

	TBLDAFTAR.TBLDAFTAR_GOLONGAN,
	TBLDAFTAR.TBLDAFTAR_NOPOK,
	TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
	TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	TBLSETOR.TBLSETOR_JNSBAYAR,
	TBLREKENING_NAMAREKENING_90 AS NMREK
	FROM
	TBLSETOR 
	JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK

	LEFT JOIN TBLREKENING_90 TBLREKENING ON TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS

	WHERE
	TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
	AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
	AND TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan'
	AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
	AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	AND TBLSETOR.TBLSETOR_REKPAD = 1
	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'
	ORDER BY
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLSETOR_REKPENDAPATAN
	";

	$data['cetak'] = $cetak = Yii::app()->db->createCommand($sql)->queryAll();

	$sqlheader = $sql;
	// echo $sqlheader;Yii::app()->end();

	$data['header'] = $header = Yii::app()->db->createCommand($sqlheader)->queryrow();

	$sqltotal = "SELECT
	SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS bulanini,
	SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR < '$masapajak_bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanlalu,
	SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR <= '$masapajak_bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanini
	FROM
	TBLSETOR
	WHERE
	TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
	AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
	AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
	AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	AND TBLSETOR.TBLSETOR_REKPAD = 1
	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'";

	$data['total'] = $total = Yii::app()->db->createCommand($sqltotal)->queryrow();

	if (isset($_REQUEST['jenis']) AND ($_REQUEST['jenis'])=='excel') {
		header('Content-Type: application/excel');
		header("Content-Disposition: attachment;Filename=Cetak-Jenis.xls");
	}
	elseif (isset($_REQUEST['jenis']) AND ($_REQUEST['jenis'])=='word') {
		header('Content-Type: application/word');
		header("Content-Disposition: attachment;Filename=Cetak-Jenis.doc");
	}


		// 	switch ($type) {
		// 	case 'word':
		// 	header('Content-Type: application/vnd.ms-word');
		// 	header('Content-Disposition: attachment; filename=laporan_penyelenggaraan.doc');
		// 	break;
		// 	case 'excel':
		// 	header('Content-Type: application/vnd.ms-excel');
		// 	header('Content-Disposition: attachment; filename=laporan_penyelenggaraan.xls');
		// 	break;

		// 	default:
		// 		# code...
		// 	break;
		// }
	$this->renderPartial('cetak_laporan',array('data'=>$data));
}

public function actionCetakword($data=array())
{

	$path_tpl =  dirname(Yii::app()->basePath) . DIRECTORY_SEPARATOR . 'file' . DIRECTORY_SEPARATOR . 'tpl_pembukuan' . DIRECTORY_SEPARATOR;
	$namatpl = $path_tpl . 'CETAK_BUKU_JENIS_90.docx';
	$namafileDL = "CETAK_BUKU_JENIS.docx";

	Yii::import('ext.DMOpenTBS',true);
	Yii::import('ext.LokalIndonesia');
	DMOpenTBS::init();
	$otbs = new clsTinyButStrong;

		// Useful for debugging purposes. Displays the errors
	$otbs->NoErr = 0;
	$otbs->Plugin(TBS_INSTALL, OPENTBS_PLUGIN); // load the OpenTBS plugin

	$template = $namatpl;
	$otbs->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // load the template

	// Delete a sheet 
	// $otbs->PlugIn(OPENTBS_DELETE_SHEETS, 'Delete me'); 


	// Display a sheet (make it visible) 
	// $otbs->PlugIn(OPENTBS_DISPLAY_SHEETS, 'Display me'); 

	// Change the current sheet 
	// $otbs->PlugIn(OPENTBS_SELECT_SHEET, 2); 

	// A recordset for merging tables

	//INI CODING CETAK WORD BUKU JENIS

	$rek = $_REQUEST['rek'];
	$masapajak_tahun = substr($_REQUEST['masapajak_tahun'], -2);
	$masapajak_bulan = $_REQUEST['masapajak_bulan'];
	$TBLREKENING_NAMAREKENING = !empty(DMOrcl::getRequest('TBLREKENING_NAMAREKENING')) ? DMOrcl::getRequest('TBLREKENING_NAMAREKENING') : '';
	$TBLSETOR_BLNSETOR = !empty(DMOrcl::getRequest('TBLSETOR_BLNSETOR')) ? DMOrcl::getRequest('TBLSETOR_BLNSETOR') : '';
	$TBLSETOR_THNSETOR = !empty(DMOrcl::getRequest('TBLSETOR_THNSETOR')) ? DMOrcl::getRequest('TBLSETOR_THNSETOR') : '';
	$TBLSETOR_TGLSETOR = !empty(DMOrcl::getRequest('TBLSETOR_TGLSETOR')) ? DMOrcl::getRequest('TBLSETOR_TGLSETOR') : '';
	$TBLSETOR_RUPIAHSETOR = !empty(DMOrcl::getRequest('TBLSETOR_RUPIAHSETOR')) ? DMOrcl::getRequest('TBLSETOR_RUPIAHSETOR') : '';
	$TBLSETOR_NOMORSSPD = !empty(DMOrcl::getRequest('TBLSETOR_NOMORSSPD')) ? DMOrcl::getRequest('TBLSETOR_NOMORSSPD') : '';
	$TBLSETOR_REKPENDAPATAN = !empty(DMOrcl::getRequest('TBLSETOR_REKPENDAPATAN')) ? DMOrcl::getRequest('TBLSETOR_REKPENDAPATAN') : '';
	$TBLSETOR_REKPAD = !empty(DMOrcl::getRequest('TBLSETOR_REKPAD')) ? DMOrcl::getRequest('TBLSETOR_REKPAD') : '';
	$TBLSETOR_REKPAJAK = !empty(DMOrcl::getRequest('TBLSETOR_REKPAJAK')) ? DMOrcl::getRequest('TBLSETOR_REKPAJAK') : '';
	$TBLSETOR_REKAYAT = !empty(DMOrcl::getRequest('TBLSETOR_REKAYAT')) ? DMOrcl::getRequest('TBLSETOR_REKAYAT') : '';
	$TBLPENDATAAN_THNPAJAK = !empty(DMOrcl::getRequest('TBLPENDATAAN_THNPAJAK')) ? DMOrcl::getRequest('TBLPENDATAAN_THNPAJAK') : '';
	$TBLPENDATAAN_BLNPAJAK = !empty(DMOrcl::getRequest('TBLPENDATAAN_BLNPAJAK')) ? DMOrcl::getRequest('TBLPENDATAAN_BLNPAJAK') : '';
	$BULANINI = !empty(DMOrcl::getRequest('BULANINI')) ? DMOrcl::getRequest('BULANINI') : '';
	$SD_BULANINI = !empty(DMOrcl::getRequest('SD_BULANINI')) ? DMOrcl::getRequest('SD_BULANINI') : '';
	$SD_BULANLALU = !empty(DMOrcl::getRequest('SD_BULANLALU')) ? DMOrcl::getRequest('SD_BULANLALU') : '';

	$cetak ="SELECT
	TBLSETOR.*,
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLPENDATAAN_THNPAJAK,
	TBLSETOR.TBLPENDATAAN_BLNPAJAK,
	TBLSETOR.TBLPENDATAAN_TGLPAJAK,
	TBLSETOR.TBLSETOR_NOMORSSPD,

	TBLREKENING.TBLREKENING_REKPENDAPATAN_90 AS TBLSETOR_REKPENDAPATAN,
	TBLREKENING.TBLREKENING_REKPAD_90 AS TBLSETOR_REKPAD,
	TBLREKENING.TBLREKENING_REKPAJAK_90 AS TBLSETOR_REKPAJAK,
	TBLREKENING.TBLREKENING_REKAYAT_90 TBLSETOR_REKAYAT,
	TBLREKENING.TBLREKENING_REKJENIS_90 AS TBLSETOR_REKJENIS,
	TBLREKENING.TBLREKENING_REKSUBJENIS_90 AS TBLSETOR_REKSUBJENIS,

	TBLDAFTAR.TBLDAFTAR_GOLONGAN,
	TBLDAFTAR.TBLDAFTAR_NOPOK,
	TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
	TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
	TBLSETOR.TBLSETOR_RUPIAHSETOR,
	TBLSETOR.TBLSETOR_JNSBAYAR,
	TBLREKENING_NAMAREKENING_90 AS NMREK
	FROM
	TBLSETOR 
	JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK

	LEFT JOIN TBLREKENING_90 TBLREKENING ON TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS

	WHERE
	TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
	AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
	AND TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan'
	AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
	AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	AND TBLSETOR.TBLSETOR_REKPAD = 1
	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'
	ORDER BY
	TBLSETOR.TBLSETOR_THNSETOR,
	TBLSETOR.TBLSETOR_BLNSETOR,
	TBLSETOR.TBLSETOR_TGLSETOR,
	TBLSETOR.TBLSETOR_REKPENDAPATAN
	";

	$data['cetak'] = $cetak = Yii::app()->db->createCommand($cetak)->queryAll();

	$total = "SELECT
	SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR = '$masapajak_bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS bulanini,
	SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR < '$masapajak_bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanlalu,
	SUM (
		CASE
		WHEN TBLSETOR.TBLSETOR_BLNSETOR <= '$masapajak_bulan' THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS sd_bulanini
	FROM
	TBLSETOR
	WHERE
	TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
	AND TBLSETOR.TBLSETOR_THNSETOR = '$masapajak_tahun'
	AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
	AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
	AND TBLSETOR.TBLSETOR_REKPAD = 1
	AND TBLSETOR.TBLSETOR_REKPAJAK = 1
	AND TBLSETOR.TBLSETOR_REKAYAT = '$rek'";

	// echo $total;Yii::app()->end();

	$data['total'] = $total = Yii::app()->db->createCommand($total)->queryrow();

	$jenis="SELECT
			TBLREKENING.TBLREKENING_REKAYAT_90 AS AYAT,
			TBLREKENING.TBLREKENING_NAMAREKENING_90 AS NMREK
			FROM
			TBLREKENING_90 TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = 4
			AND TBLREKENING.TBLREKENING_REKPAD = 1
			AND TBLREKENING.TBLREKENING_REKPAJAK = 1
			AND TBLREKENING.TBLREKENING_REKAYAT = '$rek'
			AND TBLREKENING.TBLREKENING_REKJENIS = 0";

	$data['jenis'] = $jenis = Yii::app()->db->createCommand($jenis)->queryrow();
	$utama = array();
	$rows = array();
	// $jumlah = array();
	// $rows = array();

	$no = 1;

	$GLOBALS['date'] = date('d-m-Y');  
	$GLOBALS['datenow'] =  date('d-m-Y');
	foreach ($data['cetak'] as $rowWP) :

		//$koderekening = $rowWP['TBLSETOR_REKPENDAPATAN'] . '.' . (sprintf('%07d',$rowWP['TBLSETOR_REKPAD'])) . '.' . (sprintf('%02d',$rowWP['TBLSETOR_REKPAJAK'])) . '.' . (sprintf('%02d',$rowWP['TBLSETOR_REKAYAT']));
		//$tanggalsetor = $rowWP['TBLSETOR_TGLSETOR'] . ' ' . (sprintf('MMMM',$rowWP['TBLSETOR_BLNSETOR'])) . '' . (sprintf('YYY',$rowWP['TBLSETOR_THNSETOR']));

		$utama['ke'] = '';
		$utama['no'] = $no++;
		
		$utama['sspd'] = trim ($rowWP['TBLSETOR_NOMORSSPD']);
		$utama['rpset'] = trim (LokalIndonesia::ribuan($rowWP['TBLSETOR_RUPIAHSETOR']));
		$utama['thnpjk'] = trim ($rowWP['TBLPENDATAAN_THNPAJAK']);
		$utama['blnpjk'] = trim ($rowWP['TBLPENDATAAN_BLNPAJAK']);
		$utama['tanggalsetor'] = trim ($rowWP['TBLSETOR_TGLSETOR'] . ' ' . ($rowWP['TBLSETOR_BLNSETOR']) . ' ' . ($rowWP['TBLSETOR_THNSETOR']));

		

	array_push($rows, $utama);

	endforeach;
	$header=array();
	$header['masapajak_bulan'] = LokalIndonesia::getbulan($_REQUEST ['masapajak_bulan']);
	$header['masapajak_tahun'] = $_REQUEST ['masapajak_tahun'];
	$header['koderekening'] = '4.1.1.0.'. $data['jenis']['AYAT'];
	$header['namarek'] = trim($data['jenis']['NMREK']);
	$header['bulanini'] = LokalIndonesia::ribuan($data['total']['BULANINI']);
	$header['sdbulanini'] = LokalIndonesia::ribuan($data['total']['SD_BULANINI']);
	$header['sdbulanlalu'] = LokalIndonesia::ribuan($data['total']['SD_BULANLALU']);
	$header['tgltoday'] = date('d-m-Y');

	$sqlpengguna = "SELECT * FROM TBLPEJABAT WHERE REFJABATAN_ID=1";
	$pjbt_pengguna = Yii::app()->db->createCommand($sqlpengguna)->queryRow();
	$header['pengguna_pejabat_uraian'] = $pjbt_pengguna ? $pjbt_pengguna['TBLPEJABAT_URAIAN'] : '';
	$header['pengguna_pejabat_nama'] = $pjbt_pengguna ? $pjbt_pengguna['TBLPEJABAT_NAMA'] : '';
	$header['pengguna_pejabat_nip'] = $pjbt_pengguna ? $pjbt_pengguna['TBLPEJABAT_NIP'] : '';

	$sqlbendahara = "SELECT * FROM TBLPEJABAT WHERE REFJABATAN_ID=24";
	$pjbt_bendahara = Yii::app()->db->createCommand($sqlbendahara)->queryRow();
	$header['bendahara_pejabat_nama'] = $pjbt_bendahara ? $pjbt_bendahara['TBLPEJABAT_NAMA'] : '';
	$header['bendahara_pejabat_nip'] = $pjbt_bendahara ? $pjbt_bendahara['TBLPEJABAT_NIP'] : '';

	//echo json_encode($rows); Yii::app()->end();

	$otbs->MergeBlock('utama', $rows); 
	$otbs->MergeField('header', $header); 

			// $otbs->PlugIn(OPENTBS_DEBUG_XML_CURRENT); // debug the template

	$otbs->Show(OPENTBS_DOWNLOAD, $namafileDL);
	Yii::app()->end();


}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}