<?php

class Cetak_kartukendaliController extends Controller
{
	public function actionIndex()
	{
		$data['list_kecamatan'] = Yii::app()->db->createCommand()->select()->from('REFKECAMATAN')->queryAll();
		$data['list_jalan'] = Yii::app()->db->createCommand()->select()->from('tabjalan')->queryAll();
		$data['rek'] = Yii::app()->db->createCommand('
			SELECT
			*
			FROM
			TBLREKENING
			WHERE
			TBLREKENING_REKPAJAK = 1
			AND TBLREKENING_REKPAD = 1
			AND TBLREKENING_REKJENIS = 0
			ORDER BY
			TBLREKENING_REKPENDAPATAN,
			TBLREKENING_REKPAD,
			TBLREKENING_REKPAJAK,
			TBLREKENING_REKAYAT,
			TBLREKENING_REKJENIS
			')->queryAll();
		$data['sub_rek'] = Yii::app()->db->createCommand()
		->select('*')
		->from('TREKENING')
		->where('TREKENING_LEVEL=1')
		->queryAll();

		$this->renderPartial('index', array('data'=>$data));
	}

	public function getData()
	{
		$namaTBL = '';
		$tahunpjk = isset($_REQUEST['TBLPENDATAAN_THNPAJAK']) && !empty($_REQUEST['TBLPENDATAAN_THNPAJAK']) ? (int)$_REQUEST['TBLPENDATAAN_THNPAJAK'] : '';
		$bulanpjk = isset($_REQUEST['TBLPENDATAAN_BLNPAJAK']) && !empty($_REQUEST['TBLPENDATAAN_BLNPAJAK']) ? (int)$_REQUEST['TBLPENDATAAN_BLNPAJAK'] : '';

		$wherethnpajak = $tahunpjk!=0 ? (' AND TBLPENDATAAN_THNPAJAK='.$tahunpjk) : '';
		$whereblnpajak = $bulanpjk!=0 ? (' AND TBLPENDATAAN_BLNPAJAK='.$bulanpjk) : '';

		$rek = isset($_REQUEST['rekening']) && !empty($_REQUEST['rekening']) ? $_REQUEST['rekening'] : '';
		switch ( $rek ) {
			case '4.1.1.1.0':
			$namaTBL = 'TBLDAFTHOTEL';
			$AYAT = '1';
			break;
			
			case '4.1.1.2.0':
			$namaTBL = 'TBLDAFTRMAKAN';
			$AYAT = '2';
			break;
			
			case '4.1.1.3.0':
			$namaTBL = 'TBLDAFTHIBURAN';
			$AYAT = '3';
			break;
			
			case '4.1.1.4.0':
			$namaTBL = 'TBLDAFTREKLAME';
			$AYAT = '4';
			break;
			
			case '4.1.1.7.0':
			$namaTBL = 'TBLDAFTPARKIR';
			$AYAT = '7';
			break;
			
			case '4.1.1.8.0':
			$namaTBL = 'TBLDAFTTANAH';
			$AYAT = '8';
			break;
			
			case '4.1.1.9.0':
			$namaTBL = 'TBLDAFTBURUNG';
			$AYAT = '9';
			break;
			
			default:
			$namaTBL = 'TBLDAFTHOTEL';
			break;
		}
		$sql = "
		SELECT
		TBLDAFTAR.TBLDAFTAR_GOLONGAN
		,TBLDAFTAR.TBLDAFTAR_NOPOK
		,TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		,TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=1  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  JANUARI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=2  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  FEBRUARI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=3  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  MARET,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=4  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  APRIL,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=5  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  MEI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=6  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  JUNI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=7  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  JULI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=8  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  AGUSTUS,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=9  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  SEPTEMBER,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=10  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  OKTOBER,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=11  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  NOVEMBER,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=12  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  DESEMBER
		
		FROM TBLDAFTAR
		Inner Join " . $namaTBL . " ON TBLDAFTAR.TBLDAFTAR_NOPOK = " . $namaTBL . ".TBLDAFTAR_NOPOK
		
		WHERE
		" . $namaTBL . "_REKPENDAPATAN = 4
		AND " . $namaTBL . "_REKPAD = 1
		AND " . $namaTBL . "_REKPAJAK = 1
		AND " . $namaTBL . "_REKAYAT = ".$AYAT."
		".$wherethnpajak."
		".$whereblnpajak."
		and " . $namaTBL . "." . $namaTBL . "_ISJNSPENETAPAN='S'

		group by TBLDAFTAR.TBLDAFTAR_GOLONGAN
		,TBLDAFTAR.TBLDAFTAR_NOPOK
		,TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		,TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT

		ORDER BY  TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		,TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		,TBLDAFTAR.TBLDAFTAR_NOPOK
		";
		return $data = Yii::app()->db->createCommand( $sql )->queryAll();
	}

	public function actionCetak()
	{
		$tahun = substr($_REQUEST['tahun'], -2) ? substr($_REQUEST['tahun'], -2) : '0';
		$bulan = $_REQUEST['bulan'] ? $_REQUEST['bulan'] : '0';
		$cara = $_REQUEST['cara'] ? $_REQUEST['cara'] : '0';
		$kec = $_REQUEST['kec'] ? $_REQUEST['kec'] : '0';
		$TBLREKENING_KODE  = $_REQUEST['TBLREKENING_KODE'] ? $_REQUEST['TBLREKENING_KODE'] : '0';
		
		$AYAT = $_REQUEST['TBLREKENING_KODE'];
		
		if($AYAT=='4.1.1.4.0' ){
			$reklame = "SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR_BADANUSAHAALAMAT,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK,
			TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK,
			TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK,
			TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE,
			TBLDAFTREKLAME.TBLDAFTAR_GOLONGAN,
			TBLDAFTREKLAME.TBLDAFTAR_NOPOK,
			TBLDAFTREKLAME.TBLKECAMATAN_ID,
			TBLDAFTREKLAME.TBLKELURAHAN_ID,
			TBLDAFTREKLAME.TBLDAFTREKLAME_ISJNSPENETAPAN,
			TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRI,
			TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRI,
			TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRI,
			TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAK,
			TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN2,
			TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN1,
			TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME,
			TBLDAFTREKLAME.TBLDAFTREKLAME_THNBATASSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_BLNBATASSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_TGLBATASSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_NOMORSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_URUTSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_THNSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_BLNSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_TGLSKPD,
			TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRISETOR,
			TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRISETOR,
			TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRISETOR,
			TBLDAFTREKLAME.TBLDAFTREKLAME_REGSETOR,
			TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR,
			TBLDAFTREKLAME.REFJALAN_ID,
			CONCAT (
			TBLDAFTREKLAME_TGLSPTPD,
			CONCAT (
			'/',
			CONCAT (
			TBLDAFTREKLAME_BLNSPTPD,
			(CONCAT('/20', TBLDAFTREKLAME_THNSPTPD))
			)
			)
			) AS TGLSPT,
			CONCAT (
			TBLDAFTREKLAME_TGLENTRI,
			CONCAT (
			'/',
			CONCAT (
			TBLDAFTREKLAME_BLNENTRI,
			(CONCAT('/20', TBLDAFTREKLAME_THNENTRI))
			)
			)
			) AS Tgl_ENTRY,
			TO_DATE (
			CONCAT (
			TBLDAFTREKLAME_BLNSKPD,
			CONCAT (
			'/',
			CONCAT (TBLDAFTREKLAME_TGLSKPD, CONCAT('/20', TBLDAFTREKLAME_THNSKPD))
			)
			),
			'MM/DD/YY'
			) AS Tanggal_Ketetapan,
			(
			CASE
			WHEN NVL (TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD, 0) <> 0 THEN
			'SKPD Sudah Dicetak'
			WHEN NVL (TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR, 0) <> 0 THEN
			'SKPD Sudah Dicetak'
			END
			) AS status
			FROM
			TBLDAFTREKLAME
			LEFT JOIN TBLSETOR ON TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK = TBLSETOR.TBLPENDATAAN_THNPAJAK
			AND TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK = TBLSETOR.TBLPENDATAAN_BLNPAJAK
			AND TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK = TBLSETOR.TBLPENDATAAN_TGLPAJAK
			AND TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE = TBLSETOR.TBLPENDATAAN_PAJAKKE
			AND TBLDAFTREKLAME.TBLDAFTAR_NOPOK = TBLSETOR.TBLDAFTAR_NOPOK
			AND (
			NVL (TBLSETOR.TBLSETOR_JNSKETETAPAN, '0') = '0'
			OR TBLSETOR.TBLSETOR_JNSKETETAPAN = 'T'
			)
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			INNER JOIN TBLDAFTAR ON TBLDAFTREKLAME.TBLDAFTAR_NOPOK = TBLDAFTAR.tbldaftar_nopok
			)
			WHERE
			NVL (TBLDAFTREKLAME_THNSKPD, 0) <> 0
			AND NVL (TBLDAFTREKLAME_BLNSKPD, 0) <> 0
			AND NVL (TBLDAFTREKLAME_TGLSKPD, 0) <> 0
			AND NVL (TBLDAFTREKLAME_PAJAK, 0) > 0
			AND NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) > 0
			AND NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) <> 0
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."";

			$data['cetak'] = $cetak = Yii::app()->db->createCommand($reklame)->queryAll();

			$reklameheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 4
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($reklameheader)->queryrow();
		}

		elseif ($AYAT=='4.1.1.1.0' ){
			$hotel="SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTHOTEL.TBLDAFTHOTEL_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHOTEL.TBLDAFTHOTEL_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTHOTEL ON TBLDAFTHOTEL.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK

			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTHOTEL_REKPENDAPATAN = 4
			AND TBLDAFTHOTEL_REKPAD = 1
			AND TBLDAFTHOTEL_REKPAJAK = 1
			AND TBLDAFTHOTEL_REKAYAT = 1
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			
			AND TBLDAFTHOTEL.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($hotel)->queryAll();
			//AND TBLDAFTHOTEL.TBLDAFTHOTEL_ISJNSPENETAPAN = ".$cara."

			$hotelheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 1
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($hotelheader)->queryrow();
		}

		elseif ($AYAT =='4.1.1.2.0') {		
			$rmakan="SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTRMAKAN.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTRMAKAN.TBLDAFTRMAKAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTRMAKAN.TBLDAFTRMAKAN_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTRMAKAN ON TBLDAFTRMAKAN.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTRMAKAN_REKPENDAPATAN = 4
			AND TBLDAFTRMAKAN_REKPAD = 1
			AND TBLDAFTRMAKAN_REKPAJAK = 1
			AND TBLDAFTRMAKAN_REKAYAT = 2
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			
			AND TBLDAFTRMAKAN.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTRMAKAN.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($rmakan)->queryAll();
			// AND TBLDAFTRMAKAN.TBLDAFTRMAKAN_ISJNSPENETAPAN = ".$cara."

			$rmakanheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 2
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($rmakanheader)->queryrow();

		}
		elseif ($AYAT =='4.1.1.3.0') {		
			$hiburan="SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTHIBURAN.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTHIBURAN.TBLDAFTHIBURAN_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTHIBURAN.TBLDAFTHIBURAN_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTHIBURAN ON TBLDAFTHIBURAN.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTHIBURAN_REKPENDAPATAN = 4
			AND TBLDAFTHIBURAN_REKPAD = 1
			AND TBLDAFTHIBURAN_REKPAJAK = 1
			AND TBLDAFTHIBURAN_REKAYAT = 3
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			AND TBLDAFTHIBURAN.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTHIBURAN.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($hiburan)->queryAll();
			// AND TBLDAFTHIBURAN.TBLDAFTHIBURAN_ISJNSPENETAPAN = ".$cara."

			$hiburanheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 3
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($hiburanheader)->queryrow();
		}

		elseif ($AYAT =='4.1.1.7.0') {		
			$parkir="SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTPARKIR.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTPARKIR ON TBLDAFTPARKIR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTPARKIR_REKPENDAPATAN = 4
			AND TBLDAFTPARKIR_REKPAD = 1
			AND TBLDAFTPARKIR_REKPAJAK = 1
			AND TBLDAFTPARKIR_REKAYAT = 7
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			
			AND TBLDAFTPARKIR.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTPARKIR.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($parkir)->queryAll();
			// AND TBLDAFTPARKIR.TBLDAFTPARKIR_ISJNSPENETAPAN = ".$cara."

			$parkirheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 7
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($parkirheader)->queryrow();
		}
		elseif ($AYAT =='4.1.1.8.0') {			
			$tanah = "SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTTANAH.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTTANAH ON TBLDAFTTANAH.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTTANAH_REKPENDAPATAN = 4
			AND TBLDAFTTANAH_REKPAD = 1
			AND TBLDAFTTANAH_REKPAJAK = 1
			AND TBLDAFTTANAH_REKAYAT = 8
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			
			AND TBLDAFTTANAH.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTTANAH.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($tanah)->queryAll();
			// AND TBLDAFTTANAH.TBLDAFTTANAH_ISJNSPENETAPAN = ".$cara."

			$tanahheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 8
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($tanahheader)->queryrow();
		}

		elseif ($AYAT =='4.1.1.9.0') {
			$burung = "SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTBURUNG.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTBURUNG.TBLDAFTBURUNG_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBURUNG.TBLDAFTBURUNG_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTBURUNG ON TBLDAFTBURUNG.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTBURUNG_REKPENDAPATAN = 4
			AND TBLDAFTBURUNG_REKPAD = 1
			AND TBLDAFTBURUNG_REKPAJAK = 1
			AND TBLDAFTBURUNG_REKAYAT = 9
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			
			AND TBLDAFTBURUNG.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTBURUNG.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($burung)->queryAll();
			// AND TBLDAFTBURUNG.TBLDAFTBURUNG_ISJNSPENETAPAN = ".$cara."

			$burungheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 9
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($burungheader)->queryrow();
		}
		elseif ($AYAT =='4.1.1.11.0') {
			$bphtb = "SELECT
			*
			FROM
			(
			SELECT
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTBPHTB.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 1 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS januari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 2 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS februari,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 3 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS maret,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 4 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS april,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 5 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS mei,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 6 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juni,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 7 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS juli,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 8 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS agustus,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 9 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS september,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 10 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS oktober,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 11 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS november,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0)
			AND TBLPENDATAAN_BLNPAJAK = 12 THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS desember,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0) THEN
			NVL (TBLDAFTBPHTB.TBLDAFTBPHTB_PAJAKSKPD, 0)
			ELSE
			0
			END
			) AS jumlah_pembayaran,
			SUM (
			CASE
			WHEN (NVL(TBLDAFTBPHTB.TBLDAFTBPHTB_RUPIAHSETOR, 0) > 0) THEN
			1
			ELSE
			0
			END
			) AS jumlah_skpd
			FROM
			TBLDAFTAR
			INNER JOIN TBLDAFTBPHTB ON TBLDAFTBPHTB.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
			AND TBLDAFTBPHTB_REKPENDAPATAN = 4
			AND TBLDAFTBPHTB_REKPAD = 1
			AND TBLDAFTBPHTB_REKPAJAK = 1
			AND TBLDAFTBPHTB_REKAYAT = 9
			AND TBLPENDATAAN_THNPAJAK = ".$tahun."
			AND TBLPENDATAAN_BLNPAJAK = ".$bulan."
			AND TBLDAFTBPHTB.TBLKECAMATAN_ID = ".$kec."
			GROUP BY
			TBLDAFTBPHTB.TBLPENDATAAN_THNPAJAK,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
			TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
			TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
			ORDER BY
			tblkecamatan_idbadanusaha,
			tblkelurahan_idbadanusaha,
			tbldaftar_nopok";
			$data['cetak'] = $cetak = Yii::app()->db->createCommand($burung)->queryAll();
			// AND TBLDAFTBPHTB.TBLDAFTBPHTB_ISJNSPENETAPAN = ".$cara."

			$bphtbheader = "
			SELECT
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLPENDATAAN_THNPAJAK,
			TBLSETOR.TBLPENDATAAN_BLNPAJAK,
			TBLSETOR.TBLPENDATAAN_TGLPAJAK,
			TBLSETOR.TBLSETOR_NOMORSSPD,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKPAD,
			TBLSETOR.TBLSETOR_REKPAJAK,
			TBLSETOR.TBLSETOR_REKPENDAPATAN,
			TBLSETOR.TBLSETOR_REKAYAT,
			TBLSETOR.TBLSETOR_REKJENIS,
			TBLSETOR.TBLSETOR_REKSUBJENIS,
			TBLDAFTAR.TBLDAFTAR_GOLONGAN,
			TBLDAFTAR.TBLDAFTAR_NOPOK,
			TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
			TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
			TBLSETOR.TBLSETOR_RUPIAHSETOR,
			TBLSETOR.TBLSETOR_JNSBAYAR,
			(
			SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLSETOR.TBLSETOR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLSETOR.TBLSETOR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLSETOR.TBLSETOR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLSETOR.TBLSETOR_REKJENIS
			) AS TBLREKENING_NAMAREKENING,
			TBLSETOR.*
			FROM
			TBLSETOR
			INNER JOIN TBLDAFTAR ON TBLSETOR.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
			WHERE
			TBLSETOR.TBLSETOR_REKPENDAPATAN <> 0
			AND TBLSETOR.TBLSETOR_THNSETOR = 15
			AND TBLSETOR.TBLSETOR_BLNSETOR = 3
			AND TBLSETOR.TBLSETOR_STATUSBAYAR = 20
			AND TBLSETOR.TBLSETOR_REKPENDAPATAN = 4
			AND TBLSETOR.TBLSETOR_REKPAD = 1
			AND TBLSETOR.TBLSETOR_REKPAJAK = 1
			AND TBLSETOR.TBLSETOR_REKAYAT = 11
			ORDER BY
			TBLSETOR.TBLSETOR_THNSETOR,
			TBLSETOR.TBLSETOR_BLNSETOR,
			TBLSETOR.TBLSETOR_TGLSETOR,
			TBLSETOR.TBLSETOR_REKPENDAPATAN";
			$data['header'] = $header = Yii::app()->db->createCommand($bphtbheader)->queryrow();
		}

		
		if ($AYAT=='4.1.1.4.0') {
			$this->renderPartial('cetak-reklame',array('data'=>$data));
		} else {
			$this->renderPartial('cetak',array('data'=>$data));
		}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}
}