<?php

class Lapbulanan_bendaharaController extends Controller
{
	public function init()
	{
		Yii::import('ext.DBFetch');
	}

	public function actionIndex()
	{
		$this->renderPartial('index');
	}

	public function actionCari()
	{
		$tgl_setor = trim($_REQUEST['tgl_setor'])!='' ? date('Y-m-d', strtotime($_REQUEST['tgl_setor']) ) : "";
		$explode = explode('-',$tgl_setor);
		$tgl =$explode[2];
		$bln =$explode[1];
		$tahun = substr($explode[0], -2);

		$cari = "SELECT
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR = 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS BULAN_INI,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR < 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANLALU,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANINI,
		(
		SELECT
		TBLREKTARGET.TBLREKENING_NAMAREKENING
		FROM
		TBLREKTARGET
		WHERE
		TBLREKTARGET.REFBADANUSAHA_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKTARGET.PAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKTARGET.PJK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKTARGET.AYT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKTARGET.REFBADANUSAHA_JENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK,
		NVL (
		(
		SELECT
		NVL (
		TBLREKTARGET.TBLREKENING_TARGETANGGARAN,
		0
		)
		FROM
		TBLREKTARGET
		WHERE
		TBLREKTARGET.REFBADANUSAHA_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKTARGET.PAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKTARGET.PJK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKTARGET.AYT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKTARGET.REFBADANUSAHA_JENIS = TBLSETOR.TBLSETOR_REKJENIS
		),
		0
		) AS TARGETANGGARAN
		FROM
		TBLSETOR
		WHERE
		TBLSETOR.TBLSETOR_THNSETOR = '$tahun'
		AND TBLSETOR_STATUSBAYAR <> 20
		GROUP BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS
		HAVING
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) > 0
		ORDER BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS";

		$data['cari'] = $cari = Yii::app()->db->createCommand($cari)->queryAll();
		$this->renderPartial('tabel_laporan',array('data'=>$data));
	}


	public function actionCetak()
	{
		$tgl_setor = trim($_REQUEST['tgl_setor'])!='' ? date('Y-m-d', strtotime($_REQUEST['tgl_setor']) ) : "";
		$explode = explode('-',$tgl_setor);
		$tgl =$explode[2];
		$bln =$explode[1];
		$tahun = substr($explode[0], -2);

		$cetak = "SELECT
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR = 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS BULAN_INI,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR < 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANLALU,
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) AS SD_BULANINI,
		(
		SELECT
		TBLREKTARGET.TBLREKENING_NAMAREKENING
		FROM
		TBLREKTARGET
		WHERE
		TBLREKTARGET.REFBADANUSAHA_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKTARGET.PAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKTARGET.PJK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKTARGET.AYT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKTARGET.REFBADANUSAHA_JENIS = TBLSETOR.TBLSETOR_REKJENIS
		) AS NMREK,
		NVL (
		(
		SELECT
		NVL (
		TBLREKTARGET.TBLREKENING_TARGETANGGARAN,
		0
		)
		FROM
		TBLREKTARGET
		WHERE
		TBLREKTARGET.REFBADANUSAHA_REKPENDAPATAN = TBLSETOR.TBLSETOR_REKPENDAPATAN
		AND TBLREKTARGET.PAD = TBLSETOR.TBLSETOR_REKPAD
		AND TBLREKTARGET.PJK = TBLSETOR.TBLSETOR_REKPAJAK
		AND TBLREKTARGET.AYT = TBLSETOR.TBLSETOR_REKAYAT
		AND TBLREKTARGET.REFBADANUSAHA_JENIS = TBLSETOR.TBLSETOR_REKJENIS
		),
		0
		) AS TARGETANGGARAN
		FROM
		TBLSETOR
		WHERE
		TBLSETOR.TBLSETOR_THNSETOR = '$tahun'
		AND TBLSETOR_STATUSBAYAR <> 20
		GROUP BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS
		HAVING
		SUM (
		CASE
		WHEN TBLSETOR_BLNSETOR <= 3 THEN
		TBLSETOR.TBLSETOR_RUPIAHSETOR
		ELSE
		0
		END
		) > 0
		ORDER BY
		TBLSETOR.TBLSETOR_REKPENDAPATAN,
		TBLSETOR.TBLSETOR_REKPAD,
		TBLSETOR.TBLSETOR_REKPAJAK,
		TBLSETOR.TBLSETOR_REKAYAT,
		TBLSETOR.TBLSETOR_REKJENIS";

		$data['cetak'] = $cetak = Yii::app()->db->createCommand($cetak)->queryAll();
		$this->renderPartial('cetak',array('data'=>$data));
	}
	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}