<?php

class TunggakanpajakController extends Controller
{

	public function actionIndex()
	{
		$data['list_kecamatan'] = Yii::app()->db->createCommand()->select()->from('REFKECAMATAN')->queryAll();
		$data['rek'] = Yii::app()->db->createCommand('
		SELECT
			*
		FROM
			TBLREKENING
		WHERE
			TBLREKENING_REKPAJAK = 1
		AND TBLREKENING_REKPAD = 1
		AND TBLREKENING_REKJENIS = 0
		ORDER BY
			TBLREKENING_REKPENDAPATAN,
			TBLREKENING_REKPAD,
			TBLREKENING_REKPAJAK,
			TBLREKENING_REKAYAT,
			TBLREKENING_REKJENIS
		')->queryAll();
		$data['sub_rek'] = Yii::app()->db->createCommand()
						->select('*')
						->from('TREKENING')
						->where('TREKENING_LEVEL=1')
						->queryAll();

		$data['URL_APP'] = Yii::app()->getBaseUrl(true);
		$this->renderPartial('index', array('data'=>$data));
	}

	public function getData()
	{
		$namaTBL = '';
		$tahunpjk = isset($_REQUEST['TBLPENDATAAN_THNPAJAK']) && !empty($_REQUEST['TBLPENDATAAN_THNPAJAK']) ? (int)$_REQUEST['TBLPENDATAAN_THNPAJAK'] : '';
		$bulanpjk = isset($_REQUEST['TBLPENDATAAN_BLNPAJAK']) && !empty($_REQUEST['TBLPENDATAAN_BLNPAJAK']) ? (int)$_REQUEST['TBLPENDATAAN_BLNPAJAK'] : '';

		$wherethnpajak = $tahunpjk!=0 ? (' AND TBLPENDATAAN_THNPAJAK='.$tahunpjk) : '';
		$whereblnpajak = $bulanpjk!=0 ? (' AND TBLPENDATAAN_BLNPAJAK='.$bulanpjk) : '';

		$rek = isset($_REQUEST['rekening']) && !empty($_REQUEST['rekening']) ? $_REQUEST['rekening'] : '';
		switch ( $rek ) {
			case '4.1.1.1.0':
				$namaTBL = 'TBLDAFTHOTEL';
				$AYAT = '1';
				break;
			
			case '4.1.1.2.0':
				$namaTBL = 'TBLDAFTRMAKAN';
				$AYAT = '2';
				break;
			
			case '4.1.1.3.0':
				$namaTBL = 'TBLDAFTHIBURAN';
				$AYAT = '3';
				break;
			
			case '4.1.1.4.0':
				$namaTBL = 'TBLDAFTREKLAME';
				$AYAT = '4';
				break;
			
			case '4.1.1.7.0':
				$namaTBL = 'TBLDAFTPARKIR';
				$AYAT = '7';
				break;
			
			case '4.1.1.8.0':
				$namaTBL = 'TBLDAFTTANAH';
				$AYAT = '8';
				break;
			
			case '4.1.1.9.0':
				$namaTBL = 'TBLDAFTBURUNG';
				$AYAT = '9';
				break;
			
			default:
				$namaTBL = 'TBLDAFTHOTEL';
				break;
		}
		$sql = "
		SELECT
		TBLDAFTAR.TBLDAFTAR_GOLONGAN
		,TBLDAFTAR.TBLDAFTAR_NOPOK
		,TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		,TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=1  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  JANUARI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=2  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  FEBRUARI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=3  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  MARET,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=4  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  APRIL,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=5  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  MEI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=6  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  JUNI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=7  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  JULI,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=8  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  AGUSTUS,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=9  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  SEPTEMBER,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=10  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  OKTOBER,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=11  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  NOVEMBER,
		sum(CASE  WHEN TBLPENDATAAN_BLNPAJAK=12  THEN NVL(" . $namaTBL . "_OMSETPAJAK,0) ELSE 0 END) AS  DESEMBER
		
		FROM TBLDAFTAR
		Inner Join " . $namaTBL . " ON TBLDAFTAR.TBLDAFTAR_NOPOK = " . $namaTBL . ".TBLDAFTAR_NOPOK
		
		WHERE
		" . $namaTBL . "_REKPENDAPATAN = 4
		AND " . $namaTBL . "_REKPAD = 1
		AND " . $namaTBL . "_REKPAJAK = 1
		AND " . $namaTBL . "_REKAYAT = ".$AYAT."
		".$wherethnpajak."
		".$whereblnpajak."
		and " . $namaTBL . "." . $namaTBL . "_ISJNSPENETAPAN='S'

		group by TBLDAFTAR.TBLDAFTAR_GOLONGAN
		,TBLDAFTAR.TBLDAFTAR_NOPOK
		,TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		,TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA
		,TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT

		ORDER BY  TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		,TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		,TBLDAFTAR.TBLDAFTAR_NOPOK
		";
		return $data = Yii::app()->db->createCommand( $sql )->queryAll();
	}

	public function actionCetak()
	{
		$tahun = substr($_REQUEST['tahun'], -2);
		$TBLREKENING_KODE = $_REQUEST['TBLREKENING_KODE'];

		$sql = "SELECT
		*
		FROM
		(
		SELECT
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
		TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 1 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 1 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS januari,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 2 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 2 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS februari,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 3 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 3 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS maret,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 4 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 4 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS april,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 5 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 5 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS mei,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 6 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 6 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS juni,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 7 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 7 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS juli,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 8 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 8 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS agustus,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 9 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 9 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS september,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 10 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 10 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS oktober,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 11 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 11 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS november,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 12 THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) = 0)
		AND TBLANGSURAN.TBLANGSURAN_BLNBATASKETETAPAN = 12 THEN
		0 - NVL (TBLANGSURAN.TBLANGSURAN_ANGSURAN, 0)
		ELSE
		0
		END
		) AS desember,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0) THEN
		NVL (TBLANGSURAN.TBLANGSURAN_SETORAN, 0)
		ELSE
		0
		END
		) AS jumlah_pembayaran,
		SUM (
		CASE
		WHEN (NVL(TBLANGSURAN.TBLANGSURAN_SETORAN, 0) > 0) THEN
		1
		ELSE
		0
		END
		) AS jumlah_skpd
		FROM
		TBLDAFTAR
		INNER JOIN TBLDAFTHOTEL ON TBLDAFTHOTEL.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
		INNER JOIN TBLANGSURAN ON TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK = TBLANGSURAN.TBLPENDATAAN_THNPAJAK
		AND TBLDAFTHOTEL.TBLPENDATAAN_BLNPAJAK = TBLANGSURAN.TBLPENDATAAN_BLNPAJAK
		AND TBLDAFTHOTEL.TBLDAFTAR_NOPOK = TBLANGSURAN.TBLDAFTAR_NOMORPOKOK
		WHERE
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
		AND TBLDAFTHOTEL.TBLDAFTHOTEL_REKPENDAPATAN = 4
		AND TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAD = 1
		AND TBLDAFTHOTEL.TBLDAFTHOTEL_REKPAJAK = 1
		AND TBLDAFTHOTEL.TBLDAFTHOTEL_REKAYAT = ".$TBLREKENING_KODE."
		AND TBLANGSURAN.TBLANGSURAN_THNBATASKETETAPAN = ".$tahun."
		GROUP BY
		TBLDAFTHOTEL.TBLPENDATAAN_THNPAJAK,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
		TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
		)
		ORDER BY
		TBLKECAMATAN_IDBADANUSAHA,
		TBLKELURAHAN_IDBADANUSAHA,
		TBLDAFTAR_NOPOK";

		$data['tunggakan'] = $skpda = Yii::app()->db->createCommand($sql)->queryAll();
		$this->renderPartial('cetak',array('data'=>$data));
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}