<?php

class Bukukendali_skpdController extends Controller
{
	public function actionIndex()
	{
		$data['list_kecamatan'] = Yii::app()->db->createCommand()->select()->from('REFKECAMATAN')->queryAll();
		$data['list_kodejalan'] = Yii::app()->db->createCommand()->select()->from('RREKJALAN')->queryAll();
		$data['rek'] = Yii::app()->db->createCommand('
			SELECT
				*
			FROM
				TBLREKENING
			WHERE
				TBLREKENING_REKPAJAK = 1
			AND TBLREKENING_REKPAD = 1
			AND TBLREKENING_REKJENIS = 0
			AND TBLREKENING_REKAYAT = 4 OR TBLREKENING_REKAYAT = 8
			AND TBLREKENING_REKJENIS = 0
			ORDER BY
			TBLREKENING_REKPENDAPATAN,
			TBLREKENING_REKPAD,
			TBLREKENING_REKPAJAK,
			TBLREKENING_REKAYAT,
			TBLREKENING_REKJENIS
			')->queryAll();
		$data['sub_rek'] = Yii::app()->db->createCommand()
		->select('*')
		->from('TREKENING')
		->where('TREKENING_LEVEL=1')
		->queryAll();
		
		$this->renderPartial('index', array('data'=>$data));
	}

	public function actionCetak()
	{
		$TBLPENDATAAN_THNPAJAK = isset($_REQUEST['TBLPENDATAAN_THNPAJAK']) && !empty($_REQUEST['TBLPENDATAAN_THNPAJAK']) ? (int)$_REQUEST['TBLPENDATAAN_THNPAJAK'] : '';
		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);
		$TBLREKENING_KODE = isset($_REQUEST['TBLREKENING_KODE']) && !empty($_REQUEST['TBLREKENING_KODE']) ? $_REQUEST['TBLREKENING_KODE'] : '';
		$TBLREKENING_KODESUB = isset($_REQUEST['TBLREKENING_KODESUB']) && !empty($_REQUEST['TBLREKENING_KODESUB']) ? $_REQUEST['TBLREKENING_KODESUB'] : '';
		$KODEJALAN = isset($_REQUEST['KODEJALAN']) && !empty($_REQUEST['KODEJALAN']) ? $_REQUEST['KODEJALAN'] : '';
		$TBLKECAMATAN_ID = isset($_REQUEST['TBLKECAMATAN_ID']) && !empty($_REQUEST['TBLKECAMATAN_ID']) ? $_REQUEST['TBLKECAMATAN_ID'] : '';
		$PENETAPAN_CARA = isset($_REQUEST['PENETAPAN_CARA']) && !empty($_REQUEST['PENETAPAN_CARA']) ? $_REQUEST['PENETAPAN_CARA'] : '';

		if ($TBLREKENING_KODE=='4.1.1.4.0') {
			$sql="
        SELECT
			*
		FROM
			(
				SELECT
					TBLDAFTAR_BADANUSAHANAMA,
					TBLDAFTAR_BADANUSAHAALAMAT,
					TBLDAFTAR_JENISPENDAPATAN,
					TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
					TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
					TBLSETOR.TBLSETOR_RUPIAHSETOR,
					TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK,
					TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK,
					TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK,
					TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE,
					TBLDAFTREKLAME.TBLDAFTAR_GOLONGAN,
					TBLDAFTREKLAME.TBLDAFTAR_NOPOK,
					TBLDAFTREKLAME.TBLKECAMATAN_ID,
					TBLDAFTREKLAME.TBLKELURAHAN_ID,
					TBLDAFTREKLAME.TBLDAFTREKLAME_ISJNSPENETAPAN,
					TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRI,
					TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRI,
					TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRI,
					TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAK,
					TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN2,
					TBLDAFTREKLAME.TBLDAFTREKLAME_KETERANGAN1,
					TBLDAFTREKLAME.TBLDAFTREKLAME_JNSREKLAME,
					TBLDAFTREKLAME.TBLDAFTREKLAME_THNBATASSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_BLNBATASSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_TGLBATASSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_NOMORSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_URUTSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_THNSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_BLNSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_TGLSKPD,
					TBLDAFTREKLAME.TBLDAFTREKLAME_THNENTRISETOR,
					TBLDAFTREKLAME.TBLDAFTREKLAME_BLNENTRISETOR,
					TBLDAFTREKLAME.TBLDAFTREKLAME_TGLENTRISETOR,
					TBLDAFTREKLAME.TBLDAFTREKLAME_REGSETOR,
					TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR,
					TBLDAFTREKLAME.REFJALAN_ID,
					CONCAT (
						TBLDAFTREKLAME_TGLSPTPD,
						CONCAT (
							'/',
							CONCAT (
								TBLDAFTREKLAME_BLNSPTPD,
								(CONCAT('/20', TBLDAFTREKLAME_THNSPTPD))
							)
						)
					) AS TGLSPT,
					CONCAT (
						TBLDAFTREKLAME_TGLENTRI,
						CONCAT (
							'/',
							CONCAT (
								TBLDAFTREKLAME_BLNENTRI,
								(CONCAT('/20', TBLDAFTREKLAME_THNENTRI))
							)
						)
					) AS Tgl_ENTRY,
					TO_DATE (
						CONCAT (
							TBLDAFTREKLAME_BLNSKPD,
							CONCAT (
								'/',
								CONCAT (TBLDAFTREKLAME_TGLSKPD, CONCAT('/20', TBLDAFTREKLAME_THNSKPD))
							)
						),
						'MM/DD/YY'
					) AS Tanggal_Ketetapan,
					(
						CASE
						WHEN NVL (TBLDAFTREKLAME.TBLDAFTREKLAME_PAJAKSKPD, 0) <> 0 THEN
							'SKPD Sudah Dicetak'
						WHEN NVL (TBLDAFTREKLAME.TBLDAFTREKLAME_RUPIAHSETOR, 0) <> 0 THEN
							'SKPD Sudah Dicetak'
						END
					) AS status
				FROM
					TBLDAFTREKLAME
				LEFT JOIN TBLSETOR ON TBLDAFTREKLAME.TBLPENDATAAN_THNPAJAK = TBLSETOR.TBLPENDATAAN_THNPAJAK
				AND TBLDAFTREKLAME.TBLPENDATAAN_BLNPAJAK = TBLSETOR.TBLPENDATAAN_BLNPAJAK
				AND TBLDAFTREKLAME.TBLPENDATAAN_TGLPAJAK = TBLSETOR.TBLPENDATAAN_TGLPAJAK
				AND TBLDAFTREKLAME.TBLPENDATAAN_PAJAKKE = TBLSETOR.TBLPENDATAAN_PAJAKKE
				AND TBLDAFTREKLAME.TBLDAFTAR_NOPOK = TBLSETOR.TBLDAFTAR_NOPOK
				AND (
					NVL (TBLSETOR.TBLSETOR_JNSKETETAPAN, '0') = '0'
					OR TBLSETOR.TBLSETOR_JNSKETETAPAN = 'T'
				)
				AND TBLSETOR.TBLSETOR_REKPAJAK = 1
				INNER JOIN TBLDAFTAR ON TBLDAFTREKLAME.TBLDAFTAR_NOPOK = TBLDAFTAR.tbldaftar_nopok
			)
		WHERE
			NVL (TBLDAFTREKLAME_THNSKPD, 0) <> 0
		AND NVL (TBLDAFTREKLAME_BLNSKPD, 0) <> 0
		AND NVL (TBLDAFTREKLAME_TGLSKPD, 0) <> 0
		AND NVL (TBLDAFTREKLAME_PAJAK, 0) > 0
		AND NVL (TBLDAFTREKLAME_PAJAKSKPD, 0) > 0
		AND NVL (TBLDAFTREKLAME_RUPIAHSETOR, 0) <> 0
		AND TBLPENDATAAN_THNPAJAK = ".$THNPJK."
		AND TBLKECAMATAN_ID = ".$TBLKECAMATAN_ID."
		AND REFJALAN_ID = ".$KODEJALAN."
		-- AND Tanggal_Ketetapan < TO_DATE ('2017-09-12', 'YYYY-MM-DD')
		"
		;
		} else {
			$sql="
        SELECT
			*
		FROM
			(
				SELECT
					TBLDAFTAR.TBLDAFTAR_NOPOK,
					TBLDAFTTANAH.TBLPENDATAAN_THNPAJAK,
					TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
					TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
					TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
					TBLDAFTAR.TBLDAFTAR_GOLONGAN,
					TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
					TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
					TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 1 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS januari,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 2 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS februari,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 3 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS maret,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 4 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS april,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 5 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS mei,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 6 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS juni,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 7 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS juli,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 8 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS agustus,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 9 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS september,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 10 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS oktober,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 11 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS november,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0)
						AND TBLPENDATAAN_BLNPAJAK = 12 THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS desember,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0) THEN
							NVL (TBLDAFTTANAH.TBLDAFTTANAH_PAJAKSKPD, 0)
						ELSE
							0
						END
					) AS jumlah_pembayaran,
					SUM (
						CASE
						WHEN (NVL(TBLDAFTTANAH.TBLDAFTTANAH_RUPIAHSETOR, 0) > 0) THEN
							1
						ELSE
							0
						END
					) AS jumlah_skpd
				FROM
					TBLDAFTAR
				INNER JOIN TBLDAFTTANAH ON TBLDAFTTANAH.TBLDAFTAR_NOPOK = TBLDAFTAR.TBLDAFTAR_NOPOK
				WHERE
					TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA IS NOT NULL
				AND TBLDAFTTANAH_REKPENDAPATAN = 4
				AND TBLDAFTTANAH_REKPAD = 1
				AND TBLDAFTTANAH_REKPAJAK = 1
				AND TBLDAFTTANAH_REKAYAT = 8
				-- AND TBLDAFTTANAH_ISJNSPENETAPAN = 
				AND TBLPENDATAAN_THNPAJAK = ".$THNPJK."
				GROUP BY
					TBLDAFTTANAH.TBLPENDATAAN_THNPAJAK,
					TBLDAFTAR.TBLDAFTAR_NOPOK,
					TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
					TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
					TBLDAFTAR.TBLDAFTAR_JENISPENDAPATAN,
					TBLDAFTAR.TBLDAFTAR_GOLONGAN,
					TBLDAFTAR.TBLDAFTAR_NOPOK,
					TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
					TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
					TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT
			)
		ORDER BY
			TBLKECAMATAN_IDBADANUSAHA,
			TBLKELURAHAN_IDBADANUSAHA,
			TBLDAFTAR_NOPOK
		"
		;
		}
		$data['cetak'] = Yii::app()->db->createCommand( $sql )->queryAll();

		// print_r($data['cetak']);
		
		if ($TBLREKENING_KODE=='4.1.1.4.0') {
			$this->renderPartial('cetak-reklame',array('data'=>$data));
		} else {
			$this->renderPartial('cetak',array('data'=>$data));
		}
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}