<?php

class Skpdkb_parkirController extends Controller
{
	var $KODE_GOL = 2;
	var $PAJAK_AYAT = 7;
	var $PAJAK_REK = '4.1.1.7.0';

	public function actionIndex()
	{
		$data['theme_baseurl'] = Yii::app()->theme->baseUrl;
		$data['sub_rek'] = TRekening::model()->getRekeningSubAktif('4110100');

		$data['rek'] = Yii::app()->db->createCommand("
		SELECT * 
		FROM TBLREKENING
		WHERE TBLREKENING_KODE LIKE '4.1.1.7.%'
		ORDER BY TBLREKENING_KODE
		")
		->queryAll();

		$this->renderPartial('index', array('data'=>$data));
	}

	public function actionautocompletewpparkir()
	{
		header('Content-type: text/json');
		header('Content-type: application/json');
		
		$query = trim($_REQUEST['query']);

		$select = 'TBLDAFTPARKIR.TBLDAFTAR_NOPOK, TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA, TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT';
		$from = 'TBLDAFTPARKIR';
		$filter = array(
			'LK__TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA' => $query
			,'LK__TBLDAFTAR.TBLDAFTAR_NOPOK' => $query
		);

		$filter_AND = array(
			//'EQ__TREKENING_KODE' => '4110100'
			// ,'EQ__tblsubyek_jenisusaha' => $jenisusaha
			// ,'EQ__tblsubyek_isaktif' => "T"
		);

		$otherquery = array(
			'limit'=> 30
			,'join'=> array('TBLDAFTAR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTPARKIR.TBLDAFTAR_NOPOK')
			,'order'=> 'TBLDAFTPARKIR.TBLDAFTAR_NOPOK ASC'
			,'group'=> 'TBLDAFTPARKIR.TBLDAFTAR_NOPOK, TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA, TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT'
		);

		$arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'filter_AND'=>$filter_AND,'filterOR'=>true,'otherquery'=>$otherquery,'mode'=>'LIST');
		$results = DBFetch::query($arrayConfig);

		$suggestions = array();
		 
		foreach($results as $result)
		{
			$suggestions[] = array(
			"value" => $result['TBLDAFTAR_NOPOK']. ' | ' . $result['TBLDAFTAR_BADANUSAHANAMA']
			,"data" => $result['TBLDAFTAR_NOPOK']
			,"TBLDAFTAR_BADANUSAHANAMA" => $result['TBLDAFTAR_BADANUSAHANAMA']
			,"TBLDAFTAR_BADANUSAHAALAMAT" => $result['TBLDAFTAR_BADANUSAHAALAMAT']
			,"TBLDAFTAR_NOPOK" => $result['TBLDAFTAR_NOPOK']
			);
		}
 
		echo CJSON::encode(array('suggestions' => $suggestions));
	}

	public function actiongetdata()
	{
		$TBLDAFTAR_NOPOK = trim($_POST['TBLDAFTAR_NOPOK']);
		$bulan = trim($_POST['bulan']);
		$tahun = trim($_POST['tahun']);
		$tahun_substr = substr($tahun, 2,4);
		$proses = $this->cekProses($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);
		$cek = $this->cekPernahDaftar($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);
		$bayar =$this->cekBayar($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);
		$angsur =$this->cekAngsur($tahun_substr, $bulan, $TBLDAFTAR_NOPOK);

		if ($bayar > 0) {
			$data['data'] = 'sudah dibayar';	
		} else if ($angsur > 0){
			$data['data'] = 'ada angsur';
		} else  if ($proses == '') {
			$data['data'] = 'belum terdaftar';	
		} else if ($cek>0){

			$data['data'] = 'sudah entri';
		
		$select = "
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_ISAKTIF,
		TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
		TBLDAFTAR.TBLDAFTAR_PEMILIKALAMAT,
		REFBADANUSAHA.REKENING_KODE,
		REFBADANUSAHA.REFBADANUSAHA_REKPENDAPATAN,
		REFBADANUSAHA.REFBADANUSAHA_REKPAD,
		REFBADANUSAHA.REFBADANUSAHA_REKPJK,
		REFBADANUSAHA.REFBADANUSAHA_REKAYAT,
		REFBADANUSAHA.REFBADANUSAHA_REKJENIS,
		REFBADANUSAHA.REFBADANUSAHA_PERSEN,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_NOMORPERIKSA, 0) AS TBLDAFTPARKIR_NOMORPERIKSA,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_REGKURANGBAYAR, 0) AS TBLDAFTPARKIR_REGKURANGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_PAJAKPERIKSA,0) AS TBLDAFTPARKIR_PAJAKPERIKSA,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BUNGAKRGBAYAR,0) AS TBLDAFTPARKIR_BUNGAKRGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_NAKB,0) AS TBLDAFTPARKIR_NAKB,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_DENDAKRGBAYAR,0) AS TBLDAFTPARKIR_DENDAKRGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHKRGBAYAR,0) AS TBLDAFTPARKIR_RUPIAHKRGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKBAWAL,0) AS TBLDAFTPARKIR_BLNKBAWAL,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKBAKHIR,0) AS TBLDAFTPARKIR_BLNKBAKHIR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_TGLKURANGBAYAR,0) AS TBLDAFTPARKIR_TGLKURANGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKURANGBAYAR,0) AS TBLDAFTPARKIR_BLNKURANGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_THNKURANGBAYAR,0) AS TBLDAFTPARKIR_THNKURANGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_TGLBTSKRGBAYAR,0) AS TBLDAFTPARKIR_TGLBTSKRGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNBTSKRGBAYAR,0) AS TBLDAFTPARKIR_BLNBTSKRGBAYAR,
		NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_THNBTSKRGBAYAR,0) AS TBLDAFTPARKIR_THNBTSKRGBAYAR 
		";
		$from = 'TBLDAFTAR';
		$filter = array(
			'EQ__TBLDAFTAR.TBLDAFTAR_NOPOK' => $TBLDAFTAR_NOPOK
		);

		$filter_AND = array(
			'EQ__TBLDAFTAR.TBLDAFTAR_GOLONGAN' => $this->KODE_GOL
			,'EQ__REFBADANUSAHA.REFBADANUSAHA_REKAYAT' => $this->PAJAK_AYAT
			,'EQ__TBLDAFTPARKIR.TBLPENDATAAN_THNPAJAK' => $tahun_substr
			,'EQ__TBLDAFTPARKIR.TBLPENDATAAN_BLNPAJAK' => $bulan
			// ,'EQ__tblsubyek_isaktif' => "T"
		);

		$otherquery = array(
			'limit'=> 30
			,'join'=> array('REFBADANUSAHA', 'REFBADANUSAHA.REFBADANUSAHA_ID= TBLDAFTAR.REFBADANUSAHA_IDBADANUSAHA')
			,'join_2'=> array('TBLDAFTPARKIR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTPARKIR.TBLDAFTAR_NOPOK')
			,'order'=> 'TBLDAFTAR.TBLDAFTAR_NOPOK ASC'
			,'andwhere_hrp'=> 'NVL(TBLDAFTPARKIR.TBLPENDATAAN_TGLPAJAK,0) = 0'
		);
		$model = DBFetch::query( array('select'=>$select,'from'=>$from,'filter'=>$filter,'filter_AND'=>$filter_AND,'filterOR'=>true,'otherquery'=>$otherquery,'mode'=>'DETAIL') );

		$data['TBLDAFTAR_BADANUSAHANAMA'] =$model['TBLDAFTAR_BADANUSAHANAMA'];
		$data['TBLDAFTAR_BADANUSAHAALAMAT'] =$model['TBLDAFTAR_BADANUSAHAALAMAT'];
		$data['REKENING_KODE'] =$model['REKENING_KODE'];
		$data['TREKENING_TARIF'] =$model['REFBADANUSAHA_PERSEN'];
		
		$data['REFBADANUSAHA_REKPENDAPATAN'] =$model['REFBADANUSAHA_REKPENDAPATAN'];
		$data['REFBADANUSAHA_REKPAD'] =$model['REFBADANUSAHA_REKPAD'];
		$data['REFBADANUSAHA_REKPJK'] =$model['REFBADANUSAHA_REKPJK'];
		$data['REFBADANUSAHA_REKAYAT'] =$model['REFBADANUSAHA_REKAYAT'];
		$data['REFBADANUSAHA_REKJENIS'] =$model['REFBADANUSAHA_REKJENIS'];

		$data['TBLDAFTPARKIR_REGKURANGBAYAR'] = $model['TBLDAFTPARKIR_REGKURANGBAYAR'];
		$data['TBLDAFTPARKIR_NOMORPERIKSA'] = $model['TBLDAFTPARKIR_NOMORPERIKSA'];
		$data['TBLDAFTPARKIR_PAJAKPERIKSA'] = $model['TBLDAFTPARKIR_PAJAKPERIKSA']; 
		$data['TBLDAFTPARKIR_BUNGAKRGBAYAR'] = $model['TBLDAFTPARKIR_BUNGAKRGBAYAR']; 
		$data['TBLDAFTPARKIR_NAKB'] = $model['TBLDAFTPARKIR_NAKB']; 
		$data['TBLDAFTPARKIR_DENDAKRGBAYAR'] = $model['TBLDAFTPARKIR_DENDAKRGBAYAR']; 
		$data['TBLDAFTPARKIR_RUPIAHKRGBAYAR'] = $model['TBLDAFTPARKIR_RUPIAHKRGBAYAR']; 
		$data['TBLDAFTPARKIR_BLNKBAWAL'] = $model['TBLDAFTPARKIR_BLNKBAWAL']; 
		$data['TBLDAFTPARKIR_BLNKBAKHIR'] = $model['TBLDAFTPARKIR_BLNKBAKHIR']; 
		$data['TBLDAFTPARKIR_TGLKURANGBAYAR'] = sprintf("%02d",$model['TBLDAFTPARKIR_TGLKURANGBAYAR']); 
		$data['TBLDAFTPARKIR_BLNKURANGBAYAR'] = sprintf("%02d",$model['TBLDAFTPARKIR_BLNKURANGBAYAR']); 
		$data['TBLDAFTPARKIR_THNKURANGBAYAR'] = $model['TBLDAFTPARKIR_THNKURANGBAYAR']; 
		$data['TBLDAFTPARKIR_TGLBTSKRGBAYAR'] = sprintf("%02d",$model['TBLDAFTPARKIR_TGLBTSKRGBAYAR']); 
		$data['TBLDAFTPARKIR_BLNBTSKRGBAYAR'] = sprintf("%02d",$model['TBLDAFTPARKIR_BLNBTSKRGBAYAR']); 
		$data['TBLDAFTPARKIR_THNBTSKRGBAYAR'] = $model['TBLDAFTPARKIR_THNBTSKRGBAYAR']; 
		
		} else {

		$data['data'] = 'sudah terdaftar';
		
		$select = "
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_ISAKTIF,
		TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
		TBLDAFTAR.TBLDAFTAR_PEMILIKALAMAT,
		REFBADANUSAHA.REKENING_KODE,
		REFBADANUSAHA.REFBADANUSAHA_REKPENDAPATAN,
		REFBADANUSAHA.REFBADANUSAHA_REKPAD,
		REFBADANUSAHA.REFBADANUSAHA_REKPJK,
		REFBADANUSAHA.REFBADANUSAHA_REKAYAT,
		REFBADANUSAHA.REFBADANUSAHA_REKJENIS,
		REFBADANUSAHA.REFBADANUSAHA_PERSEN
		";
		$from = 'TBLDAFTAR';
		$filter = array(
			'EQ__TBLDAFTAR_NOPOK' => $TBLDAFTAR_NOPOK
		);

		$filter_AND = array(
			'EQ__TBLDAFTAR_GOLONGAN' => $this->KODE_GOL
			,'EQ__REFBADANUSAHA.REFBADANUSAHA_REKAYAT' => $this->PAJAK_AYAT
			// ,'EQ__tblsubyek_isaktif' => "T"
		);

		$otherquery = array(
			'limit'=> 30
			,'join'=> array('REFBADANUSAHA', 'REFBADANUSAHA.REFBADANUSAHA_ID= TBLDAFTAR.REFBADANUSAHA_IDBADANUSAHA')
			,'order'=> 'TBLDAFTAR_NOPOK ASC'
		);
		$model = DBFetch::query( array('select'=>$select,'from'=>$from,'filter'=>$filter,'filter_AND'=>$filter_AND,'filterOR'=>true,'otherquery'=>$otherquery,'mode'=>'DETAIL') );

		$data['TBLDAFTAR_BADANUSAHANAMA'] =$model['TBLDAFTAR_BADANUSAHANAMA'];
		$data['TBLDAFTAR_BADANUSAHAALAMAT'] =$model['TBLDAFTAR_BADANUSAHAALAMAT'];
		$data['REKENING_KODE'] =$model['REKENING_KODE'];
		$data['TREKENING_TARIF'] =$model['REFBADANUSAHA_PERSEN'];
		
		$data['REFBADANUSAHA_REKPENDAPATAN'] =$model['REFBADANUSAHA_REKPENDAPATAN'];
		$data['REFBADANUSAHA_REKPAD'] =$model['REFBADANUSAHA_REKPAD'];
		$data['REFBADANUSAHA_REKPJK'] =$model['REFBADANUSAHA_REKPJK'];
		$data['REFBADANUSAHA_REKAYAT'] =$model['REFBADANUSAHA_REKAYAT'];
		$data['REFBADANUSAHA_REKJENIS'] =$model['REFBADANUSAHA_REKJENIS'];

		}

		echo CJSON::encode($data);
	}

	public function cekProses($tahun, $bulan, $TBLDAFTAR_NOPOK)
	{
		$model = Yii::app()->db->createCommand('SELECT TBLPENDATAAN_THNPAJAK FROM TBLDAFTPARKIR WHERE TBLPENDATAAN_THNPAJAK ='.$tahun.' AND TBLPENDATAAN_BLNPAJAK='.$bulan.' AND TBLDAFTAR_NOPOK='.$TBLDAFTAR_NOPOK.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function cekPernahDaftar($thn, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT COUNT(TBLDAFTPARKIR_THNKURANGBAYAR) AS JML FROM TBLDAFTPARKIR WHERE TBLPENDATAAN_THNPAJAK ='.$thn.' AND TBLPENDATAAN_BLNPAJAK='.$bulan.' AND TBLDAFTAR_NOPOK='.$nopok.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function cekBayar($THNPAJAK, $BLNPAJAK, $NOPOKOK)
	{
		$model = Yii::app()->db->createCommand("SELECT COUNT(TBLPENDATAAN_THNPAJAK) AS JML FROM TBLSETORANBPD WHERE TBLPENDATAAN_THNPAJAK =".$THNPAJAK." AND TBLPENDATAAN_BLNPAJAK=".$BLNPAJAK." AND TBLDAFTAR_NOPOK=".$NOPOKOK." AND TBLSETORANBPD_JNSKETETAPAN = 'K'")->queryScalar();
		return $model;
	}

	public function cekAngsur($thn, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT COUNT(TBLPENDATAAN_THNPAJAK) AS JML FROM TBLANGSURAN WHERE TBLANGSURAN_PAJAKKE = 1 AND TBLPENDATAAN_THNPAJAK ='.$thn.' AND TBLPENDATAAN_BLNPAJAK='.$bulan.' AND TBLDAFTAR_NOPOK='.$nopok)->queryScalar();
		return $model;
	}

	public function CekNoRegisterKB($tahun, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT NVL(TBLDAFTPARKIR_REGKURANGBAYAR,0) AS NOKB FROM TBLDAFTPARKIR WHERE TBLPENDATAAN_THNPAJAK = '.$tahun.' AND TBLPENDATAAN_BLNPAJAK = '.$bulan.' AND TBLDAFTAR_NOPOK = '.$nopok.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function GetLastNoKB($tahun, $bulan, $nopok)
	{
		$model = Yii::app()->db->createCommand('SELECT MAX(NVL(TBLKRGBAYAR_REGKURANGBAYAR,0)) AS LAST_KB FROM TBLKRGBAYAR WHERE TBLPENDATAAN_THNPAJAK = '.$tahun.' AND TBLPENDATAAN_BLNPAJAK = '.$bulan.' AND TBLDAFTAR_NOPOK = '.$nopok.' AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0')->queryScalar();
		return $model;
	}

	public function actionSimpanSKPDKBParkir()
	{
		Yii::import('ext.LokalIndonesia');

		$PARAM = $_REQUEST;
		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];

		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);

		$TBLPENDATAAN_BLNPAJAK = !empty($_REQUEST['TBLPENDATAAN_BLNPAJAK']) ? $_REQUEST['TBLPENDATAAN_BLNPAJAK'] : '';

		$TBLDAFTPARKIR_TGLKURANGBAYAR = !empty($_REQUEST['TBLDAFTPARKIR_TGLKURANGBAYAR']) ? $_REQUEST['TBLDAFTPARKIR_TGLKURANGBAYAR'] : '';

		$TBLDAFTPARKIR_TGLBTSKRGBAYAR = !empty($_REQUEST['TBLDAFTPARKIR_TGLBTSKRGBAYAR']) ? $_REQUEST['TBLDAFTPARKIR_TGLBTSKRGBAYAR'] : '';

		$TBLDAFTPARKIR_TGLPERIKSA = !empty($_REQUEST['TBLDAFTPARKIR_TGLPERIKSA']) ? $_REQUEST['TBLDAFTPARKIR_TGLPERIKSA'] : '';

		if ($TBLDAFTPARKIR_TGLKURANGBAYAR !='') {
			$exp_TGLTERIMADAFTAR = explode('-', $TBLDAFTPARKIR_TGLKURANGBAYAR);
			$pecahtgldaftar = $exp_TGLTERIMADAFTAR[0];
			$pecahbulandaftar = $exp_TGLTERIMADAFTAR[1];
			$pecahthndaftar = substr($exp_TGLTERIMADAFTAR[2], -2);	
		} else {
			$pecahtgldaftar = '';
			$pecahbulandaftar = '';
			$pecahthndaftar = '';
		}

		if ($TBLDAFTPARKIR_TGLBTSKRGBAYAR !='') {
			$exp_TGLENTRYDAFTAR = explode('-', $TBLDAFTPARKIR_TGLBTSKRGBAYAR);
			$pecahtglentry = $exp_TGLENTRYDAFTAR[0];
			$pecahbulanentry = $exp_TGLENTRYDAFTAR[1];
			$pecahthnentry = substr($exp_TGLENTRYDAFTAR[2], -2);
		} else {
			$pecahtglentry = '';
			$pecahbulanentry = '';
			$pecahthnentry = '';
		}

		if ($TBLDAFTPARKIR_TGLPERIKSA !='') {
			$exp_TGLPERIKSA = explode('-', $TBLDAFTPARKIR_TGLPERIKSA);
			$pecahtglperiksa = $exp_TGLPERIKSA[0];
			$pecahbulanperiksa = $exp_TGLPERIKSA[1];
			$pecahthnperiksa = substr($exp_TGLPERIKSA[2], -2);
		} else {
			$pecahtglperiksa = '';
			$pecahbulanperiksa = '';
			$pecahthnperiksa = '';
		}


		$command = Yii::app()->db->createCommand();
		$column = array(

			'TBLDAFTPARKIR_REGKURANGBAYAR' => LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_REGKURANGBAYAR']),
			'TBLDAFTPARKIR_PAJAKPERIKSA' => LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_PAJAKPERIKSA']),
			'TBLDAFTPARKIR_NOMORPERIKSA' => $PARAM['TBLDAFTPARKIR_NOMORPERIKSA'],
			'TBLDAFTPARKIR_BUNGAKRGBAYAR' => LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_BUNGAKRGBAYAR']),
			'TBLDAFTPARKIR_NAKB' => LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_NAKB']),
			'TBLDAFTPARKIR_DENDAKRGBAYAR' => LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_DENDAKRGBAYAR']),
			'TBLDAFTPARKIR_RUPIAHKRGBAYAR' => LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_RUPIAHKRGBAYAR']),
			'TBLDAFTPARKIR_BLNKBAWAL' => $PARAM['TBLDAFTPARKIR_BLNKBAWAL'],
			'TBLDAFTPARKIR_BLNKBAKHIR' => $PARAM['TBLDAFTPARKIR_BLNKBAKHIR'],

			'TBLDAFTPARKIR_TGLKURANGBAYAR' => $pecahtgldaftar,
			'TBLDAFTPARKIR_BLNKURANGBAYAR' => $pecahbulandaftar,
			'TBLDAFTPARKIR_THNKURANGBAYAR' => $pecahthndaftar,

			'TBLDAFTPARKIR_TGLBTSKRGBAYAR' => $pecahtglentry,
			'TBLDAFTPARKIR_BLNBTSKRGBAYAR' => $pecahbulanentry,
			'TBLDAFTPARKIR_THNBTSKRGBAYAR' => $pecahthnentry,

			'TBLDAFTPARKIR_TGLPERIKSA' => $pecahtglperiksa,
			'TBLDAFTPARKIR_BLNPERIKSA' => $pecahbulanperiksa,
			'TBLDAFTPARKIR_THNPERIKSA' => $pecahthnperiksa,

		);

		$simpan = $command->update('TBLDAFTPARKIR', $column ,'TBLDAFTAR_NOPOK =:NOPOK AND TBLPENDATAAN_THNPAJAK =:THNPJK AND TBLPENDATAAN_BLNPAJAK =:TBLPENDATAAN_BLNPAJAK AND (TBLPENDATAAN_TGLPAJAK IS NULL OR TBLPENDATAAN_TGLPAJAK = 0)',array(':NOPOK' => $NOPOK,':THNPJK' => $THNPJK,':TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK));

		/* INSERT TABEL KURANG BAYAR */

		$CekNoRegisterKB = $this->CekNoRegisterKB($THNPJK, $TBLPENDATAAN_BLNPAJAK, $NOPOK);
		$LastNoKB = $this->GetLastNoKB($THNPJK, $TBLPENDATAAN_BLNPAJAK, $NOPOK);

		if ($CekNoRegisterKB==0) {
			$NoRecordKB = '1';
		} else {
			$NoRecordKB = $LastNoKB+1;
		}

		// 

		$sql="SELECT
		TBLDAFTAR.TBLDAFTAR_BADANUSAHANAMA,
		TBLDAFTAR.TBLDAFTAR_NOPOK,
		TBLDAFTAR.TBLDAFTAR_PEMILIKNAMA,
		TBLDAFTAR.TBLDAFTAR_BADANUSAHAALAMAT,
		TBLDAFTAR.TBLDAFTAR_PEMILIKALAMAT,
		TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA,
		TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA,
		TBLDAFTAR.TBLDAFTAR_GOLONGAN
		FROM
		TBLDAFTAR
		WHERE
		TBLDAFTAR.TBLDAFTAR_NOPOK = ".$NOPOK;
		$data['wp'] = Yii::app()->db->createCommand( $sql )->queryRow();

		// echo $CekNoRegisterKB;die();
		$dataspt['spt'] = Yii::app()->db->createCommand()
		->select('*')
		->from('TBLDAFTPARKIR')
		->where('NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0 AND TBLPENDATAAN_THNPAJAK ='.$THNPJK.' AND
			TBLPENDATAAN_BLNPAJAK='.$TBLPENDATAAN_BLNPAJAK.' AND
			TBLDAFTAR_NOPOK='.$NOPOK)
		->queryRow();

		$column = array('TBLPENDATAAN_THNPAJAK'=>$THNPJK
			,'TBLPENDATAAN_BLNPAJAK'=>$TBLPENDATAAN_BLNPAJAK
			,'TBLPENDATAAN_TGLPAJAK'=>'0'
			,'TBLKRGBAYAR_JNSSURAT'=>''
			,'TBLDAFTAR_JNSPENDAPATAN'=>$dataspt['spt']['TBLDAFTAR_JNSPENDAPATAN']
			,'TBLDAFTAR_NOPOK'=>$NOPOK
			,'LOP'=>''
			,'TBLKRGBAYAR_PAJAKKE'=>$NoRecordKB
			,'TBLKRGBAYAR_GOLONGAN'=>$dataspt['spt']['TBLDAFTAR_GOLONGAN']
			,'TBLKECAMATAN_ID'=>$dataspt['spt']['TBLKECAMATAN_ID']
			,'TBLKELURAHAN_ID'=>$dataspt['spt']['TBLKELURAHAN_ID']
			,'TBLKRGBAYAR_NAMABADANUSAHA'=>$data['wp']['TBLDAFTAR_BADANUSAHANAMA']
			,'TBLKRGBAYAR_ALAMATBADANUSAHA'=>$data['wp']['TBLDAFTAR_BADANUSAHAALAMAT']
			,'PJ'=>''
			,'TBLKRGBAYAR_CARAKETETAPAN'=>''
			,'TBLKRGBAYAR_THNKETETAPAN'=>$pecahthndaftar
			,'TBLKRGBAYAR_BLNKETETAPAN'=>$pecahbulandaftar
			,'TBLKRGBAYAR_TGLKETETAPAN'=>$pecahtgldaftar
			,'TBLKRGBAYAR_REGKURANGBAYAR'=>LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_REGKURANGBAYAR'])
			,'TBLKRGBAYAR_THNAWALKETETAPAN'=>'' // DIKOSONGKAN
			,'TBLKRGBAYAR_BLNAWALKETETAPAN'=>'' // DIKOSONGKAN
			,'TBLKRGBAYAR_TGLAWALKETETAPAN'=>'' // DIKOSONGKAN
			,'TBLKRGBAYAR_THNBATASKETETAPAN'=>$pecahthnentry
			,'TBLKRGBAYAR_BLNBATASKETETAPAN'=>$pecahbulanentry
			,'TBLKRGBAYAR_TGLBATASKETETAPAN'=>$pecahtglentry
			,'TBLKRGBAYAR_THNTERIMAKETETAPAN'=>'' // DIKOSONGKAN
			,'TBLKRGBAYAR_BLNTERIMAKETETAPAN'=>'' // DIKOSONGKAN
			,'TBLKRGBAYAR_TGLTERIMAKETETAPAN'=>'' // DIKOSONGKAN
			,'TBLKRGBAYAR_THNENTRIKETETAPAN'=>$pecahthndaftar
			,'TBLKRGBAYAR_BLNENTRIKETETAPAN'=>$pecahbulandaftar
			,'TBLKRGBAYAR_TGLENTRIKETETAPAN'=>$pecahtgldaftar
			,'TBLKRGBAYAR_KETETAPANTOTAL'=> !empty($dataspt['spt']['TBLDAFTPARKIR_PAJAKSKPD']) ? $dataspt['spt']['TBLDAFTPARKIR_PAJAKSKPD'] : ''
			,'TBLKRGBAYAR_SETORAN'=>'' // DARI TABEL SETOR
			,'TBLKRGBAYAR_SISAANGSURAN'=>'' //DATA ANGSURAN
			,'TBLKRGBAYAR_DENDAANGSURAN'=>'' //DATA ANGSURAN
			,'TBLKRGBAYAR_BUNGAANGSURAN'=>'' //DATA ANGSURAN
			,'TBLKRGBAYAR_THNSETORANGSURAN'=>''  //DATA ANGSURAN
			,'TBLKRGBAYAR_BLNSETORANGSURAN'=>''  //DATA ANGSURAN
			,'TBLKRGBAYAR_TGLSETORANGSURAN'=>''  //DATA ANGSURAN
			,'TBLKRGBAYAR_THNENTRISETOR'=>!empty($dataspt['spt']['TBLDAFTPARKIR_THNENTRISETOR']) ? $dataspt['spt']['TBLDAFTPARKIR_THNENTRISETOR'] : ''
			,'TBLKRGBAYAR_BLNENTRISETOR'=>!empty($dataspt['spt']['TBLDAFTPARKIR_BLNENTRISETOR']) ? $dataspt['spt']['TBLDAFTPARKIR_BLNENTRISETOR'] : ''
			,'TBLKRGBAYAR_TGLENTRISETOR'=>!empty($dataspt['spt']['TBLDAFTPARKIR_TGLENTRISETOR']) ? $dataspt['spt']['TBLDAFTPARKIR_TGLENTRISETOR'] : ''
			,'TBLKRGBAYAR_NOMORSETOR'=> '' //DARI TABEL SETOR
			,'TBLKRGBAYAR_REKPENDAPATAN'=>$dataspt['spt']['TBLDAFTPARKIR_REKPENDAPATAN']
			,'TBLKRGBAYAR_REKPAD'=>$dataspt['spt']['TBLDAFTPARKIR_REKPAD']
			,'TBLKRGBAYAR_REKPAJAK'=>$dataspt['spt']['TBLDAFTPARKIR_REKPAJAK']
			,'TBLKRGBAYAR_REKAYAT'=>$dataspt['spt']['TBLDAFTPARKIR_REKAYAT']
			,'TBLKRGBAYAR_REKJENIS'=>$dataspt['spt']['TBLDAFTPARKIR_REKJENIS']
			,'TBLKRGBAYAR_NAMAOPERATOR'=>''
			,'TER'=>''
			,'TBLKRGBAYAR_TGLENTRI'=> ''
			,'TBLKRGBAYAR_PAJAKPERIKSA'=> LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_PAJAKPERIKSA'])
			,'TBLKRGBAYAR_DENDAKRGBAYAR'=> LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_DENDAKRGBAYAR'])
			,'TBLKRGBAYAR_KENAIKANKRGBAYAR'=> LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_NAKB'])
			,'TBLKRGBAYAR_BUNGAKRGBAYAR'=> LokalIndonesia::toAngka($PARAM['TBLDAFTPARKIR_BUNGAKRGBAYAR'])
			,'TBLKRGBAYAR_BLNKBAWAL'=> $PARAM['TBLDAFTPARKIR_BLNKBAWAL']
			,'TBLKRGBAYAR_BLNKBAKHIR'=> $PARAM['TBLDAFTPARKIR_BLNKBAKHIR']
			,'TBLKRGBAYAR_NOMORPERIKSA'=> $PARAM['TBLDAFTPARKIR_NOMORPERIKSA']
			,'TBLKRGBAYAR_ISAKTIF'=>'T'
		);

		$simpan_kb = $command->insert('TBLKRGBAYAR', $column);

		if ($simpan_kb>=0) {
			if ($simpan>=0) {
				echo CJSON::encode(array('status'=>'success'));
			}
			else{
				echo CJSON::encode(array('status'=>'failed'));
			}
		} else {
			echo CJSON::encode(array('status'=>'failed'));
		}
	}

	public function actionHapusSKPDKB()
	{
		Yii::import('ext.LokalIndonesia');

		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];

		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);

		$TBLPENDATAAN_BLNPAJAK = !empty($_REQUEST['TBLPENDATAAN_BLNPAJAK']) ? $_REQUEST['TBLPENDATAAN_BLNPAJAK'] : '';

		$command = Yii::app()->db->createCommand();
		$column = array(

			'TBLDAFTPARKIR_REGKURANGBAYAR' => '',
			'TBLDAFTPARKIR_PAJAKPERIKSA' => '',
			'TBLDAFTPARKIR_NOMORPERIKSA' => '',
			'TBLDAFTPARKIR_BUNGAKRGBAYAR' => '',
			'TBLDAFTPARKIR_NAKB' => '',
			'TBLDAFTPARKIR_DENDAKRGBAYAR' => '',
			'TBLDAFTPARKIR_RUPIAHKRGBAYAR' => '',
			'TBLDAFTPARKIR_BLNKBAWAL' => '',
			'TBLDAFTPARKIR_BLNKBAKHIR' => '',

			'TBLDAFTPARKIR_TGLKURANGBAYAR' => '',
			'TBLDAFTPARKIR_BLNKURANGBAYAR' => '',
			'TBLDAFTPARKIR_THNKURANGBAYAR' => '',

			'TBLDAFTPARKIR_TGLBTSKRGBAYAR' => '',
			'TBLDAFTPARKIR_BLNBTSKRGBAYAR' => '',
			'TBLDAFTPARKIR_THNBTSKRGBAYAR' => '',

			'TBLDAFTPARKIR_TGLPERIKSA' => '',
			'TBLDAFTPARKIR_BLNPERIKSA' => '',
			'TBLDAFTPARKIR_THNPERIKSA' => '',

		);

		$simpan = $command->update('TBLDAFTPARKIR', $column ,'TBLDAFTAR_NOPOK =:NOPOK AND TBLPENDATAAN_THNPAJAK =:THNPJK AND TBLPENDATAAN_BLNPAJAK =:TBLPENDATAAN_BLNPAJAK AND NVL(TBLPENDATAAN_TGLPAJAK, 0) = 0',array(':NOPOK' => $NOPOK,':THNPJK' => $THNPJK,':TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK));

		if ($simpan>=0) {
			echo CJSON::encode(array('status'=>'success'));
		}
		else{
			echo CJSON::encode(array('status'=>'failed'));
		}
	}
	
	public function actionGetNoSKPDKB()
	{
		$tahun = $_REQUEST['tahun'];
		$splthn = substr($tahun, -2);

		$data = Yii::app()->db->createCommand("SELECT
			MAX(TO_NUMBER (TO_CHAR(NVL(TBLDAFTPARKIR_REGKURANGBAYAR, 0))))+1 AS nokb
		FROM
			TBLDAFTPARKIR
		WHERE
			TBLPENDATAAN_THNPAJAK = ".$splthn."
		AND NVL (TBLDAFTPARKIR_REGKURANGBAYAR, 0) <> 0
		ORDER BY
			TO_NUMBER (TO_CHAR(NVL(nokb, 0))) DESC")->queryRow();

		echo CJSON::encode($data);
	}

	public function actionCetak()
	{
		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];
		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);
		$TBLPENDATAAN_BLNPAJAK = $_REQUEST['TBLPENDATAAN_BLNPAJAK'];

        $select = "
        TBLDAFTPARKIR.*,
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BUNGAKRGBAYAR, 0) AS TBLDAFTPARKIR_BUNGAKRGBAYAR, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_DENDAKRGBAYAR, 0) AS TBLDAFTPARKIR_DENDAKRGBAYAR, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) AS TBLDAFTPARKIR_RUPIAHSETOR, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKBAWAL, 0) AS TBLDAFTPARKIR_BLNKBAWAL, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKBAKHIR, 0) AS TBLDAFTPARKIR_BLNKBAKHIR, 
        TBLDAFTAR.*, (
		SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
			TBLREKENING
		WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTPARKIR.TBLDAFTPARKIR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTPARKIR.TBLDAFTPARKIR_REKJENIS
	) AS NMREK,
	(
		SELECT
		TBLREKENING.TBLREKENING_KODEFULL
		FROM
		TBLREKENING
		WHERE
		TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTPARKIR.TBLDAFTPARKIR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTPARKIR.TBLDAFTPARKIR_REKJENIS
		) AS TBLREKENING_KODEFULL,
	(
		SELECT
			REFKECAMATAN.REFKECAMATAN_NAMA
		FROM
			REFKECAMATAN
		WHERE
			REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
	) AS bnmkec,
	(
		SELECT
			REFKELURAHAN.REFKELURAHAN_NAMA
		FROM
			REFKELURAHAN
		WHERE
			REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
		AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_KODE
	) AS bnmkel,
	(
		SELECT
			REFKECAMATAN.REFKECAMATAN_NAMA
		FROM
			REFKECAMATAN
		WHERE
			REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
	) AS pnmkec,
	(
		SELECT
			REFKELURAHAN.REFKELURAHAN_NAMA
		FROM
			REFKELURAHAN
		WHERE
			REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDPEMILIK
		AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
	) AS pnmkel";
        $from = 'TBLDAFTPARKIR';

        $otherquery = array(
             'leftjoin_daftar'=>array('TBLDAFTAR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTPARKIR.TBLDAFTAR_NOPOK')
        );

        $filter = array(
            'EQ__TBLDAFTPARKIR.TBLDAFTAR_NOPOK' => $NOPOK
			,'EQ__TBLDAFTPARKIR.TBLPENDATAAN_THNPAJAK' => $THNPJK
			,'EQ__TBLDAFTPARKIR.TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK
        );

        $arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'otherquery'=>$otherquery,'mode'=>'DETAIL');
        $data['cetak'] = DBFetch::query($arrayConfig);

		$this->renderPartial('cetak',array('data'=>$data));
	}

	public function actionCetakWord()
	{
		// error_reporting(0);

		// baca file template, yg dipakai
		// $gettpl = MasterTemplate::model()->find('tblmastertemplate_jenis="WORD" AND tblmastertemplate_kelompok="tpl_bakecamatan" AND tblmastertemplate_isaktif="T"');
		
		// echo "$query";
		
		// $data['list_kartudata'] = Yii::app()->db->createCommand($query)->queryAll();

		$path_tpl =  dirname(Yii::app()->basePath) . DIRECTORY_SEPARATOR . 'file' . DIRECTORY_SEPARATOR . 'tpl_skpdkb' . DIRECTORY_SEPARATOR;
		$namatpl = $path_tpl . 'skpdkb.docx';

		Yii::import('ext.DMOpenTBS',true);
		Yii::import('ext.LokalIndonesia');
		DMOpenTBS::init();
		$otbs = new clsTinyButStrong;

		// Useful for debugging purposes. Displays the errors
		$otbs->NoErr = 0;
		$otbs->Plugin(TBS_INSTALL, OPENTBS_PLUGIN); // load the OpenTBS plugin

		$template = $namatpl;
		$otbs->LoadTemplate($template, OPENTBS_ALREADY_UTF8); // load the template

		// Delete a sheet 
		// $otbs->PlugIn(OPENTBS_DELETE_SHEETS, 'Delete me'); 


		// Display a sheet (make it visible) 
		// $otbs->PlugIn(OPENTBS_DISPLAY_SHEETS, 'Display me'); 

		// Change the current sheet 
		// $otbs->PlugIn(OPENTBS_SELECT_SHEET, 2); 

		// A recordset for merging tables

		//INI CODING QUERY CETAK WORD

		$NOPOK = $_REQUEST['TBLDAFTAR_NOPOK'];
		$TBLPENDATAAN_THNPAJAK = $_REQUEST['TBLPENDATAAN_THNPAJAK'];
		$THNPJK = substr($TBLPENDATAAN_THNPAJAK, 2,4);
		$TBLPENDATAAN_BLNPAJAK = $_REQUEST['TBLPENDATAAN_BLNPAJAK'];

        $select = "
        TBLDAFTPARKIR.*,
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BUNGAKRGBAYAR, 0) AS TBLDAFTPARKIR_BUNGAKRGBAYAR, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_DENDAKRGBAYAR, 0) AS TBLDAFTPARKIR_DENDAKRGBAYAR,
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_NAKB, 0) AS TBLDAFTPARKIR_NAKB, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_RUPIAHSETOR, 0) AS TBLDAFTPARKIR_RUPIAHSETOR, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKBAWAL, 0) AS TBLDAFTPARKIR_BLNKBAWAL, 
        NVL(TBLDAFTPARKIR.TBLDAFTPARKIR_BLNKBAKHIR, 0) AS TBLDAFTPARKIR_BLNKBAKHIR, 
        TBLDAFTAR.*, (
		SELECT
			TBLREKENING.TBLREKENING_NAMAREKENING
		FROM
			TBLREKENING
		WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPENDAPATAN
		AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAD
		AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAJAK
		AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTPARKIR.TBLDAFTPARKIR_REKAYAT
		AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTPARKIR.TBLDAFTPARKIR_REKJENIS
		) AS NMREK,
		(
			SELECT
			TBLREKENING.TBLREKENING_KODEFULL
			FROM
			TBLREKENING
			WHERE
			TBLREKENING.TBLREKENING_REKPENDAPATAN = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPENDAPATAN
			AND TBLREKENING.TBLREKENING_REKPAD = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAD
			AND TBLREKENING.TBLREKENING_REKPAJAK = TBLDAFTPARKIR.TBLDAFTPARKIR_REKPAJAK
			AND TBLREKENING.TBLREKENING_REKAYAT = TBLDAFTPARKIR.TBLDAFTPARKIR_REKAYAT
			AND TBLREKENING.TBLREKENING_REKJENIS = TBLDAFTPARKIR.TBLDAFTPARKIR_REKJENIS
			) AS TBLREKENING_KODEFULL,
		(
			SELECT
				REFKECAMATAN.REFKECAMATAN_NAMA
			FROM
				REFKECAMATAN
			WHERE
				REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDBADANUSAHA
		) AS bnmkec,
		(
			SELECT
				REFKELURAHAN.REFKELURAHAN_NAMA
			FROM
				REFKELURAHAN
			WHERE
				REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDBADANUSAHA
			AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_KODE
		) AS bnmkel,
		(
			SELECT
				REFKECAMATAN.REFKECAMATAN_NAMA
			FROM
				REFKECAMATAN
			WHERE
				REFKECAMATAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
		) AS pnmkec,
		(
			SELECT
				REFKELURAHAN.REFKELURAHAN_NAMA
			FROM
				REFKELURAHAN
			WHERE
				REFKELURAHAN.REFKELURAHAN_ID = TBLDAFTAR.TBLKELURAHAN_IDPEMILIK
			AND REFKELURAHAN.REFKECAMATAN_ID = TBLDAFTAR.TBLKECAMATAN_IDPEMILIK
		) AS pnmkel";
        $from = 'TBLDAFTPARKIR';

        $otherquery = array(
             'leftjoin_daftar'=>array('TBLDAFTAR', 'TBLDAFTAR.TBLDAFTAR_NOPOK = TBLDAFTPARKIR.TBLDAFTAR_NOPOK')
        );

        $filter = array(
            'EQ__TBLDAFTPARKIR.TBLDAFTAR_NOPOK' => $NOPOK
			,'EQ__TBLDAFTPARKIR.TBLPENDATAAN_THNPAJAK' => $THNPJK
			,'EQ__TBLDAFTPARKIR.TBLPENDATAAN_BLNPAJAK' => $TBLPENDATAAN_BLNPAJAK
        );

        $arrayConfig = array('select'=>$select,'from'=>$from,'filter'=>$filter,'otherquery'=>$otherquery,'mode'=>'DETAIL');
        $data['cetak'] = DBFetch::query($arrayConfig);

        $sql1="SELECT * FROM TBLPEJABAT WHERE REFJABATAN_ID = 6";

		$data['jab1'] = Yii::app()->db->createCommand($sql1)->queryRow();

		$dt = array();

		$dt['nopok'] = $data['cetak']['TBLDAFTAR_NOPOK'];
		$dt['jabatan'] = $data['jab1']['TBLPEJABAT_URAIAN'];
		$dt['petugas'] = $data['jab1']['TBLPEJABAT_NAMA'];
		$dt['nip'] = $data['jab1']['TBLPEJABAT_NIP'];
		$dt['thnkb'] = '20'.$data['cetak']['TBLDAFTPARKIR_THNKURANGBAYAR'];
		$dt['blnkbawal'] = LokalIndonesia::getbulan($data['cetak']['TBLDAFTPARKIR_BLNKBAWAL']);
		$dt['blnkbakhir'] = LokalIndonesia::getbulan($data['cetak']['TBLDAFTPARKIR_BLNKBAKHIR']);
		$dt['regkb'] = $data['cetak']['TBLDAFTPARKIR_REGKURANGBAYAR'];

		$dt['namabadan'] = $data['cetak']['TBLDAFTAR_BADANUSAHANAMA'];
		$dt['namapemilik'] = $data['cetak']['TBLDAFTAR_PEMILIKNAMA'];
		$dt['alamatbadan'] = $data['cetak']['TBLDAFTAR_BADANUSAHAALAMAT'];
		$dt['alamatpemilik'] = $data['cetak']['TBLDAFTAR_PEMILIKALAMAT'];

		$dt['kodefull'] = $data['cetak']['TBLREKENING_KODEFULL'];

		$dt['namarek'] = $data['cetak']['NMREK'];

		$dt['namarek'] = $data['cetak']['NMREK'];

		$dt['jatuhtempo'] = $data['cetak']['TBLDAFTPARKIR_TGLBTSKRGBAYAR'] .'/'. $data['cetak']['TBLDAFTPARKIR_BLNBTSKRGBAYAR'] .'/20'.$data['cetak']['TBLDAFTPARKIR_THNBTSKRGBAYAR'];

		$dt['pajakperiksa'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_PAJAKPERIKSA']);
		$dt['bunga'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_BUNGAKRGBAYAR']);
		$dt['denda'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_DENDAKRGBAYAR']);
		$dt['naik'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_NAKB']);
		$dt['setoran'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_RUPIAHSETOR']);
		$dt['kurangbayar'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_RUPIAHKRGBAYAR']);
		$dt['total'] = LokalIndonesia::rupiah($data['cetak']['TBLDAFTPARKIR_RUPIAHKRGBAYAR']);
		$dt['terbilang'] = LokalIndonesia::terbilangangka($data['cetak']['TBLDAFTPARKIR_RUPIAHKRGBAYAR']);

		$dt['thnpajak'] = '20'.$data['cetak']['TBLPENDATAAN_THNPAJAK'];

		$dt['npwpd'] = $data['cetak']['TBLDAFTAR_JENISPENDAPATAN'] .'.'. $data['cetak']['TBLDAFTAR_GOLONGAN'] .'.'. $data['cetak']['TBLDAFTAR_NOPOK'] .'.'. sprintf("%02d",$data['cetak']['TBLKECAMATAN_IDBADANUSAHA']) .'.'. sprintf("%02d",$data['cetak']['TBLKELURAHAN_IDBADANUSAHA']);

		// $dt['totalpajak'] = LokalIndonesia::ribuan($totalpajak['totalpajak']);
		$dt['datenow'] = date('d') .' '. LokalIndonesia::getbulan(date('m')) .' '. date('Y');
		
		//SAMPAI SINI QUERYNYA

		// var_dump($data);
		// echo json_encode($data['cetak']);Yii::app()->end();
		// echo json_encode($row);

		// Merge data in the first sheet 
		$npwpd = $data['cetak']['TBLDAFTAR_NOPOK'];
		$namafileDL = "SKPDKB-PARKIR-".$npwpd.".docx";
		$otbs->MergeField('dt', $dt); 
		// $otbs->MergeField('setoran', $setoran); 
		// $otbs->PlugIn(OPENTBS_DEBUG_XML_CURRENT); // debug the template

		$otbs->Show(OPENTBS_DOWNLOAD, $namafileDL);
		Yii::app()->end();
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}